#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include "airship.h"
#include "animation.h"
#include "app.h"
#include "audio/game_sound.h"
#include "code_module.h"
#include "collision.h"
#include "effect_update.h"
#include "global.h"
#include "hq.h"
#include "map.h"
#include "mechanoid.h"
#include "mission.h"
#include "model.h"
#include "object.h"
#include "player.h"
#include "projectile.h"
#include "psx.h"
#include "random.h"
#include "runtime_heap.h"
#include "sprite.h"
#include "sprite_renderer.h"
#include "stubs.h"
#include "vram_alloc.h"

/* Types. */
/* Semantic module generated by tools/merge_semantic_modules.py.
 * Original MIPS address comments remain attached to each function. */
typedef struct
{
    COLLISION collision;            /* +0x000 */
    sint16 health;                  /* +0x078 */
    sint16 hit_flash_timer;         /* +0x07A */
    MODEL_NODE nodes[15];           /* +0x07C */
    uint8 reserved_61c[0x60];       /* +0x61C */
    MODEL_NODE *node_table[15];     /* +0x67C */
    sint32 reserved_6b8;            /* +0x6B8 */
    sint32 aim_line[6];             /* +0x6BC */
    sint32 base_y;                  /* +0x6D4 */
    sint32 min_x;                   /* +0x6D8 */
    sint32 max_x;                   /* +0x6DC */
    sint32 velocity_x;              /* +0x6E0 */
    sint32 target_velocity_x;       /* +0x6E4 */
    sint32 saved_target_velocity_x; /* +0x6E8 */
    sint16 bomb_cooldown;           /* +0x6EC */
    sint16 target_yaw;              /* +0x6EE */
    uint16 attack_timer;            /* +0x6F0 */
    uint16 reserved_6f2;            /* +0x6F2 */
    sint16 aim_yaw_jitter;          /* +0x6F4 */
    uint16 destruction_timer;       /* +0x6F6 */
} AIRSHIP_ACTOR;

#if defined(AP_32BIT)
typedef char AirshipActor_size_6f8[sizeof(AIRSHIP_ACTOR) == 0x6f8 ? 1 : -1];
typedef char AirshipActor_nodes_at_07c[offsetof(AIRSHIP_ACTOR, nodes) == 0x07c ? 1 : -1];
typedef char AirshipActor_node_table_at_67c[offsetof(AIRSHIP_ACTOR, node_table) == 0x67c ? 1 : -1];
typedef char AirshipActor_aim_line_at_6bc[offsetof(AIRSHIP_ACTOR, aim_line) == 0x6bc ? 1 : -1];
typedef char AirshipActor_destruction_timer_at_6f6[offsetof(AIRSHIP_ACTOR, destruction_timer) == 0x6f6 ? 1 : -1];
#endif

/* AIRSHIP M3 effect type 0x47: exact resident constructor/update/damage
 * closure rooted at 0x800A4CD4. */

typedef struct
{
    COLLISION collision;         /* +0x000 */
    sint16 health;               /* +0x078 */
    sint16 flash_clut_ticks;     /* +0x07A */
    VRAM_SPRITE vram_descriptor; /* +0x07C */
    ANIM animation;              /* +0x0AC */
    sint32 velocity_x;           /* +0x0C8 */
    sint32 velocity_y;           /* +0x0CC */
    sint32 velocity_z;           /* +0x0D0 */
    sint32 field_d4;             /* +0x0D4 */
    sint32 yaw;                  /* +0x0D8 */
    sint32 field_dc;             /* +0x0DC */
    EFFECT *owner_effect;        /* +0x0E0 */
    EFFECT *route[16];           /* +0x0E4 */
    sint16 route_count;          /* +0x124 */
    sint16 route_index;          /* +0x126 */
    sint16 route_step;           /* +0x128 */
    sint16 field_12a;            /* +0x12A */
    sint16 sound_handle;         /* +0x12C */
    sint16 field_12e;            /* +0x12E */
} AIRSHIP_DRONE;

typedef struct
{
    COLLISION collision;     /* +0x00 */
    sint16 field_78;         /* +0x78 */
    sint16 flash_clut_ticks; /* +0x7A */
    ANIM animation;          /* +0x7C */
    uint8 reserved_98[8];    /* +0x98 */
    uint16 state;            /* +0xA0 */
    uint16 field_a2;         /* +0xA2 */
    sint16 input_latch;      /* +0xA4 */
    sint16 collision_latch;  /* +0xA6 */
    sint16 cooldown;         /* +0xA8 */
    sint16 field_aa;         /* +0xAA */
    EFFECT *effect;          /* +0xAC */
} AIRSHIP_SWITCH;

#if defined(AP_32BIT)
typedef char AirshipDrone_size_130[sizeof(AIRSHIP_DRONE) == 0x130 ? 1 : -1];
typedef char AirshipDrone_animation_at_ac[offsetof(AIRSHIP_DRONE, animation) == 0xac ? 1 : -1];
typedef char AirshipDrone_route_at_e4[offsetof(AIRSHIP_DRONE, route) == 0xe4 ? 1 : -1];
typedef char AirshipSwitch_size_b0[sizeof(AIRSHIP_SWITCH) == 0xb0 ? 1 : -1];
typedef char AirshipSwitch_animation_at_7c[offsetof(AIRSHIP_SWITCH, animation) == 0x7c ? 1 : -1];
#endif

/* AIRSHIP M3 type 0x30 lift/door volume, resident 0x8009FFD0 closure. */

typedef struct
{
    COLLISION collision;       /* +0x00 */
    uint8 reserved_78[4];      /* +0x78 */
    sint32 delta_y;            /* +0x7C */
    sint32 cell_width;         /* +0x80 */
    sint32 cell_height;        /* +0x84 */
    sint32 cell_depth;         /* +0x88 */
    EFFECT *waypoints[10];     /* +0x8C */
    sint16 waypoint_count;     /* +0xB4 */
    sint16 waypoint_step;      /* +0xB6 */
    sint16 waypoint_index;     /* +0xB8 */
    sint16 wait_timer;         /* +0xBA */
    sint16 sound_handle;       /* +0xBC */
    uint8 enabled;             /* +0xBE */
    uint8 field_bf;            /* +0xBF */
    uint8 completed_trips;     /* +0xC0 */
    uint8 sound_disabled;      /* +0xC1 */
    uint8 previous_gate_state; /* +0xC2 */
    uint8 field_c3;            /* +0xC3 */
} AIRSHIP_LIFT;

#if defined(AP_32BIT)
typedef char AirshipLift_size_c4[sizeof(AIRSHIP_LIFT) == 0xc4 ? 1 : -1];
typedef char AirshipLift_waypoints_at_8c[offsetof(AIRSHIP_LIFT, waypoints) == 0x8c ? 1 : -1];
typedef char AirshipLift_enabled_at_be[offsetof(AIRSHIP_LIFT, enabled) == 0xbe ? 1 : -1];
#endif

/* Functions. */
/* Exact resident helper 0x800AD8A8..0x800AD9DC.  The four selected hierarchy
 * nodes define a dynamic collision box around the visible airship body. */
/* Original: FUN_800AD8A8. */
void hierarchy_collision_box_update(COLLISION *object, MODEL_NODE *first_node, sint32 count)
{
    MODEL_NODE *node = first_node;
    sint32 n;
    sint32 min_x = node->world_x, min_y = node->world_y, min_z = node->world_z;
    sint32 max_x = min_x, max_y = min_y, max_z = min_z;
    for (n = 1; n < count; n++)
    {
        ++node;
        if (node->world_x < min_x)
            min_x = node->world_x;
        if (max_x < node->world_x)
            max_x = node->world_x;
        if (node->world_y < min_y)
            min_y = node->world_y;
        if (max_y < node->world_y)
            max_y = node->world_y;
        if (node->world_z < min_z)
            min_z = node->world_z;
        if (max_z < node->world_z)
            max_z = node->world_z;
    }
    collision_box_set(object, (max_x - min_x) / 0x100, (max_y - min_y) / 0x100, (max_z - min_z) / 0x100);
    object->box_y += (((max_y - min_y) / 0x100) >> 1) << 8;
}

/* Exact projectile trail callback 0x800AEA54..0x800AEB04. */
/* Original: FUN_800AEA54. */
void explosive_projectile_trail_update(PROJECTILE *projectile)
{
#ifdef AP_WIN
    {
        const char *trace = getenv("OA_AIRFIELD_TRACE");
        if (trace && *trace)
        {
            FILE *file = fopen("../status/airfield-native.log", "a");
            if (file)
            {
                fprintf(file, "AIRFIELD_NATIVE_TRAIL tick=%u\n", g_frame_counter);
                fclose(file);
            }
        }
    }
#endif
    if ((g_frame_counter & 7) == 0)
    {
        SPRITE *p = world_sprite_create(projectile->collision.x, projectile->collision.y + 0x1000, projectile->collision.z, (const sint32 *)player_assets_executable_address(0x800c8bc8u));
        p->velocity_x = projectile->motion[3] / 1280;
        p->velocity_y = projectile->motion[4] / 1280;
        p->velocity_z = projectile->motion[5] / 1280;
    }
}

/* Exact projectile impact callback 0x800AEB08..0x800AEC30. */
/* Original: FUN_800AEB08. */
void explosive_projectile_impact(PROJECTILE *projectile)
{
#ifdef AP_WIN
    const char *airfield_trace = getenv("OA_AIRFIELD_TRACE");
    #define AIRFIELD_STEP(label)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
        do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
            if (airfield_trace && *airfield_trace)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
                FILE *file = fopen("../status/airfield-native.log", "a");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
                if (file)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \
                {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
                    fprintf(file, "AIRFIELD_NATIVE_IMPACT_STEP %s\n", label);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
                    fclose(file);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
                }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
            }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
        } while (0)
#else
    #define AIRFIELD_STEP(label) ((void)0)
#endif
#ifdef AP_WIN
    {
        const char *trace = getenv("OA_AIRFIELD_TRACE");
        if (trace && *trace)
        {
            FILE *file = fopen("../status/airfield-native.log", "a");
            if (file)
            {
                fprintf(file, "AIRFIELD_NATIVE_IMPACT xyz=%d,%d,%d\n", projectile->collision.x, projectile->collision.y, projectile->collision.z);
                fclose(file);
            }
        }
    }
#endif
    SPRITE *impact = world_sprite_create(projectile->collision.x, projectile->collision.y, projectile->collision.z, (const sint32 *)player_assets_executable_address(0x800c8b5cu));
    AIRFIELD_STEP("actor");
    sound_play_positional(9, 0, 0xc8, projectile->collision.x, projectile->collision.y, projectile->collision.z);
    AIRFIELD_STEP("sound");
    timed_callback_create(expl_debris_particle_create, projectile->collision.x, projectile->collision.y, projectile->collision.z, 0x13, 2);
    AIRFIELD_STEP("effect");
    impact->scale_x = (uint16)(random_range(0x800) + 0x2000);
    collision_box_set(impact, 0x78, 0x60, 0x60);
    impact->collision.callback_14 = player_apply_damage;
    AIRFIELD_STEP("bounds");
    impact->collision.receives_mask = 6;
    impact->collision.sends_mask = 0x10;
    impact->collision.object_type = 2;
    impact->damage = 0xcc;
    impact->collision.box_y += 0x1000;
    player_particle_ring_create(impact->collision.x, impact->collision.y, impact->collision.z, 0x0c, 3);
    AIRFIELD_STEP("rings");
    expl_flash_create(impact->collision.x, impact->collision.y - 0x4000, impact->collision.z - 0x100);
    AIRFIELD_STEP("blast");
#undef AIRFIELD_STEP
}

/* Original: AIRSHIP_800FAF60. */
static void airship_update(AIRSHIP_ACTOR *actor)
{
    static const MATRIX identity = {{{4096, 0, 0}, {0, 4096, 0}, {0, 0, 4096}}, {0, 0, 0}};
    MODEL_NODE *root = &actor->nodes[0];
    MODEL_NODE *projectile_origin = &actor->nodes[5];
    MODEL_NODE *bomb_origin = &actor->nodes[7];
    MODEL_NODE *bomb_target = &actor->nodes[8];
    MODEL_NODE *aim_origin = &actor->nodes[9];
    sint32 target_y, angle, v, abs_v;

    if (actor->destruction_timer != 0)
    {
        if (actor->collision.x < g_camera_world_x)
            actor->target_velocity_x = 0x200;
        if (g_camera_world_x < actor->collision.x)
            actor->target_velocity_x = -0x200;
        actor->destruction_timer++;
        if (actor->destruction_timer == 0xdc)
            g_airship_destruction_complete = 1;
    }
    if (actor->collision.x < actor->min_x)
    {
        actor->target_velocity_x = 0x300;
        actor->target_yaw = 0x400;
    }
    if (actor->max_x < actor->collision.x)
    {
        actor->target_velocity_x = -0x300;
        actor->target_yaw = 0xbf8;
    }
    if (actor->velocity_x < actor->target_velocity_x)
        actor->velocity_x += 0x20;
    if (actor->target_velocity_x < actor->velocity_x)
        actor->velocity_x -= 0x20;
    actor->collision.x += actor->velocity_x;
    actor->nodes[1].rotation_z = (sint16)((g_frame_counter << 8) & 0xfff);
    if ((g_frame_counter & 0x3f) == 0)
        actor->aim_yaw_jitter = (sint16)(random_range(0x400) - 0x200);

    fixed_dda_initialize(aim_origin->world_x, aim_origin->world_y, aim_origin->world_z, g_player_world_x, g_player_world_y - 0x3000, g_player_world_z, actor->aim_line);
    angle = ((fixed_angle_from_vector(div_2048_trunc(actor->aim_line[3]), div_2048_trunc(actor->aim_line[5])) << 2) - root->rotation_y + actor->aim_yaw_jitter) & 0xfff;
    actor->nodes[9].rotation_y = angle_approach_wrapped((sint16)angle, 0x20, actor->nodes[9].rotation_y);
    actor->nodes[5].rotation_y = angle_approach_wrapped((sint16)((angle - actor->aim_yaw_jitter) & 0xfff), 0x40, actor->nodes[5].rotation_y);

    target_y = actor->base_y;
    actor->attack_timer--;
    if ((sint16)actor->attack_timer < 0x201)
    {
        if (actor->attack_timer == 0x200)
            actor->saved_target_velocity_x = actor->target_velocity_x;
        actor->target_velocity_x = 0;
        if ((sint16)actor->attack_timer < 0x1c4)
            target_y += 0xe400;
        if ((sint16)actor->attack_timer < 0x188)
        {
            if ((sint16)actor->attack_timer < 0x16a)
            {
                v = (0x320 - actor->health) / 12 + 0x30;
                if (v > 0x64)
                    v = 0x64;
                actor->nodes[2].rotation_y = (sint16)((actor->nodes[2].rotation_y + v) & 0xfff);
            }
            else
            {
                actor->nodes[2].rotation_y = angle_approach_wrapped((sint16)((actor->nodes[5].rotation_y + 0x400) & 0xfff), 0x40, actor->nodes[2].rotation_y);
            }
            if (actor->bomb_cooldown == 0)
            {
                PROJECTILE *projectile;
                actor->bomb_cooldown = 1;
                projectile = projectile_create(bomb_origin->world_x, bomb_origin->world_y - 0x100, bomb_origin->world_z, bomb_target->world_x, bomb_target->world_y - 0x100, bomb_target->world_z);
                projectile->motion[3] *= 3;
                projectile->motion[4] *= 3;
                projectile->motion[5] *= 3;
            }
            else
                actor->bomb_cooldown--;
        }
        if (actor->attack_timer == 0)
        {
            actor->target_velocity_x = actor->saved_target_velocity_x;
            actor->attack_timer = (uint16)(random_range(0x100) + 0x32c);
        }
    }

    if (actor->destruction_timer != 0)
    {
        sint32 projected = (-((actor->collision.z - g_camera_world_z) * 0x10) / 355) + g_camera_world_y;
        actor->collision.y += (actor->destruction_timer < 0x64 && projected < actor->collision.y) ? -0x200 : 0x200;
        if ((g_frame_counter & 3) == 0)
        {
            sint32 x;
            SPRITE *debris;
            if ((g_frame_counter & 0xf) == 0)
                sound_play_nonpositional(9, 0, 0x7f);
            x = actor->collision.x + (random_range(0xc8) - 0x64) * 0x100;
            debris = world_sprite_create(x, actor->collision.y + (random_range(0x50) - 0x28) * 0x100, actor->collision.z - 0x2000, (const sint32 *)win_code_module_address(0x800fb7d8));
            debris->scale_x = 0x1400;
            if (random_range(8) == 0)
                expl_flash_create(actor->collision.x, actor->collision.y, actor->collision.z - 0x2000);
        }
    }
    else
    {
        v = actor->collision.y - target_y;
        abs_v = v < 0 ? -v : v;
        if (abs_v > 0x400)
            abs_v = 0x400;
        actor->collision.y += target_y < actor->collision.y ? -abs_v : abs_v;
    }

    root->rotation_y = actor->destruction_timer == 0 ? angle_approach_wrapped(actor->target_yaw, 0x10, root->rotation_y) : (sint16)((uint16)root->rotation_y + 0x40);
    root->rotation_y &= 0xfff;
    v = actor->velocity_x;
    if (v < 0)
        v = -v;
    root->rotation_x = (sint16)(v / 21);
    root->translation_x = actor->collision.x - g_camera_world_x;
    root->translation_y = actor->collision.y + player_bob_offset_update(0) - g_camera_world_y;
    root->translation_z = actor->collision.z - g_camera_world_z;
    g_render_depth_bucket = 0x480 - (g_render_row_world_z - actor->collision.z) / 0x100;
    g_current_model_world_z = actor->collision.z;
    if (actor->hit_flash_timer != 0)
    {
        g_model_clut_override = g_hit_flash_clut;
        actor->hit_flash_timer--;
    }
    g_model_render_frame = g_current_render_frame;
    model_render_node(root, (MATRIX *)&identity);
    hierarchy_collision_box_update(actor, &actor->nodes[11], 4);
    g_model_clut_override = 0;

    if ((sint16)actor->attack_timer >= 0x201 && (g_frame_counter & 0x7f) == 0 && actor->destruction_timer == 0)
    {
        PROJECTILE *projectile = projectile_create(projectile_origin->world_x, projectile_origin->world_y, projectile_origin->world_z, g_player_world_x, g_player_world_y - 0x2000, g_player_world_z);
        projectile->damage = 0x80;
        projectile->floor_callback = (FUNC_COLLISION_UPDATE)explosive_projectile_trail_update;
        projectile->impact_callback = (FUNC_COLLISION_UPDATE)explosive_projectile_impact;
        projectile->collision.object_type = 0;
        projectile->collision.receives_mask |= 4;
        projectile->motion[3] *= 2;
        projectile->motion[4] *= 2;
        projectile->motion[5] *= 2;
        sound_play_positional(10, 0, 0x96, actor->collision.x, actor->collision.y, actor->collision.z);
        speech_random_request(10);
    }
    hud_bar_render(g_boss_health_bar, actor->health, 0, 0);
}

/* Original: AIRSHIP_800FB6C8. */
static void airship_damage(AIRSHIP_ACTOR *actor, void *source)
{
    if (object_damage_apply(actor, source))
    {
        speech_random_request(10);
        expl_flash_create(actor->collision.x, actor->collision.y, actor->collision.z);
        actor->destruction_timer = 1;
        actor->collision.receives_mask = 0;
    }
}

/* Original: AIRSHIP_800FADD4. */
void airship_create(EFFECT *effect)
{
    AIRSHIP_ACTOR *actor = (AIRSHIP_ACTOR *)runtime_heap_allocate(sizeof(*actor));
    const sint16 *models = (const sint16 *)win_code_module_address(0x800fb73c);
    sint32 n;
    effect->type = 0;
    actor->collision.update = (FUNC_COLLISION_UPDATE)airship_update;
    linked_list_append(g_object_list, actor);
    actor->collision.object_type = 0x81;
    for (n = 0; n < 15; n++)
    {
        MODEL_NODE *node = &actor->nodes[n];
        actor->node_table[n] = node;
        node->model_id = models[n] == -1 ? 0 : models[n];
        node->render_flags = 0x3f;
    }
    actor->nodes[0].scale = 0x1000;
    model_initialize_pose(win_code_module_address(0x800fb75c), actor->node_table, 1);
    actor->collision.x = effect->x;
    actor->collision.y = effect->y - 0x4000;
    actor->collision.z = effect->z - 0x3000;
    actor->collision.callback_18 = (FUNC_COLLISION_CALLBACK)airship_damage;
    actor->health = 0x320;
    actor->collision.receives_mask = 1;
    actor->base_y = actor->collision.y;
    actor->min_x = actor->collision.x - 0xc800;
    actor->max_x = actor->collision.x + 0xc800;
    actor->target_velocity_x = 0x300;
    actor->target_yaw = 0x400;
    actor->attack_timer = 0x52c;
    hud_bar_initialize(g_boss_health_bar, -0x28, -0x60, 0x50, 0x320);
}

/* Original: FUN_800A565C. */
static void jetpack_enemy_damage(AIRSHIP_DRONE *object, void *source)
{
    destroyable_object_damage_and_reward(object, source);
    if (object->health <= 0)
        sound_voice_stop(&object->sound_handle);
}

/* Exact 0x800A4C1C..0x800A4CD0. */
/* Original: FUN_800A4C1C. */
void parachute_bomb_update(SPRITE *o)
{
    if (g_render_row_world_z < o->collision.z)
        object_destroy(o);
    if (o->animation.frame == 0x27804)
        o->velocity_y = 0x80;
    if (o->velocity_y == 0x80)
    {
        o->rotation_x = (sint16)(((uint16)o->rotation_x + o->field_c8) & 0x3ff);
        if ((uint16)((uint16)o->rotation_x - 0x21) < 0x1df)
            o->field_c8 = -2;
        if ((uint16)((uint16)o->rotation_x - 0x201) < 0x1df)
            o->field_c8 = 2;
    }
}

/* Exact 0x800A59E8..0x800A5A84. */
/* Original: FUN_800A59E8. */
void parachute_bomb_explode(SPRITE *source)
{
    SPRITE *p = world_sprite_create(source->collision.x, source->collision.y, source->collision.z, (const sint32 *)player_assets_executable_address(0x800c8b5cu));
    p->scale_x = 0x1555;
    object_destroy(source);
    p->collision.receives_mask = 2;
    p->collision.callback_14 = (FUNC_COLLISION_CALLBACK)player_apply_damage;
    collision_box_set(p, 0x40, 0x40, 0x40);
    sound_play_positional(9, 0, 0x7f, p->collision.x, p->collision.y, p->collision.z);
}

/* Original: FUN_800A4EA8. */
static void jetpack_enemy_update(AIRSHIP_DRONE *object)
{
    sint32 tx, ty, tz, frame = 0x1540a, depth, scale, flare_scale;
    EFFECT *waypoint;
    void *sound;
    if (!world_object_is_visible(object->collision.x, object->collision.y, object->collision.z, 0x20000))
    {
        if (object->vram_descriptor.region_token != 0)
            sprite_vram_defer_release(&object->vram_descriptor);
        object->owner_effect->type = 0x47;
        sound_voice_stop(&object->sound_handle);
        object_destroy(object);
        return;
    }
    if (object->vram_descriptor.region_token == 0)
    {
        g_vram_error_reporting_enabled = 0;
        if (!sprite_vram_allocate(&object->vram_descriptor, 0x40, 0x4c, 1))
        {
            object->owner_effect->type = 0x47;
            object_destroy(object);
            sound_voice_stop(&object->sound_handle);
            g_vram_error_reporting_enabled = 1;
            return;
        }
        /* 800A4F84 LHU reads 800D7682, the mutable palette-table element
         * 800D75D8 + 2*(15400 >> 10), populated by 8008CDE0..8008CDEC. */
        g_vram_error_reporting_enabled = 1;
        object->vram_descriptor.clut = g_resource_clut_table[0x15400u >> 10];
    }
    animation_update(&object->animation);
    object->collision.x += object->velocity_x;
    object->collision.y += object->velocity_y;
    object->collision.z += object->velocity_z;
    if (object->sound_handle == -1)
    {
        if (object->animation.next_address == 0)
            object->sound_handle = (sint16)sound_play_positional(0x2b, 0, 0x40, object->collision.x, object->collision.y, object->collision.z);
    }
    else
    {
        sound = sound_spatial_volume_calculate(0x40, object->collision.x, object->collision.y, object->collision.z);
        if (sound)
            sound_voice_spatial_volume_update(sound, object->sound_handle);
        else
            sound_voice_stop(&object->sound_handle);
    }
    if (object->animation.next_address != 0)
    {
        animation_update(&object->animation);
        frame = object->animation.frame;
        if (frame == 0x15405)
            object->velocity_y = -0x300;
    }
    else
    {
        if ((g_frame_counter & 0x3f) == 0)
        {
            SPRITE *p = world_sprite_create(object->collision.x, object->collision.y, object->collision.z, (const sint32 *)player_assets_executable_address(0x800caddcu));
            p->velocity_y = 0x200;
            p->collision_callback = parachute_bomb_explode;
            p->frame_callback = parachute_bomb_update;
            p->collision.receives_mask = 0;
            p->acceleration_y = 0;
            p->field_c8 = 2;
            p->velocity_x = g_player_world_x < object->collision.x ? -0x80 : 0x80;
            p->velocity_z = g_player_world_z < object->collision.z ? -0x80 : 0x80;
        }
        waypoint = object->route[object->route_index];
        if (!waypoint)
            fatal_error_with_value("NO ROUTE %d", (sint16)object->owner_effect->values[0]);
        tx = waypoint->x;
        ty = waypoint->y;
        tz = waypoint->z;
        if (tx - 0x3000 < object->collision.x && object->collision.x < tx + 0x3000 && ty - 0x3000 < object->collision.y && object->collision.y < ty + 0x3000 && tz - 0x3000 < object->collision.z && object->collision.z < tz + 0x3000)
        {
            object->route_index = (sint16)((uint16)object->route_index + (uint16)object->route_step);
            if (object->route_index == object->route_count)
                object->route_index = 0;
            if (object->route_index < 0)
                object->route_index = (sint16)((uint16)object->route_count - 1);
            waypoint = object->route[object->route_index];
            tx = waypoint->x;
            ty = waypoint->y;
            tz = waypoint->z;
        }
        if (object->collision.x < tx && object->velocity_x < 0x300)
            object->velocity_x += 0x20;
        if (tx < object->collision.x && object->velocity_x >= -0x2ff)
            object->velocity_x -= 0x20;
        if (object->collision.y < ty && object->velocity_y < 0x200)
            object->velocity_y += 0x20;
        if (ty < object->collision.y && object->velocity_y >= -0x1ff)
            object->velocity_y -= 0x20;
        if (object->collision.z < tz && object->velocity_z < 0x300)
            object->velocity_z += 0x20;
        if (tz < object->collision.z && object->velocity_z >= -0x2ff)
            object->velocity_z -= 0x20;
        object->yaw = angle_approach_wrapped((sint16)(((object->collision.x - tx) < 0 ? 0x28 : 0x3d8) * 4), 0x0c, (sint16)(object->yaw * 4)) / 4;
        frame = 0x1540a;
        if (object->yaw < 0x3d8)
        {
            if (object->yaw >= 9)
                frame = 0x15409;
            if (object->yaw >= 0x11)
                frame = 0x15408;
            if (object->yaw >= 0x19)
                frame = 0x15407;
            if (object->yaw >= 0x21)
                frame = 0x15406;
        }
        else
        {
            if (object->yaw < 0x3f8)
                frame = 0x1540b;
            if (object->yaw < 0x3f0)
                frame = 0x1540c;
            if (object->yaw < 0x3e8)
                frame = 0x1540d;
            if (object->yaw < 0x3e0)
                frame = 0x1540e;
        }
    }
    depth = object->animation.next_address ? 0 : 0x480 - (g_render_row_world_z - object->collision.z) / 0x100;
    if ((sint16)depth >= 0x480)
        depth = 0x47f;
    if (g_render_row_world_z < object->collision.z)
        return;
    render_world_sprite(frame, object->collision.x, object->collision.y, object->collision.z, 0, g_default_model_scale, g_default_model_scale, 0, depth, 0, &object->vram_descriptor, object->yaw);
    object_hit_flash_apply((FLASHABLE *)object);
    flare_scale = 0x1000 - object->velocity_y * 2;
    scale = flare_scale / 2;
    if (object->animation.next_address != 0 && object->animation.flags != 1)
        return;
    if ((g_frame_counter & 2) != 0)
        scale = flare_scale;
    {
        POLY_FT4 *prim = (POLY_FT4 *)(intptr)g_transient_prim_cursor;
        SetPolyFT4(prim);
        SetSemiTrans(prim, 1);
        g_next_frame_object->light_delta = (sint16)(-0x30 - (object->velocity_y >> 4));
        g_next_frame_object->force_light = 1;
        render_world_sprite(0x27400, object->collision.x - object->velocity_x * 2, object->collision.y - 0x1800, object->collision.z + 0x800, 0, scale, scale, prim, depth + 1, 0, 0, (g_frame_counter * 8) & 0x3ff);
        g_transient_prim_cursor += (sint32)sizeof(*prim);
    }
}

/* Original: FUN_800A4CD4. */
void jetpack_enemy_create(EFFECT *effect)
{
    AIRSHIP_DRONE *object = (AIRSHIP_DRONE *)runtime_heap_allocate(sizeof(*object));
    object->collision.update = (FUNC_COLLISION_UPDATE)jetpack_enemy_update;
    linked_list_append(g_object_list, object);
    object->collision.x = effect->x;
    object->collision.y = effect->y + 0x2000;
    object->collision.z = effect->z;
    object->collision.receives_mask = 0x81;
    object->collision.callback_18 = (FUNC_COLLISION_CALLBACK)jetpack_enemy_damage;
    object->health = 10;
    object->collision.frame_descriptor = &object->vram_descriptor;
    collision_box_set(object, 0x40, 0x40, 0x10);
    object->owner_effect = effect;
    effect->type = 0;
    object->route_count = (sint16)route_waypoints_collect(effect->values[0], -1, object->route);
    object->route_step = 1;
    animation_start(&object->animation, (const sint32 *)player_assets_executable_address(0x800cad84u));
    animation_set_owner(&object->animation, object);
    object->velocity_y = 0;
    object->sound_handle = -1;
}

/* Original: FUN_800A5DF4. */
static void airship_switch_activate(AIRSHIP_SWITCH *object)
{
    /* 800A5E04..800A5E10: three independent SH stores. A4 must not
     * overwrite the collision-activation flag at A6. */
    if (object->cooldown == 0)
    {
        object->cooldown = 0x3c;
        object->collision_latch = 1;
        object->input_latch = 0;
    }
}

/* Original: FUN_800A5B90. */
static void airship_switch_update(AIRSHIP_SWITCH *object)
{
    EFFECT *effect = object->effect;
    if (object->collision_latch == 0 && !world_object_is_visible(object->collision.x, object->collision.y, object->collision.z, 0x8000))
        return;
    if (object->cooldown != 0)
        object->cooldown--;
    if (!player_inside_xz_box(object->collision.x, object->collision.z, 0x4000, 0x2000) || !(g_held_buttons & 0x20) || g_player->menu_resume != 0 || object->cooldown != 0)
    {
        if (object->collision_latch == 0)
        {
            if (object->state != g_trigger_states[(uint16)effect->values[0]])
                goto toggle;
            object->input_latch = 0;
        }
        else
            goto perform;
    }
    else
    {
    toggle:
        if (object->collision_latch == 0 && object->state == g_trigger_states[(uint16)effect->values[0]])
        {
            /* 800A5C24 LH tests only the input latch; the adjacent grenade
             * timer at 1B6 is separate. 800A5CC0/CC4 clear/set via SH. */
            g_player->field_1b6 = 0;
            g_player->menu_resume = 1;
        }
    perform:
        object->collision_latch = 0;
        if (object->input_latch == 0)
        {
            sound_play_positional(0x17, 0, 0x7f, object->collision.x, object->collision.y, object->collision.z);
            object->state ^= 1;
            effect->values[1] = object->state;
            animation_start(&object->animation, (const sint32 *)player_assets_executable_address(object->state ? 0x800caee4u : 0x800caec8u));
        }
        object->input_latch = 1;
        object->cooldown = 0x3c;
    }
    animation_update(&object->animation);
    g_next_frame_object->light_delta = 0;
    if (g_stage_index != 0x0b)
        render_world_sprite(object->animation.frame, object->collision.x, object->collision.y, object->collision.z, 0, 0x1000, 0x1000, (POLY_FT4 *)object->collision.prim, 0, 0, 0, 0);
    g_trigger_states[(uint16)effect->values[0]] = (uint8)object->state;
}

/* Original: FUN_800A5A88. */
void airship_switch_create(EFFECT *effect)
{
    AIRSHIP_SWITCH *object = (AIRSHIP_SWITCH *)runtime_heap_allocate(sizeof(*object));
    const sint32 *animation;
    effect->type = 0;
    object->collision.update = (FUNC_COLLISION_UPDATE)airship_switch_update;
    linked_list_append(g_object_list, object);
    setPolyFT4(object->collision.prim);
    setShadeTex(object->collision.prim, 0);
    object->collision.x = effect->x;
    object->collision.y = effect->y;
    object->collision.z = effect->z + 0x2000;
    object->collision.object_type = 0x3e;
    object->collision.receives_mask = 1;
    object->collision.callback_18 = (FUNC_COLLISION_CALLBACK)airship_switch_activate;
    collision_box_set(object, 0x40, 0x40, 0x10);
    object->effect = effect;
    object->state = effect->values[1];
    animation = (const sint32 *)player_assets_executable_address(effect->values[1] ? 0x800caee4u : 0x800caec8u);
    g_trigger_states[(uint16)effect->values[0]] = (uint8)effect->values[1];
    animation_start(&object->animation, animation);
}

/* Exact 0x8009FEB0..0x8009FFCC: shift cell-model vertices whose Y lies in
 * the moving lift slab. */
/* Original: FUN_8009FEB0. */
void lift_deform_map_models(sint32 x, sint32 y, sint32 z, sint32 width, sint32 height, sint32 depth, sint32 delta)
{
    MAP_FLOOR_CELL *row = map_floor_cell_at(x, z);
    sint32 min_y = y < 0 ? (y + 0xff) >> 8 : y >> 8;
    sint32 r, c, n;
    MAP_MODEL_GROUP *groups = g_map_model_groups;
    for (r = 0; r < depth; r++, row += g_map_width_cells)
    {
        MAP_FLOOR_CELL *cell = row;
        for (c = 0; c < width; c++, cell++)
        {
            MAP_MODEL_GROUP *group = (MAP_MODEL_GROUP *)((uint8 *)groups + (uint32)cell->group_index * sizeof(*group));
            MAP_MODEL_INSTANCE *instance = (MAP_MODEL_INSTANCE *)(group + 1);
            n = group > groups ? group->active_count : 0;
            for (; n > 0; n--, instance++)
            {
                if (instance->y >= min_y && instance->y < min_y + height)
                    instance->y = (sint16)(instance->y + delta);
            }
        }
    }
}

/* Original: FUN_800A0128. */
static void lift_update(AIRSHIP_LIFT *lift)
{
    PLAYER *player = (PLAYER *)g_player;
    EFFECT *source = lift->waypoints[0];
    void *sound;
    sint32 shifted_x, shifted_z, target_y;
    sint16 gate;
    if (player->preserve_checkpoint != 0 && player->checkpoint == lift && player->update == player_checkpoint_recovery_update)
        return;
    shifted_z = lift->collision.z + 0x2000;
    lift->collision.x -= 0x2000;
    shifted_x = lift->collision.x;
    lift->collision.z = shifted_z;
    if (g_player_world_x + 0x1300 >= shifted_x && g_player_world_x - 0x1300 < shifted_x + (lift->cell_width << 14) && shifted_z >= g_player_world_z - 0x400 && shifted_z - (lift->cell_depth << 14) < g_player_world_z + 0x400 && g_player_world_y > lift->collision.y - 0x800 && g_player_world_y < lift->collision.y + (lift->cell_height << 8) && player->grounded != 0)
    {
        player->checkpoint = lift;
        player->preserve_checkpoint = 1;
    }
    lift->collision.x += 0x2000;
    lift->collision.z -= 0x2000;
    gate = source->values[6];
    if (gate != 0)
    {
        uint8 state = g_trigger_states[(uint16)gate];
        if (lift->collision.object_type != 0x96)
            lift->enabled = state;
        else if (lift->previous_gate_state != state)
        {
            lift->previous_gate_state = state;
            lift->enabled = 1;
        }
    }
    sound = sound_spatial_volume_calculate(0x40, lift->collision.x, lift->collision.y, lift->collision.z);
    if (lift->enabled == 0 && lift->wait_timer != 0x270f)
    {
        lift->wait_timer = 1;
        sound = 0;
    }
    if (lift->sound_disabled == 0)
    {
        if (lift->sound_handle == -1)
        {
            if (sound)
                lift->sound_handle = (sint16)sound_play_positional(0x16, 0, 0x40, g_player_world_x, g_player_world_y, g_player_world_z);
        }
        else if (!sound)
        {
            sound_voice_stop(&lift->sound_handle);
            lift->sound_handle = -1;
        }
        else
            sound_voice_spatial_volume_update(sound, lift->sound_handle);
    }
    if (lift->wait_timer == 0 && lift->enabled != 0)
    {
        lift_deform_map_models(lift->collision.x, lift->collision.y, lift->collision.z, lift->cell_width, lift->cell_height, lift->cell_depth, lift->delta_y / 0x100);
        lift->collision.y += lift->delta_y;
        target_y = lift->waypoints[lift->waypoint_index]->y + 0x1000;
        if (lift->collision.y == target_y)
        {
            lift->waypoint_index = (sint16)(lift->waypoint_index + lift->waypoint_step);
            if (lift->waypoint_index == lift->waypoint_count - 1)
                lift->waypoint_step = -1;
            if (lift->waypoint_index == 0)
                lift->waypoint_step = 1;
            target_y = lift->waypoints[lift->waypoint_index]->y;
            lift->delta_y = lift->collision.y >= target_y ? -0x200 : 0x200;
            lift->wait_timer = 0x18;
            if (lift->collision.object_type == 0x96)
                lift->delta_y *= 8;
            if (source->values[6] != 0)
            {
                if (lift->collision.object_type == 0x5a)
                {
                    lift->enabled = 0;
                    g_trigger_states[(uint16)source->values[6]] = 0;
                    lift->wait_timer = 0;
                }
                if (lift->collision.object_type == 0x96)
                    lift->enabled = 0;
            }
            if (++lift->completed_trips >= 0x80)
                lift->completed_trips = 0x7f;
            if (lift->completed_trips == 2 && lift->collision.object_type == 0x5b)
            {
                lift->wait_timer = 0x270f;
                sound_voice_stop(&lift->sound_handle);
                lift->sound_disabled = 1;
            }
        }
    }
    else if (lift->wait_timer != 0x270f)
        lift->wait_timer--;
}

/* Original: FUN_8009FFD0. */
void lift_create(EFFECT *effect)
{
    AIRSHIP_LIFT *lift = (AIRSHIP_LIFT *)runtime_heap_allocate(sizeof(*lift));
    EFFECT *scan = 0;
    sint16 route = effect->values[0], count = 1;
    lift->collision.update = (FUNC_COLLISION_UPDATE)lift_update;
    linked_list_append(g_object_list, lift);
    lift->collision.object_type = (sint16)effect->type;
    effect->type = 0;
    lift->collision.x = effect->x;
    lift->collision.y = effect->y + 0x1000;
    lift->collision.z = effect->z;
    lift->cell_width = effect->values[2];
    lift->cell_height = effect->values[3];
    lift->cell_depth = effect->values[4];
    lift->waypoints[0] = effect;
    for (;;)
    {
        scan = effect_find_next(0x1e, scan);
        if (!scan)
            break;
        if (scan->values[0] == route)
        {
            ++count;
            lift->waypoints[scan->values[1]] = scan;
        }
        ++scan;
    }
    lift->waypoint_step = 1;
    lift->sound_handle = -1;
    lift->waypoint_count = count;
    lift->enabled = 1;
    if (effect->values[6] != 0)
    {
        lift->enabled = g_trigger_states[(uint16)effect->values[6]];
        if (lift->enabled == 0)
            lift->previous_gate_state = 1;
    }
}
