#ifndef GLOBAL_H
#define GLOBAL_H

#include "app.h"
#include "collision.h"
#include "effect_update.h"
#include "level_data.h"
#include "map.h"
#include "mission.h"
#include "model.h"
#include "object.h"
#include "player.h"
#include "render.h"
#include "text_renderer.h"

/* Generated by tools/generate_global_header.py from definitions in global.c. */
extern const uint32 g_hq_material_resources[46];

/* Byte access is unaligned-safe and independent of host endianness.
 * The inline backend keeps address expressions single-evaluation. */
static inline uint32 bytes_load_le(const void *data, uint32 count)
{
    const uint8 *bytes = (const uint8 *)data;
    uint32 value = 0, i;
    for (i = 0; i < count; ++i)
        value |= (uint32)bytes[i] << (i * 8);
    return value;
}

#define read_u16_le(data) ((uint16)bytes_load_le((data), 2))
#define read_s16_le(data) ((sint16)read_u16_le(data))
#define read_u32_le(data) bytes_load_le((data), 4)

/* Shared representation helpers.  The fixed-divisor macros retain the
 * correction-before-SRA sequence used by the original MIPS routines while
 * evaluating the value expression only once. */
#define ptr_at(type, base, byte_offset) ((type *)((uint8 *)(base) + (byte_offset)))
/* Former mission.c/sprite.c helpers. Preserve sint32 argument conversions,
 * rounding toward zero, and exactly one evaluation of each input. */
#define div_trunc(value, divisor) ((sint32)(value) / (sint32)(divisor))
/* MIPS low-word multiplication; unsigned arithmetic preserves modulo 2^32. */
#define mul_lo(left, right) ((sint32)((uint32)(left) * (uint32)(right)))
#define mips_mult_lo_div(left, right, divisor) div_trunc(mul_lo((left), (right)), (divisor))
#define div_trunc_16(value) div_trunc((value), 0x10)
#define div_trunc_256(value) div_trunc((value), 0x100)
#define div_trunc_4096(value) div_trunc((value), 0x1000)
#define div_pow2_trunc(value, shift) mips_div_pow2_trunc((value), (shift))
#define div_64_trunc(value) div_pow2_trunc((value), 6)
#define div_256_trunc(value) div_pow2_trunc((value), 8)
#define div_1024_trunc(value) div_pow2_trunc((value), 10)
#define div_2048_trunc(value) div_pow2_trunc((value), 11)
#define div_4096_trunc(value) div_pow2_trunc((value), 12)
#define div_16384_trunc(value) div_pow2_trunc((value), 14)
#define read_s16_le_at(base, byte_offset) read_s16_le((const uint8 *)(base) + (byte_offset))

sint32 mips_div_pow2_trunc(sint32 value, uint32 shift);
sint32 abs_s32(sint32 value);

extern char g_fmvSeen;
extern sint32 g_iterations;
extern OriginalModelDescriptor *g_model_descriptors;
extern sint32 g_skipPcinit;
extern sint32 g_titleStrToggle;
extern sint32 g_video_mode;
extern sint32 g_language_id;
extern sint32 g_play_fmv;
extern sint32 g_default_model_scale;
extern sint16 g_recent_speech_samples[4];
extern uint8 g_weapon_cheat_enabled;
extern uint8 g_invulnerability_cheat_enabled;
extern sint16 g_previous_destruction_sound_variant;
extern uint16 g_hq_scroll_frame_divider;
extern sint16 g_hq_map_region;
extern void *g_v2_rocket_initial_pose;
extern MISSION_TIMER_DISPLAY *g_mission_timer_display;
extern void *g_stage_archive;
extern void *g_runtime_scratch_buffer_a;
extern void *g_menu_text_pointer_table;
extern void *g_gunship_initial_pose;
extern uint32 g_previous_held_buttons;
extern void *g_model_render_frame;
extern void *g_input_record_cursor;
extern uint8 g_terrain_variation_limit;
extern FrameObjectPartial *g_next_frame_object;
extern void *g_mini_gyro_initial_pose;
extern sint16 g_mini_gyro_model_base;
extern void *g_mini_gyro_type_117_initial_pose;
extern sint16 g_mini_gyro_type_117_model_base;
extern void *g_overlay_initial_pose_slot_4004;
extern sint16 g_overlay_model_base_slot_4000;
extern char g_pause_button_latched;
extern STAGE_ENV *g_stage_env;
extern sint32 g_material_resource_table[304];
extern RENDER_FRAME *g_current_render_frame;
extern void *g_scuba_tug_initial_pose;
extern void *g_tank_initial_pose;
extern sint16 g_scuba_drifting_hazard_model_id;
extern void *DAT_800d3f84;
extern void *g_player_fire_script;
extern uint8 *g_gpu_packet_cursor;
extern COLLISION_RESULT *g_current_collision_result;
extern uint32 *g_prim_link_cursor;
extern void *g_auxiliary_object_list[2];
extern void *g_overlay_initial_pose_slot_40f0;
extern uint32 g_frame_counter;
extern void *g_input_record_buffer;
extern uint32 g_current_sprite_upload_resource;
extern void *g_tanya_initial_pose;
extern void *g_runtime_scratch_buffer_b;
extern void *g_ledge_trigger_list[2];
extern void *g_loading_image_buffer;
extern sint16 g_projectile_effect_cooldown;
extern sint16 g_red_signal_flare_clut;
extern sint16 g_white_signal_flare_clut;
extern sint16 g_truck_model_base;
extern sint16 g_gyro_model_base;
extern sint32 g_continuous_weapon_effect_rotation;
extern MAP_FLOOR_CELL *g_map_floor_cells;
extern MAP_MODEL_GROUP *g_map_model_groups;
extern EFFECT_DATA *g_effect_data;
extern void *g_map_model_attributes;
extern POLY_FT4 g_player_prone_weapon_effect_prim;
extern POLY_FT4 g_player_weapon_effect_prim;
extern POLY_FT4 g_continuous_weapon_effect_prim;
extern COLLISION_RESULT g_dynamic_collision_result;
extern COLLISION_RESULT g_static_collision_result;
extern sint32 g_dynamic_collision_cells[32];
extern sint32 g_static_collision_cells[32];
extern uint8 g_level_select_cheat_enabled;
extern uint16 g_render_frame_index;
extern char g_input_playback_label[64];
extern sint32 g_vsync_count_this_frame;
extern uint8 g_hq_weapon_area_enabled;
extern uint8 g_controller_packet[2];
extern sint32 g_vsync_count_total;
extern uint8 g_primary_objective_states[257];
extern uint8 g_secondary_objective_states[257];
extern uint8 g_action_trigger_states[32];
extern uint8 g_mission_message_slots[16];
extern uint8 g_objective_counts[256];
/* Original byte aliases inside DAT_800E7F40, not independent storage.
 * MIPS level load clears all of them at 800AB268..800AB278. */
#define g_destroyed_reward_object_count g_objective_counts[0x0e]  /* DAT_800E7F4E */
#define g_remaining_flame_target_count g_objective_counts[0x12]   /* DAT_800E7F52 */
#define g_destroyed_special_target_count g_objective_counts[0x14] /* DAT_800E7F54 */
#define g_airship_destruction_complete g_objective_counts[0x15]   /* DAT_800E7F55 */
#define g_mechanoid_destruction_complete g_objective_counts[0x16] /* DAT_800E7F56 */
extern uint8 g_trigger_states[128];
extern SpatialBucket *g_spatial_buckets;
extern uint8 *g_spatial_cell_bucket_indices;
extern uint8 *g_dynamic_collision_cell_anchors;
extern uint8 *g_map_cell_light_values;
extern PLAYER *g_player;
extern FrameObjectPartial g_frame_objects[FRAME_OBJECT_LIMIT];
extern FrameObjectPartial **g_frame_object_lookup;
extern sint32 g_map_width_cells;
extern EFFECT *g_effects;
extern EFFECT_HANDLER_ENTRY g_effect_handlers[256];
extern uint32 g_prim_link_workspace[0x2000];
extern RENDER_FRAME g_render_frame_buffer_0;
extern uint8 g_boss_health_bar[0x64];
extern uint16 g_resource_clut_table[256];
extern sint32 g_font_glyph_height;
extern FONT *g_font;
extern sint16 g_font_line_height, g_font_clut, g_font_glyph_columns;
extern sint16 g_text_color_index;
extern sint32 g_text_pen_y;
extern POLY_FT4 g_shared_quad_prim;
extern POLY_FT3 g_shared_triangle_prim;
extern uint8 g_player_health_bar[128];
extern uint16 g_sprite_vram_regions_game[];
extern uint16 g_sprite_vram_regions_hq[];
extern uint8 g_muzzle_flash_light_stamp[26];
extern void *DAT_800c8ac4;
extern const char g_loading_caption_spanish[];
extern __declspec(dllexport) sint16 g_hq_session_timer;
extern __declspec(dllexport) CD_CALLBACK g_cd_ready_callback;
extern __declspec(dllexport) CD_CALLBACK g_cd_sync_callback;
extern __declspec(dllexport) CD_CALLBACK g_cd_data_callback;
extern __declspec(dllexport) uint8 g_cd_track_table[4];
extern __declspec(dllexport) uint8 g_memory_card_entry_map[256];
extern __declspec(dllexport) uint8 DAT_80000000;
extern sint32 g_debug_cheats_enabled;
extern sint32 g_debug_coordinates_visible;
extern sint32 g_vram_error_reporting_enabled;
extern sint32 g_screenshot_index;
extern sint32 g_cd_file_io_enabled;
extern sint32 g_pause_active;
extern sint32 g_stage_index;
extern sint32 g_next_stage_index;
extern sint32 g_hq_attract_timeout;
extern sint16 g_player_input_disabled;
extern sint16 g_target_indicator_enabled;
extern sint16 g_stage_background_resource;
extern sint16 g_foreground_sprite_clut_offset;
extern sint16 DAT_800d3ccc;
extern sint16 g_attract_demo_index;
extern sint16 g_attract_demo_variant;
extern sint16 g_attract_mode;
extern sint16 g_next_attract_mode;
extern sint32 g_player_world_x;
extern sint32 g_player_world_y;
extern sint32 g_menu_selection_index;
extern sint32 g_sfx_playback_volume;
extern sint32 g_sfx_volume_setting;
extern sint32 g_music_volume_setting;
extern sint32 g_current_music_track;
extern sint32 g_cd_audio_track_offset;
extern sint32 g_player_world_z;
extern sint32 g_muzzle_light_pending;
extern sint16 g_model_clut_override;
extern sint32 g_muzzle_light_x_direction;
extern sint32 g_muzzle_light_z_direction;
extern sint32 g_saved_player_world_x;
extern sint32 g_saved_player_world_y;
extern sint32 g_saved_player_world_z;
extern sint32 g_sound_handles_invalidated;
extern sint16 DAT_800d3d70;
extern sint16 DAT_800d3d72;
extern sint16 g_recent_speech_write_index;
extern sint16 g_ambient_speech_timer;
extern __declspec(dllexport) sint16 g_loading_image_index;
extern sint32 g_camera_depth_offset_target;
extern sint32 g_scuba_stage_active;
extern sint32 g_cd_sectors_read;
extern sint32 g_cd_read_command_count;
extern sint32 g_memory_card_warning_checked;
extern sint32 g_stage_background_y;
extern sint16 g_hq_selected_map_node;
extern sint32 g_mips_frame_stack_pointer;
extern sint32 g_camera_manual_y_offset;
extern sint32 g_render_row_left_world_x;
extern sint16 g_v2_rocket_model_base;
extern sint32 g_same_stage_selected;
extern sint32 g_screen_height;
extern sint16 g_display_shake_ticks;
extern sint16 g_clut_upload_x;
extern sint16 g_clut_upload_y;
extern sint32 g_primary_target_current_count;
extern sint32 g_previous_player_world_x;
extern sint32 g_previous_player_world_y;
extern sint32 g_previous_player_world_z;
extern sint32 g_camera_world_x;
extern sint32 g_camera_world_y;
extern sint32 g_camera_world_z;
extern sint16 g_gunship_model_base;
extern sint32 g_background_brightness_bias;
extern sint32 g_scene_brightness_bias;
extern sint16 g_object_type_0x39_model_id;
extern sint32 g_secondary_target_current_count;
extern sint32 g_current_model_world_x;
extern sint32 g_current_model_world_y;
extern sint32 g_current_model_world_z;
extern sint16 g_target_indicator_model_id;
extern sint32 g_current_model_shade;
extern sint32 g_effect_wind_x;
extern sint32 g_current_model_rotation_x;
extern sint32 g_current_model_rotation_z;
extern sint32 g_room_activation_pending;
extern sint32 g_camera_render_x;
extern sint32 g_camera_render_y;
extern sint32 g_camera_render_z;
extern sint32 g_shared_scratch_value;
extern sint32 g_mission_enemy_update_count;
extern sint32 g_input_recording_mode;
extern sint32 g_primary_action_objective_present;
extern __declspec(dllexport) sint32 g_cd_track_table_status;
extern sint32 g_stage_background_disabled;
extern sint32 g_input_run_length;
extern sint32 g_map_depth_cells;
extern sint32 g_screen_half_width;
extern sint32 g_cd_sync_state;
extern sint32 g_hq_world_map_active;
extern sint32 g_mission_timer_visible;
extern sint32 g_selected_weapon_slot;
extern sint32 g_effect_visibility_depth_cells;
extern sint32 g_pressed_buttons;
extern sint32 g_archive_member_size;
extern sint16 g_display_screen_y;
extern sint16 g_model_packet_count;
extern sint32 g_vertical_cull_extent;
extern sint32 g_transient_prim_cursor;
extern sint16 g_player_sprite_clut;
extern sint32 g_collision_surface_resource;
extern sint32 g_primary_objective_count;
extern __declspec(dllexport) void *g_shared_result_pointer;
extern __declspec(dllexport) volatile uint32 g_psx_flush_cache_boundary_calls;
extern __declspec(dllexport) sint32 g_language_assets_preloaded;
extern __declspec(dllexport) void *g_sound_archive;
extern sint16 g_scuba_tug_model_base;
extern sint16 g_tank_model_base;
extern sint32 g_collision_flags;
extern sint32 g_dynamic_collision_hit;
extern sint32 g_current_model_id;
extern sint32 DAT_800d4018;
extern sint16 g_robot_press_model_id;
extern sint32 g_font_glyph_width;
extern __declspec(dllexport) uint32 g_held_buttons;
extern sint16 g_model_count;
extern sint32 g_render_depth_bucket;
extern sint32 g_depth_lighting_bias;
extern sint32 g_sprite_texture_cache_key;
extern sint32 g_render_row_back_projection_scale;
extern sint32 g_player_far_z_limit;
extern sint32 g_action_transition_direction;
extern sint16 g_surface_impact_cooldown;
extern sint32 g_render_row_world_z;
extern sint32 g_mission_script;
extern sint32 g_mission_ending;
extern sint16 g_radar_vehicle_model_base;
extern sint32 g_sprite_subdivision_cooldown;
extern sint16 g_bio_goo_model_id;
extern sint32 g_room_player_near_z;
extern sint32 g_room_player_far_z;
extern sint32 g_previous_camera_world_x;
extern sint32 g_previous_camera_world_y;
extern sint32 g_previous_camera_world_z;
extern sint32 g_scene_far_z;
extern sint32 g_current_model_translation_x;
extern sint32 g_current_model_translation_z;
extern sint32 g_secondary_objective_count;
extern sint32 g_primary_target_total_count;
extern sint32 g_camera_limit_left;
extern sint32 g_camera_limit_top;
extern sint32 g_camera_limit_near;
extern sint32 g_camera_limit_right;
extern sint32 g_model_vertical_cull_override;
extern sint32 g_camera_limit_bottom;
extern sint32 g_camera_limit_far;
extern sint32 g_initial_stack_pointer;
extern sint32 g_camera_target_y;
extern sint32 g_camera_depth_offset;
extern sint32 g_input_run_value;
extern sint16 g_stage_model_count;
extern __declspec(dllexport) OBJECT *g_object_list[2];
extern sint32 g_transient_prim_buffer;
extern sint32 g_secondary_target_total_count;
extern sint32 g_required_mission_item_count;
extern sint16 g_hit_flash_clut;
extern sint16 g_mechanoid_model_base;
extern sint16 g_radar_target_model_id;
extern sint16 g_tanya_model_base;
extern sint32 g_screen_width;
extern sint32 g_player_near_z_limit;
extern sint32 g_render_row_front_projection_scale;
extern sint32 g_current_model_rotation_y;
extern sint32 g_camera_horizontal_bias;
extern sint32 g_effect_count;
extern sint32 g_map_model_record_count;
extern sint32 g_map_depth_subcells;
extern sint32 g_map_width_subcells;
extern sint32 g_map_world_depth;
extern sint32 g_player_displacement_x;
extern sint32 g_player_displacement_z;
extern sint32 g_player_displacement_y;
extern __declspec(dllexport) RENDER_FRAME g_render_frame_buffer_1;

/* Original: DAT_800D75D8. Embedded CLUT entries, not independent storage:
 * DAT_800D760E, DAT_800D7696, DAT_800D771A, DAT_800D772E,
 * DAT_800D7742, DAT_800D7756. Resource IDs index the table by / 0x400. */
#define g_language_flag_clut (g_resource_clut_table[0x1b])       /* 0x06C00 */
#define g_tanya_sprite_clut (g_resource_clut_table[0x5f])        /* 0x17C00 */
#define g_signal_flare_sprite_clut (g_resource_clut_table[0xa1]) /* 0x28400 */
#define g_resource_0x2ac00_clut (g_resource_clut_table[0xab])    /* 0x2AC00 */
#define g_scuba_diver_sprite_clut (g_resource_clut_table[0xb5])  /* 0x2D400 */
#define g_font_uploaded_clut (g_resource_clut_table[0xbf])       /* 0x2FC00 */

/* Original frame storage: DAT_800EDCB8, DAT_800F4520.
 * Embedded fields: DAT_800EEEBC, DAT_800EEEBE, DAT_800EEED2, DAT_800EEF22,
 * DAT_800F5724, DAT_800F5726, DAT_800F573A. */
#define g_render_frame_0_draw_clip_x (g_render_frame_buffer_0.drawenv.clip.x)
#define g_render_frame_0_draw_clip_y (g_render_frame_buffer_0.drawenv.clip.y)
#define g_render_frame_0_dither_enabled (g_render_frame_buffer_0.drawenv.dtd)
#define g_render_frame_0_screen_y (g_render_frame_buffer_0.display_env.screen.y)
#define g_render_frame_1_draw_clip_x (g_render_frame_buffer_1.drawenv.clip.x)
#define g_render_frame_1_draw_clip_y (g_render_frame_buffer_1.drawenv.clip.y)
#define g_render_frame_1_dither_enabled (g_render_frame_buffer_1.drawenv.dtd)

#endif
