#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "animation.h"
#include "app.h"
#include "audio/game_sound.h"
#include "cd.h"
#include "code_module.h"
#include "collision.h"
#include "effect_update.h"
#include "global.h"
#include "hq.h"
#include "level_data.h"
#include "map.h"
#include "memory_card_platform.h"
#include "object.h"
#include "original_file.h"
#include "platform/win/game_platform.h"
#include "platform/win/input.h"
#include "player.h"
#include "psx.h"
#include "random.h"
#include "render.h"
#include "resource_table.h"
#include "runtime_heap.h"
#include "spatial.h"
#include "sprite.h"
#include "sprite_renderer.h"
#include "stubs.h"
#include "text_renderer.h"

/* Types. */
/* Semantic module generated by tools/merge_semantic_modules.py.
 * Original MIPS address comments remain attached to each function. */
/* HQ object type 0x3C callback at HQ.BIN address 0x800FC584. */

typedef struct HqSlidingHudPartial
{
    uint8 unknown_00[0x20];
    sint32 x;
    uint8 unknown_24[0x58];
    sint32 closing;
} HqSlidingHudPartial;

typedef struct
{
    uint8 field_00[0x1C];
    sint16 object_type; /* +0x1C */
    uint8 field_1e[6];
    sint32 y; /* +0x24 */
    uint8 field_28[0x54];
    sint16 text_width; /* +0x7C */
    uint16 field_7e;
    const char *archive; /* +0x80 */
} HQ_LOADING;

#if defined(AP_32BIT)
typedef char HqLoadingObject_size_84[sizeof(HQ_LOADING) == 0x84 ? 1 : -1];
typedef char HqLoadingObject_archive_at_80[offsetof(HQ_LOADING, archive) == 0x80 ? 1 : -1];
#endif

/* HQ.BIN immutable resource tables, consumed only by 800FDAD0:
 * text offsets 800FE3DC..800FE3F8 (relative to 800FE3DC), prompt PSX
 * pointers 800FE96C..800FE988. The seven type-8D EFFECTS records carry
 * LH +12 indices 1..7. Preserve PSX pointer values until resolution.
 * Text payloads occupy 800FE3FC..800FE969; names are in 800FADF8..800FAE3D.
 * 800FDAEC/FDAF8, 800FDB00/FDB04, 800FDB44/FDB48 prove the indexing.
 * See status/hq-portraits-disasm and tools/audit_hq_portraits.py. */
typedef struct HqPortraitText
{
    uint32 text_offset;
    uint32 prompt_address;
} HqPortraitText;

typedef struct
{
    COLLISION collision;     /* +0x00 */
    uint32 field_78;         /* +0x78 */
    uint32 previous_buttons; /* +0x7C */
    sint16 selected_track;   /* +0x80 */
    uint16 field_82;         /* +0x82 */
} HQ_MUSIC_SELECTOR;

#if defined(AP_32BIT)
typedef char HqMusicSelector_size_84[sizeof(HQ_MUSIC_SELECTOR) == 0x84 ? 1 : -1];
typedef char HqMusicSelector_buttons_at_7c[offsetof(HQ_MUSIC_SELECTOR, previous_buttons) == 0x7C ? 1 : -1];
typedef char HqMusicSelector_track_at_80[offsetof(HQ_MUSIC_SELECTOR, selected_track) == 0x80 ? 1 : -1];
#endif

/* Evidence-backed HQ global-map selector, original 0x800FB700..0x800FC348. */

struct HQ_MAP_NODE
{
    uint16 flags;
    uint8 pad_02;
    uint8 region;
    sint16 x, y;
    sint16 neighbour[4];
    uint8 index;
    uint8 unlocked;
    uint8 pad_12;
    uint8 pad_13;
};

typedef char HqMapNode_size_14[sizeof(HQ_MAP_NODE) == 0x14 ? 1 : -1];

/* Macros. */
#pragma optimize("", off)

#pragma optimize("", on)

#pragma optimize("", off)

#pragma optimize("", on)

#pragma optimize("", off)

#pragma optimize("", on)

#pragma optimize("", off)

#pragma optimize("", on)

#pragma optimize("", off)

#pragma optimize("", on)

/* Variables. */
static sint16 hq_texture_cache;

/* HQ.BIN 0x800FE994 */
static sint32 hq_interaction_countdown;

/* HQ.BIN 0x800FE990 */
static sint16 hq_prompt_latched;

static const char hq_loading_paths[4][12] = {"HQ\\EGT.BIN", "HQ\\FGT.BIN", "HQ\\GGT.BIN", "HQ\\SGT.BIN"};

static const HqPortraitText hq_portrait_texts[7] = {{0x020, 0x800fae34u}, {0x05a, 0x800fae2cu}, {0x0b1, 0x800fae24u}, {0x0db, 0x800fae1cu}, {0x104, 0x800fae10u}, {0x12b, 0x800fae08u}, {0x14d, 0x800fadf8u}};

/* HQ.BIN module-local storage at 0x800FE98C..0x800FEAA8. These are native
 * relocations of the original fixed addresses, not main-executable globals. */
static sint32 hq_pending_transition;

/* 0x800FEA98 */
static EFFECT *hq_effect_3b;

/* 0x800FEAA0 */
static EFFECT *hq_effect_3d;

/* 0x800FEAA8 */
static EFFECT *hq_effect_3f;

static uint8 drawn_nodes[0x80];

/* HQ.BIN data consumed by this state machine (0x800FADD4, 0x800FADDC and
 * 0x800FADE4..0x800FAE70), retained byte-for-byte instead of host pointers. */
static const char hq_save_header[7] = {'A', 'G', 'E', 'N', 'T', ' ', 0};

static const char hq_slot_text[] = "SLOT";

static const uint8 hq_card_layout[140] = {0x42, 0x45, 0x53, 0x4c, 0x45, 0x53, 0x2d, 0x30, 0x30, 0x34, 0x37, 0x34, 0x53, 0x4c, 0x4f, 0x54, 0, 0, 0, 0, 0x56, 0x49, 0x52, 0x47, 0x49, 0x4e, 0x20, 0x53, 0x54, 0x41, 0x46, 0x46, 0, 0, 0, 0, 0x4d, 0x41, 0x52, 0x43, 0x55, 0x53, 0, 0, 0x53, 0x54, 0x45, 0x50, 0x48, 0x41, 0x4e, 0x45, 0, 0, 0, 0, 0x50, 0x41, 0x55, 0x4c, 0, 0, 0, 0, 0x4d, 0x41, 0x52, 0x4b, 0, 0, 0, 0, 0x4a, 0x4f, 0x59, 0x4c, 0x59, 0x4f, 0x4e, 0, 0x52, 0x41, 0x46, 0x46, 0x41, 0x45, 0x4c, 0x45, 0, 0, 0, 0, 0x48, 0x51, 0x5c, 0x45, 0x47, 0x54, 0x2e, 0x42, 0x49, 0x4e, 0, 0, 0x48, 0x51, 0x5c, 0x46, 0x47, 0x54, 0x2e, 0x42, 0x49, 0x4e, 0, 0, 0x48, 0x51, 0x5c, 0x47, 0x47, 0x54, 0x2e, 0x42, 0x49, 0x4e, 0, 0, 0x48, 0x51, 0x5c, 0x53, 0x47, 0x54, 0x2e, 0x42, 0x49, 0x4e, 0, 0x3e};

/* Functions. */
/* Original: FUN_800FD95C. */
GDB_CALL void hq_ambient_object_update(void *raw_object)
{
    HQ_OBJECT *object = (HQ_OBJECT *)raw_object;
    sint32 floor_y;

    ++object->age;
    if (object->age < 20)
    {
        object->collision.y -= 0x400;
        floor_y = object->marker->y + 0x2000;
        if (object->collision.y < floor_y)
            object->collision.y = floor_y;
    }
    if (object->age >= 101)
        object->collision.y += 0x400;
    if (object->age == 130)
    {
        object_destroy(object);
        object->marker->values[0] = 0;
    }

    /* Original clears visibility flag +0x26 on the current frame object. */
    g_next_frame_object->light_delta = 0;

    render_world_sprite(object->render_resource, object->collision.x, object->collision.y, object->collision.z, 0, 0x1000, 0x1000, 0, 0, 2, 0, 0);
}

/* Original: FUN_800FDA70. */
GDB_CALL void hq_ambient_object_collect(void *raw_object, void *collision_source)
{
    HQ_OBJECT *object = (HQ_OBJECT *)raw_object;
    SPRITE *reward = (SPRITE *)destroyable_object_damage_and_reward(raw_object, collision_source);

    if (reward != 0)
    {
        animation_update(&reward->animation);
        reward->animation.delay = 9999;
        reward->animation.frame = object->render_resource;
        object->marker->values[0] = 0;
    }
}

/* Original: FUN_800FC584. */
GDB_CALL void hq_sliding_hud_update(void *raw_object)
{
    HqSlidingHudPartial *object = (HqSlidingHudPartial *)raw_object;
    sint32 mirrored_x;

    if (!object->closing)
    {
        if (object->x != 0)
            object->x += 8;
        else if (g_held_buttons != 0)
            object->closing = 1;
    }
    if (object->closing)
    {
        object->x -= 8;
        if (object->x == -0x120)
        {
            object_destroy(object);
        }
    }

    render_screen_sprite((sint16)object->x, 0x20, 0x25c00, 0);
    mirrored_x = object->x < 0 ? -object->x : object->x;
    render_screen_sprite((sint16)mirrored_x, 0x20, 0x25c01, 0);
}

/* Original: FUN_800FDC8C. */
GDB_CALL void hq_memory_card_warning_show(void)
{
    uint8 *workspace;
    uint8 *bank;
    const char *message = 0;
    sint32 prompt = 0;
    g_memory_card_warning_checked = 1;
    workspace = (uint8 *)runtime_heap_allocate(0xd34);
    DAT_80000000 = 0;
    memory_card_system_initialize();
    bank = workspace + 0x7c;
    memory_card_context_select_slot(bank, 0);
    memory_card_directory_scan(bank);
    *(uint8 **)(workspace + 0xcc4) = bank;
    if (workspace[0x695] == 0)
    {
        message = (const char *)player_assets_executable_pointer(0x800827B8u);
        prompt = 1;
    }
    else if (workspace[0x69e] != 0 && memory_card_usable_entry_count(bank) == 0)
    {
        message = (const char *)player_assets_executable_pointer(0x800827B4u);
        prompt = 1;
    }
    if (prompt != 0)
    {
        gpu_draw_sync(0);
        display_buffers_initialize();
        g_render_frame_index ^= 1;
        g_current_render_frame = g_render_frame_index ? &g_render_frame_buffer_0 : &g_render_frame_buffer_1;
        g_current_render_frame->drawenv.isbg = 1;
        drawenv_apply(&g_current_render_frame->drawenv);
        g_current_render_frame->drawenv.isbg = 0;
        text_render(message, 0, -0x40);
        screen_overlay_draw();
        ot_submit(&g_current_render_frame->ot[1]);
        gpu_draw_sync(0);
        do
        {
            vertical_sync_wait(0);
            g_held_buttons = controllers_read(0);
        } while (g_held_buttons == 0);
        g_player->menu_resume = 1;
    }
    memory_card_system_shutdown();
}

/* Original: FUN_800ABEA0. */
GDB_CALL sint16 hq_scrolling_text_render(const char *text, sint16 x, sint16 extent, const char *caption, sint32 automatic)
{
    sint32 width;
    if (!automatic)
    {
        if (g_held_buttons & 0x1000)
            x += 2;
        if (g_held_buttons & 0x4000)
            x -= 2;
    }
    else if (++g_hq_scroll_frame_divider > 2)
    {
        --x;
        g_hq_scroll_frame_divider = 0;
    }
    if (!automatic && x > -0x50)
        x = -0x50;
    if (x < -extent)
        x = (sint16)-extent;
    width = text_byte_length(caption);
    if (g_frame_counter & 0x10)
        text_render(caption, (-width * g_font_glyph_width) / 2, g_screen_height / 2 - 0x18);
    psx_add_draw_area_rect(g_current_render_frame->ot + 1, 0, g_screen_width, 0, g_screen_height);
    g_gpu_packet_cursor += 0x40;
    text_render(text, -0x82, x);
    g_scene_brightness_bias = -0x78;
    psx_add_draw_area_rect(g_current_render_frame->ot + 1, 0, g_screen_width, 0, g_screen_height - 0x20);
    g_gpu_packet_cursor += 0x40;
    return x;
}

/* Original: FUN_800FDBF4. */
GDB_CALL void hq_scrolling_text_update(HQ_LOADING *object)
{
    sint16 y;
    g_player->field_22c = 0;
    g_hq_session_timer = 0;
    y = hq_scrolling_text_render(object->archive, (sint16)object->y, object->text_width, (const char *)player_assets_executable_pointer(0x8008275Cu), 1);
    object->y = y;
    if ((g_pressed_buttons & 0x10) != 0)
    {
        g_player->field_22c = -1;
        g_player->menu_resume = 1;
        object_destroy(object);
    }
}

/* Original: FUN_8008EDA4. */
GDB_CALL sint16 text_line_break_count(const char *text)
{
    sint16 lines = 0;
    for (;;)
    {
        uint8 code = (uint8)*text;
        if (code == 0x0c)
        {
            text += 2;
            continue;
        }
        if (code == 0)
            return lines;
        ++text;
        if (code == 0x0a)
            ++lines;
    }
}

/* Original: FUN_800FDB78. */
GDB_CALL void hq_scrolling_text_open(void *archive)
{
    HQ_LOADING *object = (HQ_LOADING *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)hq_scrolling_text_update);
    object->archive = (const char *)archive;
    object->object_type = 0x8d;
    object->y = g_screen_height / 2;
    object->text_width = (sint16)((uint16)g_font_line_height * (uint16)text_line_break_count((const char *)archive));
}

/* Original: FUN_800FDE34. */
GDB_CALL void hq_loading_screen_run(void)
{
    char path[12];
    sint32 size;
    void *archive;
    sint32 path_index = 0;
    display_buffers_initialize();
    runtime_heap_initialize();
    linked_list_initialize(g_object_list);
    if (g_language_id == 2)
        path_index = 1;
    if (g_language_id == 3)
        path_index = 2;
    if (g_language_id == 4)
        path_index = 3;
    memcpy(path, hq_loading_paths[path_index], 11);
    size = game_file_size(path);
    archive = runtime_heap_allocate_sector_aligned(size);
    game_file_read(path, archive);
    music_track_select(0x0c, 1);
    hq_scrolling_text_open(archive);
    do
    {
        vertical_sync_wait(0);
        frame_begin();
        object_list_update();
        screen_overlay_draw();
        end_frame_submit(0);
    } while ((g_pressed_buttons & 0x10) == 0);
    runtime_heap_defer_free(archive);
    runtime_heap_sweep();
    gpu_draw_sync(0);
}

/* Original: FUN_800FD59C. */
sint32 hq_interaction_prompt_update(const char *prompt, sint16 blocking_object_type)
{
    PLAYER *player = g_player;
    sint32 width;

    hq_prompt_latched = 1;
    if (hq_interaction_countdown != 0)
    {
        --hq_interaction_countdown;
        if (hq_interaction_countdown == 0)
            return 1;
    }

    player->field_22c &= ~0x40u;
    if (object_find_next_by_type(0, blocking_object_type) != 0)
        return 0;
    if ((g_pressed_buttons & 0x40) != 0)
    {
        hq_interaction_countdown = 2;
        return 0;
    }
    if ((g_held_buttons & 0x40) != 0)
        return 0;

    if ((g_frame_counter & 8) == 0)
        text_render((const char *)player_assets_executable_pointer(0x80082764u), -0x60, 0x40);
    width = text_byte_length(prompt) * g_font_glyph_width;
    text_render(prompt, -(width / 2), 0x50);
    return 0;
}

/* Exact HQ.BIN 800FDAD0..800FDB78: persistent type-8D portrait trigger.
 * Unlike constructors, it must not clear the source effect type. */
/* Original: FUN_800FDAD0. */
GDB_CALL void hq_portrait_trigger_update(EFFECT *effect)
{
    const HqPortraitText *entry = &hq_portrait_texts[(sint16)effect->values[0] - 1];
    const char *text = (const char *)win_code_module_address(0x800fe3dcu + entry->text_offset);
    if (effect->x - 0x2000 < g_player_world_x && g_player_world_x < effect->x + 0x2000 && effect->z < g_player_world_z)
    {
        const char *prompt = (const char *)win_code_module_address(entry->prompt_address);
        if (hq_interaction_prompt_update(prompt, 0x8d))
            hq_scrolling_text_open((void *)text);
    }
}

/* 0x800FE988 */

GDB_CALL void hq_reset_session_timer(void)
{
    g_hq_session_timer = 0;
}

EFFECT *hq_effect_3b_get(void)
{
    return (EFFECT *)hq_effect_3b;
}

void hq_set_pending_transition(void)
{
    hq_pending_transition = 1;
    if (getenv("OA_MISSION_LAUNCH_TRACE") != 0)
    {
        FILE *trace = fopen("mission_launch_port.log", "a");
        if (trace != 0)
        {
            fprintf(trace, "MISSION_ACCEPT selected=%d pending=%d\n", g_next_stage_index, hq_pending_transition);
            fclose(trace);
        }
    }
}

static void preserve_player_position(void)
{
    g_saved_player_world_x = g_player_world_x;
    g_saved_player_world_y = g_player_world_y;
    g_saved_player_world_z = g_player_world_z;
}

/* Original: FUN_800FD6DC. */
void hq_background_texture_select(sint32 requested_index)
{
    sint16 previous_index = g_hq_map_region;
    sint32 explicit_index = (sint16)requested_index;
    uint32 resource_offset;
    uint32 resource;
    uint8 *frame;
    sint16 saved_width;
    sint16 saved_height;

    if (previous_index == hq_texture_cache && explicit_index == -1)
        return;
    if (explicit_index != -1)
        g_hq_map_region = (sint16)explicit_index;

    resource_offset = (uint32)(sint32)g_hq_map_region << 10;
    if (resource_offset >= 0x1401u)
        resource_offset = 0x1400u;
    resource = 0x24400u + resource_offset;

    saved_width = g_clut_upload_x;
    saved_height = g_clut_upload_y;
    g_clut_upload_x = 0x140;
    /* 0x800D772E aliases DAT_800D75D8[0xAB], the CLUT saved for
     * resource group 0x2AC00.  It is not an independent global. */
    g_clut_upload_y = (sint16)(g_resource_clut_table[0x2ac00 >> 10] >> 6);
    sprite_clut_upload(resource, 0, 0, 0);
    g_clut_upload_x = saved_width;
    g_clut_upload_y = saved_height;

    frame = animation_frame_resource(resource);
    /* 0x800E53B4 is descriptor_bases[0x2AC00 >> 10] in the original
     * 0x800E5108 table, not independent storage. */
    sprite_upload_pixels(sprite_vram_descriptor_for_resource(0x2ac00), frame + 4, 1);

    if (explicit_index == -1)
        hq_texture_cache = g_hq_map_region;
    else
    {
        g_hq_map_region = previous_index;
        hq_texture_cache = -1;
    }
}

static const void *exec_ptr(uint32 table, sint32 index)
{
    const uint8 *slot = (const uint8 *)player_assets_executable_address(table + (uint32)index * 4u);
    uint32 address;
    address = (uint32)slot[0] | (uint32)slot[1] << 8 | (uint32)slot[2] << 16 | (uint32)slot[3] << 24;
    return player_assets_resolve_address(address);
}

/* Original: FUN_8009C714. */
void hq_world_map_camera_update(sint32 x, sint32 y, sint32 z)
{
    if (g_camera_world_x < x)
        g_camera_world_x += 0x200;
    if (x < g_camera_world_x)
        g_camera_world_x -= 0x200;
    if (g_camera_world_y < y)
    {
        g_camera_world_y += 0x200;
        g_camera_target_y += 0x200;
    }
    if (y < g_camera_world_y)
    {
        g_camera_world_y -= 0x200;
        g_camera_target_y -= 0x200;
    }
    if (g_camera_world_z < z)
        g_camera_world_z += 0x200;
    if (z < g_camera_world_z)
        g_camera_world_z -= 0x200;
    g_camera_render_x = g_camera_world_x < 0 ? (g_camera_world_x + 0xff) >> 8 : g_camera_world_x >> 8;
    g_camera_render_y = g_camera_world_y < 0 ? (g_camera_world_y + 0xff) >> 8 : g_camera_world_y >> 8;
    g_camera_render_z = g_camera_world_z < 0 ? (g_camera_world_z + 0xff) >> 8 : g_camera_world_z >> 8;
    g_previous_player_world_x = g_player_world_x;
    g_previous_player_world_y = g_player_world_y;
    g_previous_player_world_z = g_player_world_z;
}

/* Original: FUN_80087C68. */
GDB_CALL HQ_MAP_NODE *hq_world_map_node_find_by_id(sint16 id)
{
    HQ_MAP_NODE *node = (HQ_MAP_NODE *)player_assets_executable_address(0x800c28e4u);
    for (;;)
    {
        if (node->flags == 0xffff)
            fatal_error_with_value("NO CONNECTION", id);
        if (node->flags == (uint16)id)
            return node;
        ++node;
    }
}

/* 0x8009EE30.  This is the integer DDA used by the original route renderer;
 * all values in line[] have eight fractional bits and the return value is
 * the number of one-world-unit steps along the dominant axis. */
/* Original: FUN_8009EE30. */
sint32 fixed_dda_initialize(sint32 x0, sint32 y0, sint32 z0, sint32 x1, sint32 y1, sint32 z1, sint32 *line)
{
    sint32 dx = (x1 - x0) * 0x100, dy = (y1 - y0) * 0x100, dz = (z1 - z0) * 0x100;
    sint32 ax = dx < 0 ? -dx : dx, ay = dy < 0 ? -dy : dy, az = dz < 0 ? -dz : dz, steps = ax >> 8;
    sint32 sx = 0, sy = 0, sz = 0;
    if (dx != 0)
    {
        sx = dx < 0 ? -0x10000 : 0x10000;
        sy = (dy / steps) << 8;
        sz = (dz / steps) << 8;
    }
    if ((ay >> 8) > steps)
    {
        steps = ay >> 8;
        sy = dy < 0 ? -0x10000 : 0x10000;
        sx = steps ? ((dx / steps) << 8) : 0;
        sz = steps ? ((dz / steps) << 8) : 0;
    }
    if ((az >> 8) > steps)
    {
        steps = az >> 8;
        sz = dz < 0 ? -0x10000 : 0x10000;
        sx = steps ? ((dx / steps) << 8) : 0;
        sy = steps ? ((dy / steps) << 8) : 0;
    }
    line[0] = x0 * 0x100;
    line[1] = y0 * 0x100;
    line[2] = z0 * 0x100;
    line[3] = sx;
    line[4] = sy;
    line[5] = sz;
    return steps;
}

/* 0x8009F07C. */
/* Original: FUN_8009F07C. */
void fixed_dda_advance(sint32 *line)
{
    line[0] += line[3];
    line[1] += line[4];
    line[2] += line[5];
}

/* Original: FUN_800FC37C. */
void hq_world_map_route_draw(sint32 x0, sint32 y0, sint32 z0, sint32 x1, sint32 y1, sint32 z1)
{
    sint32 line[6], steps = fixed_dda_initialize(x0, y0, z0, x1, y1, z1, line) / 0xc00;
    line[3] *= 0xc;
    line[4] *= 0xc;
    line[5] *= 0xc;
    while (steps-- >= 0)
    {
        sint32 den = z0 - g_camera_world_z;
        sint32 x = ((line[0] < 0 ? line[0] + 0xff : line[0]) >> 8) - g_camera_world_x;
        sint32 y = ((line[1] < 0 ? line[1] + 0xff : line[1]) >> 8) - g_camera_world_y;
        if (den)
            render_screen_sprite((sint16)(x * 0x140 / den), (sint16)(y * 0x163 / den - 0x40), 0x2006, (sint16)(g_render_depth_bucket + 1));
        fixed_dda_advance(line);
    }
}

/* Original: FUN_800FB700. */
void hq_world_map_update(HQ_WORLD_MAP_SELECTOR *object)
{
    HQ_MAP_NODE *nodes = (HQ_MAP_NODE *)player_assets_executable_address(0x800c28e4u);
    HQ_MAP_NODE *selected, *target = 0;
    EFFECT *effect;
    sint32 selected_is_portal, index;

    if (object->initialized == 0)
    {
        object->initialized = 1;
        return;
    }
    ((PLAYER *)g_player)->field_22c = 0;
    hq_reset_session_timer();
    effect = hq_effect_3b_get();
    hq_world_map_camera_update(effect->x + 0x6000, effect->y - 0x8000, effect->z - 0x11800);
    selected = nodes + g_hq_selected_map_node;
    g_next_stage_index = (sint32)selected->pad_02 + 1;
    selected_is_portal = (selected->flags & 0xc0) != 0;

    if (nodes[0].flags != 0xffff && object->briefing_active == 0)
    {
        for (index = 0; nodes[index].flags != 0xffff && object->briefing_active == 0; index++)
        {
            HQ_MAP_NODE *node = nodes + index;
            sint32 available = node->unlocked;
            sint32 x, y, dx, dy, z, ot, frame, route;
            SPRT *packet;
            if ((node->flags & 0x80) != 0)
            {
                HQ_MAP_NODE *linked = hq_world_map_node_find_by_id((sint16)(node->flags & 0x3f));
                if (linked && linked->unlocked)
                    node->unlocked = 1;
                available = node->unlocked;
            }
            if (node->region != g_hq_map_region)
                continue;
            if (!available && (node->flags & 0x80) == 0)
            {
                g_shared_scratch_value = 0;
                while (g_shared_scratch_value < 4)
                {
                    available |= nodes[node->neighbour[g_shared_scratch_value]].unlocked;
                    ++g_shared_scratch_value;
                }
            }
            if (index != g_hq_selected_map_node && !available)
                continue;
            if ((g_frame_counter & 0x10) != 0)
            {
                text_render((const char *)player_assets_executable_pointer(0x80082758u), (-g_font_glyph_width * 0x14) / 2, 0x50);
                text_render((const char *)player_assets_executable_pointer(0x8008275cu), (-g_font_glyph_width * 0x18) / 2, 0x60);
            }
            route = 0x800;
            dy = 0;
            x = object->collision.x + node->x * 0x100;
            y = object->collision.y + node->y * 0x100;
            if (index != g_hq_selected_map_node || selected_is_portal)
            {
                if ((node->flags & 0xc0) == 0)
                {
                    frame = available == 1 ? 0x2009 : (available == 2 ? 0x30800 : 0x2000);
                }
                else
                {
                    frame = (node->flags & 0x80) ? 0x2008 : 0x2007;
                    dy = 0x600;
                    route = 0;
                }
            }
            else
            {
                frame = animation_update(&object->animation);
                if (available == 1)
                    frame = 0x2009;
                if (available == 2)
                    frame = 0x30800;
                if (g_next_stage_index != -1)
                {
                    const char *name = (const char *)exec_ptr(0x800826c0u, g_next_stage_index);
                    sint32 text_x = ((x - g_camera_world_x) * 0x140) / (object->collision.z - g_camera_world_z);
                    sint32 right;
                    g_shared_scratch_value = text_byte_length(name);
                    right = text_x + g_shared_scratch_value * g_font_glyph_width;
                    if (right > g_screen_width / 2 - 0x10)
                        text_x -= right - (g_screen_width / 2 - 0x10);
                    text_render(name, text_x, ((y - g_camera_world_y) * 0x163) / (object->collision.z - g_camera_world_z) - 0x3c);
                }
            }
            z = object->collision.z - g_camera_world_z;
            ot = 0x480 - ((g_render_row_world_z - object->collision.z + (g_render_row_world_z < object->collision.z ? 0xff : 0)) >> 8);
            g_render_depth_bucket = ot;
            dx = ((x + route - g_camera_world_x) * 0x140) / z;
            dy = ((y + dy - g_camera_world_y) * 0x163) / z - 0x40;
            packet = render_screen_sprite((sint16)dx, (sint16)dy, (uint32)frame, (sint16)ot);
            if (index == g_hq_selected_map_node)
            {
                sint8 c = (sint8)((char)g_frame_counter * 0x10 - 0x80);
                packet->r0 = (uint8)c;
                packet->g0 = (uint8)c;
                packet->b0 = (uint8)c;
            }
            memset(drawn_nodes, 0, sizeof(drawn_nodes));
            for (route = 0; route < 4; route++)
            {
                sint32 ni = node->neighbour[route];
                HQ_MAP_NODE *next;
                if (ni < 0)
                    continue;
                next = nodes + ni;
                if (next->region != g_hq_map_region || drawn_nodes[ni])
                    continue;
                if ((next->flags & 0x80) != 0)
                {
                    if (!node->unlocked)
                    {
                        if (next->unlocked)
                        {
                            drawn_nodes[ni] = 1;
                            hq_world_map_route_draw(x, y + 0x200, object->collision.z, object->collision.x + next->x * 0x100, object->collision.y + (next->y + 2) * 0x100, object->collision.z);
                        }
                        continue;
                    }
                }
                if (!node->unlocked)
                    continue;
                if (((next->flags & 0x80) == 0 || next->unlocked) && index <= ni)
                {
                    drawn_nodes[ni] = 1;
                    hq_world_map_route_draw(x, y + 0x200, object->collision.z, object->collision.x + next->x * 0x100, object->collision.y + (next->y + 2) * 0x100, object->collision.z);
                }
            }
        }
    }

    if ((g_pressed_buttons & 0xf040) != 0 && object->briefing_active == 0)
    {
        sint32 old = g_hq_selected_map_node;
        selected = nodes + old;
        target = selected;
        g_shared_scratch_value = old;
        sound_play_nonpositional(3, 0, 0x7f);
        if (selected->neighbour[0] >= 0 && (g_pressed_buttons & 0x1000))
        {
            target = nodes + selected->neighbour[0];
            if (selected->unlocked || target->unlocked)
                g_hq_selected_map_node = target->index;
        }
        if (selected->neighbour[1] >= 0 && (g_pressed_buttons & 0x2000))
        {
            target = nodes + selected->neighbour[1];
            if (selected->unlocked || target->unlocked)
                g_hq_selected_map_node = target->index;
        }
        if (selected->neighbour[2] >= 0 && (g_pressed_buttons & 0x4000))
        {
            target = nodes + selected->neighbour[2];
            if (selected->unlocked || target->unlocked)
                g_hq_selected_map_node = target->index;
        }
        if (selected->neighbour[3] >= 0 && (g_pressed_buttons & 0x8000))
        {
            target = nodes + selected->neighbour[3];
            if (selected->unlocked || target->unlocked)
                g_hq_selected_map_node = target->index;
        }
        if (g_hq_selected_map_node != old && (target->flags & 0x80) && !target->unlocked)
            g_hq_selected_map_node = (sint16)old;
        if (selected_is_portal)
        {
            if (g_pressed_buttons & 0x40)
            {
                target = hq_world_map_node_find_by_id((sint16)(nodes[g_hq_selected_map_node].flags & 0x3f));
                g_hq_selected_map_node = (sint16)(target - nodes);
                g_hq_map_region = target->region;
                sound_play_nonpositional(4, 0, 0x7f);
                hq_background_texture_select(-1);
            }
            g_next_stage_index = -1;
        }
        else
            g_next_stage_index = (sint32)nodes[g_hq_selected_map_node].pad_02 + 1;
    }
    else if (selected_is_portal)
        g_next_stage_index = -1;

    if ((g_pressed_buttons & 0x40) != 0)
    {
        if (object->briefing_active != 0)
            hq_set_pending_transition();
        if (!selected_is_portal && object->briefing_active == 0)
        {
            const char *label = (const char *)exec_ptr(0x8008263cu, g_next_stage_index);
            object->briefing_active = 1;
            object->briefing_extent = (sint16)(g_font_line_height * text_line_break_count(label));
        }
    }
    if (object->briefing_active != 0)
    {
        const char *label = (const char *)exec_ptr(0x8008263cu, g_next_stage_index);
        if ((g_pressed_buttons & 0x10) != 0)
        {
            object->briefing_active = 0;
            return;
        }
        object->briefing_scroll_y = hq_scrolling_text_render(label, object->briefing_scroll_y, object->briefing_extent, (const char *)player_assets_executable_pointer(0x80082858u), 0);
    }
    else
        object->briefing_scroll_y = -0x50;
    if ((g_pressed_buttons & 0x10) != 0)
    {
        if (object_destroy_all_by_type(0x3a) != 0)
            g_hq_world_map_active = 0;
        hq_background_texture_select(0);
        ((PLAYER *)g_player)->field_22c = -1;
        ((PLAYER *)g_player)->menu_resume = 1;
    }
}

/* Original: FUN_800FB648. */
void hq_world_map_open(sint32 x, sint32 y, sint32 z)
{
    HQ_WORLD_MAP_SELECTOR *object;
    if (object_find_next_by_type(0, 0x3a) != 0)
        return;
    object = (HQ_WORLD_MAP_SELECTOR *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)hq_world_map_update);
    object->collision.object_type = 0x3a;
    object->collision.x = x;
    object->collision.y = y;
    object->collision.z = z;
    g_hq_world_map_active = 1;
    animation_start(&object->animation, (const sint32 *)win_code_module_address(0x800fe394u));
    object->briefing_scroll_y = -0x50;
    object->sampled_buttons = g_held_buttons;
    hq_background_texture_select(-1);
}

/* Original: FUN_800FC81C. */
GDB_CALL void hq_gramophone_close(void)
{
    PLAYER *player = (PLAYER *)g_player;
    HQ_MUSIC_SELECTOR *removed = (HQ_MUSIC_SELECTOR *)object_destroy_all_by_type(0x3d);
    if (removed == 0)
        return;
    if (removed->selected_track != 2)
        music_track_select(2, 1);
    player->field_22c = -1;
    player->menu_resume = 1;
}

/* Original: FUN_800FC6DC. */
GDB_CALL void hq_gramophone_update(HQ_MUSIC_SELECTOR *object)
{
    PLAYER *player = (PLAYER *)g_player;
    uint32 pressed = g_held_buttons & ~object->previous_buttons;
    object->previous_buttons = g_held_buttons;
    player->field_22c = 0;
    if ((pressed & 0x5000) != 0)
    {
        if ((pressed & 0x1000) != 0)
            ++object->selected_track;
        if ((pressed & 0x4000) != 0)
            --object->selected_track;
        sound_play_nonpositional(0x68, 0, 0x7f);
        if (object->selected_track >= 0x11)
            object->selected_track = 2;
        if (object->selected_track < 2)
            object->selected_track = 0x10;
        music_track_select(object->selected_track, 1);
    }
    text_render((const char *)player_assets_executable_pointer(0x8008275cu), 0, 0x20);
    text_render((const char *)player_assets_executable_pointer(0x80082760u), -0x60, 0);
    text_render(integer_to_text(object->selected_track), 0, g_font_glyph_height + 4);
    hq_reset_session_timer();
    if ((g_pressed_buttons & 0x10) != 0)
        hq_gramophone_close();
}

/* Original: FUN_800FC660. */
GDB_CALL void hq_gramophone_open(void)
{
    HQ_MUSIC_SELECTOR *object;
    if (object_find_next_by_type(0, 0x3d) != 0)
        return;
    object = (HQ_MUSIC_SELECTOR *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)hq_gramophone_update);
    object->collision.object_type = 0x3d;
    object->selected_track = 3;
    object->previous_buttons = g_held_buttons;
    cd_initialize();
    cd_track_table_initialize();
    music_track_select(object->selected_track, 0);
}

static const char *exe_pointer(uint32 address)
{
    return (const char *)player_assets_executable_pointer(address);
}

static void set_card_message(void *object, uint32 pointer_address)
{
    *ptr_at(sint32, object, 0xcc8) = (sint32)(intptr)exe_pointer(pointer_address);
}

static void make_save_payload(void *payload, char header[7])
{
    memcpy(header, hq_save_header, 7);
    strcat(header, integer_to_text(hq_unlocked_map_node_count()));
    memory_card_header_build(payload, header);
    hq_save_payload_serialize(payload);
}

static void finish_card_io(void *object, void *payload, sint32 result)
{
    memory_card_directory_scan(*(void **)ptr_at(uint8, object, 0xcc4));
    *ptr_at(sint16, object, 0xcdc) = 0;
    set_card_message(object, result == -1 ? 0x800827A0u : 0x800827C0u);
    *ptr_at(sint16, object, 0xccc) = 0x78;
    runtime_heap_defer_free(payload);
}

/* Original: FUN_800FD560. */
GDB_CALL void hq_memory_card_manager_close(void *object)
{
    object_destroy(object);
    memory_card_system_shutdown();
    *ptr_at(sint32, g_player, 0x22c) = -1;
    *ptr_at(sint16, g_player, 0x1b4) = 1;
}

/* Original: FUN_800FC8E8. */
GDB_CALL void hq_memory_card_manager_update(void *object)
{
    uint8 *active;
    uint32 buttons;
    sint16 card_entries;
    sint16 last_column;
    sint16 last_row;
    sint16 selection;
    sint16 row;
    sint16 suffix;
    sint16 index;
    char title[64];
    char header[7];
    char *filename = (char *)ptr_at(uint8, object, 0xcde);
    void *payload;
    sint32 handle;
    sint32 io_result;

    if (*ptr_at(sint16, object, 0xd2a) == 1)
    {
        memory_card_system_initialize();
        memory_card_context_select_slot(ptr_at(uint8, object, 0x7c), 0);
        memory_card_directory_scan(ptr_at(uint8, object, 0x7c));
        if (memory_card_usable_entry_count(ptr_at(uint8, object, 0x7c)) == 0 && ptr_at(uint8, object, 0x695)[0] != 0 && *ptr_at(sint16, object, 0xd26) == 0 && ptr_at(uint8, object, 0x69e)[0] != 0)
            hq_memory_card_error_acknowledge();
        *ptr_at(sint16, object, 0xd20) = 0;
    }
    if (*ptr_at(sint16, object, 0xd2a) != 0)
    {
        --*ptr_at(sint16, object, 0xd2a);
        text_render(exe_pointer(0x800827A4u), -0x20, 0);
        return;
    }

    title[0] = 0x13;
    strcpy(title + 1, exe_pointer(*ptr_at(sint16, object, 0xd26) != 0 ? 0x80082820u : 0x80082824u));
    g_text_color_index = 5;
    text_render(title, -(g_font_glyph_width * 9), -(g_font_glyph_height * 2 + 0x50));
    if (*ptr_at(sint16, object, 0xd26) == 0)
        text_render(exe_pointer(0x80082868u), 0, -(g_font_glyph_height + 0x50));
    text_render(exe_pointer(0x8008275Cu), 0, 0x60);
    g_scene_brightness_bias = -0x64;
    g_hq_session_timer = 0;

    if (*ptr_at(sint32, object, 0xcc8) != 0 && *ptr_at(sint16, object, 0xccc) != 0)
    {
        text_render((const char *)(intptr)*ptr_at(sint32, object, 0xcc8), -(g_font_glyph_width * 9), g_font_glyph_height - 0x42);
        --*ptr_at(sint16, object, 0xccc);
    }
    if (*ptr_at(sint16, object, 0xd28) != 0)
        --*ptr_at(sint16, object, 0xd28);

    active = *ptr_at(sint16, object, 0xd20) != 0 ? ptr_at(uint8, object, 0x6a0) : ptr_at(uint8, object, 0x7c);
    *(void **)ptr_at(uint8, object, 0xcc4) = active;
    *ptr_at(sint16, object, 0xcd8) = memory_card_event_poll((sint32)active[0x61b] << 4, 0);
    if (*ptr_at(sint16, object, 0xcd8) != 0)
    {
        memory_card_directory_scan(active);
        if (memory_card_usable_entry_count(active) == 0 && active[0x619] != 0 && *ptr_at(sint16, object, 0xd26) == 0 && ptr_at(uint8, object, 0x69e)[0] != 0)
            hq_memory_card_error_acknowledge();
        *ptr_at(sint16, object, 0xcdc) = 0;
        *ptr_at(sint16, object, 0xd24) = 0;
        *ptr_at(sint16, object, 0xd1e) = 0;
    }
    if (*ptr_at(sint16, object, 0xd22) == 0x1e && *ptr_at(sint16, object, 0xcd8) == 2)
    {
        vertical_sync_wait(0);
        g_held_buttons = controllers_read(0);
    }
    buttons = g_pressed_buttons;
    --*ptr_at(sint16, object, 0xd22);

    if (*ptr_at(sint16, object, 0xcdc) == 2 && *ptr_at(sint16, object, 0xd28) == 0)
    {
        strcpy(filename, (const char *)active + 0x61c);
        index = *ptr_at(sint16, object, 0xd1e);
        strcat(filename, (const char *)active + g_memory_card_entry_map[index] * 40 - 40);
        payload = runtime_heap_allocate(0x690);
        make_save_payload(payload, header);
        handle = memory_card_file_open(filename, 0x10002);
        io_result = memory_card_file_write(handle, payload, 0x690);
        memory_card_file_close(handle);
        finish_card_io(object, payload, io_result);
        buttons = 0;
    }

    if (*ptr_at(sint16, object, 0xcdc) == 3 && *ptr_at(sint16, object, 0xd28) == 0)
    {
        strcpy(filename, (const char *)active + 0x61c);
        strcat(filename, (const char *)player_assets_executable_address(0x800CDA38u));
        strcat(filename, hq_slot_text);
        for (suffix = 0; suffix < 14; ++suffix)
        {
            for (index = 0; index < active[0x61a]; ++index)
                if (atoi((const char *)active + g_memory_card_entry_map[index] * 40 - 24) == suffix)
                    break;
            if (index == active[0x61a])
                break;
        }
        payload = runtime_heap_allocate(0x690);
        make_save_payload(payload, header);
        strcat(filename, integer_to_text(suffix));
        handle = memory_card_file_open(filename, 0x10200);
        memory_card_file_close(handle);
        handle = memory_card_file_open(filename, 0x10002);
        io_result = memory_card_file_write(handle, payload, 0x690);
        memory_card_file_close(handle);
        finish_card_io(object, payload, io_result);
    }

    if (*ptr_at(sint16, object, 0xcdc) == 5 && *ptr_at(sint16, object, 0xd28) == 0)
    {
        strcpy(filename, (const char *)active + 0x61c);
        index = *ptr_at(sint16, object, 0xd1e);
        strcat(filename, (const char *)active + g_memory_card_entry_map[index] * 40 - 40);
        payload = runtime_heap_allocate(0x690);
        handle = memory_card_file_open(filename, 0x10001);
        io_result = memory_card_file_read(handle, payload, 0x690);
        memory_card_file_close(handle);
        *ptr_at(sint16, object, 0xcdc) = 0;
        *ptr_at(sint16, object, 0xccc) = 0x78;
        if (io_result == -1)
            set_card_message(object, 0x800827A0u);
        else
            set_card_message(object, hq_save_payload_deserialize(payload) == 0 ? 0x800827A0u : 0x800827B0u);
        runtime_heap_defer_free(payload);
        buttons = 0;
    }

    *ptr_at(sint32, g_player, 0x22c) = 0;
    card_entries = memory_card_entry_map_build(active, g_memory_card_entry_map, 1, hq_card_layout);
    last_column = (sint16)(((sint32)card_entries + 2) / 3 - 1);
    if (*ptr_at(sint16, object, 0xcdc) == 0)
    {
        if ((buttons & 0x8000) != 0)
            --*ptr_at(sint16, object, 0xcce);
        if ((buttons & 0x2000) != 0)
            ++*ptr_at(sint16, object, 0xcce);
        if ((buttons & 0x1000) != 0)
            --*ptr_at(sint16, object, 0xcd0);
        if ((buttons & 0x4000) != 0)
            ++*ptr_at(sint16, object, 0xcd0);
    }
    if (*ptr_at(sint16, object, 0xcd0) > last_column)
        *ptr_at(sint16, object, 0xcd0) = 0;
    if (*ptr_at(sint16, object, 0xcd0) < 0)
        *ptr_at(sint16, object, 0xcd0) = last_column;
    if (*ptr_at(sint16, object, 0xcd0) == last_column)
        row = (sint16)(card_entries % 3);
    else
        row = 0;
    last_row = row != 0 ? (sint16)(row - 1) : 2;
    if (*ptr_at(sint16, object, 0xcce) > last_row)
        *ptr_at(sint16, object, 0xcce) = 0;
    if (*ptr_at(sint16, object, 0xcce) < 0)
        *ptr_at(sint16, object, 0xcce) = last_row;
    selection = (sint16)(*ptr_at(sint16, object, 0xcce) + *ptr_at(sint16, object, 0xcd0) * 3);
    if (selection > card_entries - 1)
        selection = (sint16)(card_entries - 1);
    *ptr_at(sint16, object, 0xd1e) = selection;

    if (g_memory_card_entry_map[selection] != 0xfe)
    {
        if ((buttons & 0x40) != 0 || *ptr_at(sint16, object, 0xd30) != 0)
        {
            if (active[0x619] != 0)
            {
                if (*ptr_at(sint16, object, 0xd26) == 0)
                {
                    if (card_entries != 0 && active[0x622] != 0 && *ptr_at(sint16, object, 0xd28) == 0)
                    {
                        *ptr_at(sint16, object, 0xd30) = 0;
                        *ptr_at(sint16, object, 0xccc) = 3;
                        if (g_memory_card_entry_map[selection] != 0xff)
                        {
                            if (menu_run((void *)player_assets_executable_address(0x800C81B4u), 0, 0) == 0x49)
                                *ptr_at(sint16, object, 0xcdc) = 2;
                            else
                            {
                                *ptr_at(sint16, object, 0xcdc) = 0;
                                *ptr_at(sint16, object, 0xccc) = 0;
                            }
                        }
                        else
                        {
                            *ptr_at(sint16, object, 0xcdc) = 3;
                        }
                        *ptr_at(sint16, object, 0xd22) = 3;
                        *ptr_at(sint16, object, 0xd28) = 3;
                        set_card_message(object, 0x800827A8u);
                    }
                }
                else if (card_entries != 0 && selection != 0 && g_memory_card_entry_map[selection] != 0xff)
                {
                    if (menu_run((void *)player_assets_executable_address(0x800C8204u), 0, 0) == 0x49)
                    {
                        *ptr_at(sint16, object, 0xcdc) = 5;
                        *ptr_at(sint16, object, 0xd22) = 3;
                        *ptr_at(sint16, object, 0xccc) = 3;
                        *ptr_at(sint16, object, 0xd28) = 3;
                        set_card_message(object, 0x800827A4u);
                    }
                }
            }
        }
    }

    memory_card_grid_render(active, g_memory_card_entry_map, (uint8)selection, 3);
    if (*ptr_at(sint16, object, 0xd26) == 0 && *ptr_at(sint16, object, 0xd28) == 0 && active[0x619] != 0 && active[0x622] == 0)
    {
        memory_card_status_refresh(active);
        if (active[0x619] != 0 && active[0x622] == 0)
        {
            for (index = 0; index < 2; ++index)
            {
                frame_begin();
                screen_overlay_draw();
                end_frame_submit(1);
            }
            if (menu_run((void *)player_assets_executable_address(0x800C8164u), 0, 0) == 0x49)
            {
                memory_card_status_refresh(active);
                if (active[0x619] != 0 && active[0x622] == 0)
                {
                    memory_card_file_delete((const char *)active + 0x61c);
                    memory_card_directory_scan(active);
                    *ptr_at(sint16, object, 0xcdc) = 0;
                    *ptr_at(sint16, object, 0xccc) = 0x10;
                    *ptr_at(sint16, object, 0xd30) = 1;
                    *ptr_at(sint16, object, 0xd28) = 0x10;
                    set_card_message(object, 0x800827C4u);
                }
                else
                {
                    memory_card_directory_scan(active);
                }
            }
            else
            {
                g_pressed_buttons &= 0xffffffbfU;
                g_previous_held_buttons |= 0x40;
                hq_memory_card_manager_close(object);
                return;
            }
        }
    }
    if ((buttons & 0x10) != 0)
        hq_memory_card_manager_close(object);
    screen_overlay_draw();
}

/* Original: FUN_800FC87C. */
GDB_CALL void hq_memory_card_manager_open(sint32 mode)
{
    void *object;
    if (object_find_next_by_type(0, 0x3f) != 0)
        return;
    object = object_create(0xd34, (FUNC_COLLISION_UPDATE)hq_memory_card_manager_update);
    *ptr_at(sint16, object, 0x1c) = 0x3f;
    *ptr_at(sint16, object, 0xd2a) = 8;
    *ptr_at(sint16, object, 0xd26) = (sint16)mode;
    g_pressed_buttons = 0;
    *ptr_at(sint16, object, 0xd28) = 3;
}

/* Original: FUN_800FC538. */
GDB_CALL void hq_sliding_hud_create(void)
{
    COLLISION *object;

    if (object_find_next_by_type(0, 0x3c) != 0)
        return;
    object = (COLLISION *)object_create(0x80, hq_sliding_hud_update);
    object->x = -0x120;
    object->object_type = 0x3c;
}

static void spawn_ambient_object(EFFECT *source)
{
    HQ_OBJECT *object = (HQ_OBJECT *)object_create(sizeof(*object), hq_ambient_object_update);

    object->collision.x = source->x;
    object->collision.y = source->y + 0x5000;
    object->collision.z = source->z + 0x2100;
    object->collision.receives_mask = 1;
    object->collision.callback_18 = (FUNC_COLLISION_CALLBACK)hq_ambient_object_collect;
    object->marker = source;
    object->render_resource = random_range(1) + 0x2f400;
    source->values[0] = 1;
    collision_box_set(object, 0x30, 0x50, 0x10);
}

/* Original: FUN_800FD83C. */
GDB_CALL void hq_ambient_spawn_update(void)
{
    EFFECT *source;
    sint32 index;

    if ((g_frame_counter & 0x3f) != 0)
        return;
    index = random_range(7);
    source = effect_find_next(0x83, 0);
    while (index-- > 0)
        source = effect_find_next(0x83, source + 1);
    if (source->values[0] == 0)
        spawn_ambient_object(source);
}

/* Original: FUN_800FAE70. */
void hq_level_update(void)
{
    sint32 trace_position_pending = getenv("OA_MISSION_LAUNCH_TRACE") != 0 && g_player != 0;
    hq_texture_cache = -1;
    g_hq_session_timer = 0;
    hq_interaction_countdown = 0;
    hq_pending_transition = 0;
    hq_effect_3b = effect_find_next(0x3b, 0);
    hq_effect_3d = effect_find_next(0x3d, 0);
    hq_effect_3f = effect_find_next(0x3f, 0);

    if (trace_position_pending)
        remove("mission_launch_port.log");

    hq_sliding_hud_create();
    hq_background_texture_select(0);
#if 0 /* SKIP: original PSX memory-card availability warning is excluded. */
    if (g_memory_card_warning_checked == 0) hq_memory_card_warning_show();
#endif
    while (!app_quit_requested())
    {
        hq_ambient_spawn_update();
        g_scene_brightness_bias = 0;
        room_camera_limits_update();
        /* 800FAF20..800FAF38.  The common inactivity counter first restores
         * the two AGNTLOGO halves; its later threshold selects attract mode. */
        if (g_hq_session_timer == 800)
            hq_sliding_hud_create();

        if (g_previous_camera_world_z != -1)
        {
            g_previous_camera_world_x = g_camera_world_x;
            g_previous_camera_world_y = g_camera_world_y;
            g_previous_camera_world_z = g_camera_world_z;
        }

        frame_begin();
        selected_weapon_sync();
        spatial_buckets_reset();
        g_next_frame_object = g_frame_objects;
        hq_prompt_latched = 0;
        g_transient_prim_cursor = g_transient_prim_buffer;
        effects_update_visible();
        object_list_update();
        /* Audit-only recreation of the exact slot-3 player position.  Wait
         * through the first native object update: FUN_80097DB8 intentionally
         * expects gp+0x494 to retain the collision result established by an
         * earlier call, as shown at 0x80097E4C.  A loaded emulator state has
         * that history, while a fresh host boot does not. */
        if (trace_position_pending)
        {
            PLAYER *player = g_player;
            player->x = 0x8ca00;
            player->y = (sint32)0xfffffd00;
            player->z = 0x83c00;
            g_player_world_x = player->x;
            g_player_world_y = player->y;
            g_player_world_z = player->z;
            g_saved_player_world_x = g_player_world_x;
            g_saved_player_world_y = g_player_world_y;
            g_saved_player_world_z = g_player_world_z;
            trace_position_pending = 0;
        }
        if (g_surface_impact_cooldown != 0)
            --g_surface_impact_cooldown;
        object_collisions_dispatch();
        spatial_buckets_build();

        if (g_muzzle_light_pending != 0)
            map_light_stamp_apply(g_player_world_x + g_muzzle_light_x_direction * 0x4000, g_player_world_z + g_muzzle_light_z_direction * 0x4000, 0, g_muzzle_flash_light_stamp);
        render_map_scene();
        g_muzzle_light_pending = 0;
        map_light_stamp_apply(g_player_world_x + g_muzzle_light_x_direction * 0x4000, g_player_world_z + g_muzzle_light_z_direction * 0x4000, 0x80, g_muzzle_flash_light_stamp);

        g_stage_background_resource = (sint16)g_stage_env->background_resource;
        if (g_stage_background_resource != 0)
            render_stage_background();
        g_previous_held_buttons = g_held_buttons;
        g_scene_far_z = g_map_depth_cells * 0xc000;

        /* 800FB10C..800FB2E8: the three HQ interaction volumes. */
        if (hq_effect_3b != 0 && g_player_world_x > hq_effect_3b->x - 0x2000 && g_player_world_x < hq_effect_3b->x + 0xe000 && g_player_world_z > hq_effect_3b->z)
        {
            const char *prompt = (const char *)player_assets_executable_pointer(0x8008274cu);
            if (hq_interaction_prompt_update(prompt, 0x3a))
                hq_world_map_open(hq_effect_3b->x - 0x2000, -0xc000, hq_effect_3b->z + 0x1f00);
        }
        else
        {
            if (object_destroy_all_by_type(0x3a) != 0)
                g_hq_world_map_active = 0;
        }

        if (hq_effect_3d != 0 && g_player_world_x > hq_effect_3d->x - 0x3000 && g_player_world_x < hq_effect_3d->x + 0x3000 &&
            /* 800FB1E4 SLT player.z, marker.z; BNE skips when below. */
            g_player_world_z >= hq_effect_3d->z)
        {
            const char *prompt = (const char *)player_assets_executable_pointer(0x80082750u);
            if (hq_interaction_prompt_update(prompt, 0x3d))
                hq_gramophone_open();
        }
        else
        {
            hq_gramophone_close();
        }

        if (hq_effect_3f != 0 && g_player_world_x > hq_effect_3f->x - 0x3000 && g_player_world_x < hq_effect_3f->x + 0x3000 &&
            /* 800FB264/800FB268: same inclusive lower Z boundary. */
            g_player_world_z >= hq_effect_3f->z)
        {
            const char *prompt = (const char *)player_assets_executable_pointer(0x80082754u);
            if (hq_interaction_prompt_update(prompt, 0x3f))
            {
                g_shared_scratch_value = menu_run((void *)player_assets_executable_address(0x800c8124u), 0, 0);
                if (g_shared_scratch_value == 0x47)
                    hq_memory_card_manager_open(0);
                if (g_shared_scratch_value == 0x48)
                    hq_memory_card_manager_open(1);
            }
        }
        else
        {
            object_destroy_all_by_type(0x3f);
        }

        end_frame_submit(g_stage_background_resource);

        /* 800FB2F8..800FB400.  Preserve the original outer-session state
         * transition stores even though RECORD.BIN playback is a separate
         * dependency of the caller after this function returns. */
        if (g_held_buttons != 0)
        {
            g_hq_session_timer = 0;
            g_hq_attract_timeout = 5000;
        }
        else if (g_input_recording_mode != 1)
        {
            g_hq_session_timer = (sint16)(g_hq_session_timer + 1);
        }
        if (g_hq_session_timer == g_hq_attract_timeout)
        {
            const sint32 *session_table = (const sint32 *)player_assets_executable_address(0x800c8e48u);
            g_stage_index = session_table[g_attract_demo_index * 2];
            if (g_stage_index == -1)
            {
                g_attract_demo_variant = (sint16)(g_attract_demo_variant ^ 1);
                g_next_stage_index = 0;
                g_play_fmv = 1;
                g_hq_attract_timeout = 1250;
                g_attract_demo_index = 0;
                g_next_attract_mode = g_attract_demo_variant;
            }
            else
            {
                g_next_stage_index = g_stage_index + 1;
                g_hq_attract_timeout = 1250;
                g_input_recording_mode = 2;
            }
            break;
        }

        if (hq_pending_transition != 0 && g_next_stage_index != -1)
        {
            if (g_next_stage_index == 0)
                g_next_stage_index = 1;
            preserve_player_position();
            break;
        }

        if ((g_pressed_buttons & 0x100) != 0 && hq_prompt_latched == 0 && object_find_next_by_type(0, 0x3f) == 0 && g_frame_counter >= 9)
        {
            if (g_level_select_cheat_enabled != 0)
            {
                g_shared_scratch_value = menu_run((void *)win_code_module_address(0x800fe2f4u), 0, 0);
                if (g_shared_scratch_value == 0x4c)
                {
                    const sint32 *entry = (const sint32 *)win_code_module_address(0x800fe2fcu + (uint32)g_menu_selection_index * 0x10u);
                    g_next_stage_index = entry[0] + 1;
                    preserve_player_position();
                    break;
                }
            }
            else
            {
                g_shared_scratch_value = menu_run((void *)win_code_module_address(0x800fe354u), 0, 0);
            }
        }

        debug_input_update();
        if (object_find_next_by_type(0, 0x3f) == 0 && object_find_next_by_type(0, 0x3a) == 0)
            pause_menu_update();

        /* 0x800FB5B4..0x800FB620: HQ X-cell state consumed directly by
         * FUN_8009E29C and the player's item/action branches. Division is
         * signed truncation toward zero, exactly as the MIPS bias/shift. */
        g_shared_scratch_value = g_player_world_x;
        if (g_shared_scratch_value < 0)
            g_shared_scratch_value += 0x3fff;
        g_shared_scratch_value >>= 14;
        g_hq_weapon_area_enabled = (uint32)(g_shared_scratch_value - 4) < 0x0bu ? 1 : 0;
        if ((uint32)(g_shared_scratch_value - 0x15) < 5u)
            g_debug_cheats_enabled = 1;

        display_shake_update();
    }
}

/* Original: FUN_800FC874. */
GDB_CALL sint32 hq_zero_return(void)
{
    return 0;
}

/* 0x80087B60..0x80087C64.  The executable stores neighbour mission IDs in
 * each 0x14-byte record.  Startup resolves them in place to record indices;
 * the byte at +0x10 receives the record's own index.  IDA's long multiply /
 * negate / shift sequences are the compiler's signed division by 0x14. */
/* Original: FUN_80087B60. */
GDB_CALL void hq_world_map_relocate_nodes(void)
{
    HQ_MAP_NODE *base = (HQ_MAP_NODE *)player_assets_executable_address(0x800c28e4u);
    HQ_MAP_NODE *node = base;

    while (node->flags != 0xffffu)
    {
        sint32 direction;
        for (direction = 0; direction < 4; direction++)
        {
            if (node->neighbour[direction] != -1)
            {
                HQ_MAP_NODE *linked = hq_world_map_node_find_by_id(node->neighbour[direction]);
                node->neighbour[direction] = (sint16)(linked - base);
                node->index = (uint8)(node - base);
            }
        }
        ++node;
    }
}
