#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "game_sound.h"
#include "collision.h"
#include "effect_update.h"
#include "global.h"
#include "level_data.h"
#include "map.h"
#include "model.h"
#include "object.h"
#include "player.h"
#include "random.h"
#include "runtime_heap.h"
#include "scuba_player.h"
#include "sprite.h"
#include "stubs.h"

/* Types. */
/* Semantic module generated by tools/merge_semantic_modules.py.
 * Original MIPS address comments remain attached to each function. */
/* Runtime map-grid helpers around MAPFLOOR.BIN. */

struct MAP_STAMP
{
    sint16 cell_x;
    sint16 cell_z;
    uint16 width;
    uint16 height;
    sint16 values[1];
};

typedef char MapStamp_values_at_08[offsetof(MAP_STAMP, values) == 0x08 ? 1 : -1];

/* Exact map-runtime object constructor/callbacks from
 * SLES_004.74 0x800A6BB8..0x800A736C. */

typedef struct
{
    COLLISION collision;          /* +0x00 */
    sint16 health;                /* +0x78 */
    sint16 flash_clut_ticks;      /* +0x7A */
    MAP_MODEL_GROUP *group;       /* +0x7C */
    MAP_MODEL_INSTANCE *instance; /* +0x80 */
    sint32 velocity_y;            /* +0x84 */
    sint32 y_offset;              /* +0x88 */
    sint16 grounded;              /* +0x8C */
    sint16 bounce_count;          /* +0x8E */
} MAP_RUNTIME;

#if defined(AP_32BIT)
typedef char MapRuntimeObject_size_90[sizeof(MAP_RUNTIME) == 0x90 ? 1 : -1];
typedef char MapRuntimeObject_group_at_7c[offsetof(MAP_RUNTIME, group) == 0x7c ? 1 : -1];
typedef char MapRuntimeObject_velocity_y_at_84[offsetof(MAP_RUNTIME, velocity_y) == 0x84 ? 1 : -1];
#endif

/* Exact type-0x29 room/depth limit logic from FUN_800A7ACC/800A7C00. */

typedef struct
{
    sint32 min_x, min_y, max_x, max_y, signed_depth, side;
} ROOM_DEPTH_LIMIT;

typedef char RoomDepthLimit_size_18[sizeof(ROOM_DEPTH_LIMIT) == 0x18 ? 1 : -1];

typedef struct
{
    void *previous;                      /* +0x00 */
    void *next;                          /* +0x04 */
    uint32 field_08;                     /* +0x08 */
    void (*update)(void *);              /* +0x0C */
    void (*callback_10)(void *, void *); /* +0x10 */
    void (*callback_14)(void *, void *); /* +0x14 */
    void (*callback_18)(void *, void *); /* +0x18 */
    sint16 effect_type;                  /* +0x1C */
    uint16 field_1e;                     /* +0x1E */
    sint32 min_x, min_y, min_z;          /* +0x20..+0x28 */
    sint32 margin;                       /* +0x2C */
    sint32 field_30, field_34;           /* +0x30..+0x34 */
    sint32 max_x, max_y, max_z;          /* +0x38..+0x40 */
    uint8 field_44[0x34];                /* +0x44..+0x77 */
    sint16 activates_room;               /* +0x78 */
    uint16 field_7a;                     /* +0x7A */
} CAMERA_LIMIT;

#if defined(AP_32BIT)
typedef char CameraLimitObject_size_7c[sizeof(CAMERA_LIMIT) == 0x7c ? 1 : -1];
typedef char CameraLimitObject_update_at_0c[offsetof(CAMERA_LIMIT, update) == 0x0c ? 1 : -1];
typedef char CameraLimitObject_type_at_1c[offsetof(CAMERA_LIMIT, effect_type) == 0x1c ? 1 : -1];
typedef char CameraLimitObject_min_at_20[offsetof(CAMERA_LIMIT, min_x) == 0x20 ? 1 : -1];
typedef char CameraLimitObject_margin_at_2c[offsetof(CAMERA_LIMIT, margin) == 0x2c ? 1 : -1];
typedef char CameraLimitObject_max_at_38[offsetof(CAMERA_LIMIT, max_x) == 0x38 ? 1 : -1];
typedef char CameraLimitObject_room_at_78[offsetof(CAMERA_LIMIT, activates_room) == 0x78 ? 1 : -1];
#endif

/* Variables. */
/* The original table at 0x800EA298 holds forty records plus the terminating
 * -1 word. */
static ROOM_DEPTH_LIMIT room_depth_limits[41];

/* Functions. */
/* Direct translation of 0x80095E64..0x80095F98. */
/* Original: FUN_80095E64. */
void map_model_group_sort_by_y(MAP_MODEL_GROUP *group)
{
    sint32 swapped;
    if (group == 0 || group == (MAP_MODEL_GROUP *)g_map_model_groups || group->active_count < 2)
        return;
    do
    {
        sint32 i;
        swapped = 0;
        for (i = 0; i + 1 < group->active_count; ++i)
        {
            MAP_MODEL_INSTANCE *a = (MAP_MODEL_INSTANCE *)(group + 1) + i;
            MAP_MODEL_INSTANCE *b = a + 1;
            if (b->y < a->y)
            {
                MAP_MODEL_INSTANCE temp;
                memcpy(&temp, a, sizeof(temp));
                memcpy(a, b, sizeof(temp));
                memcpy(b, &temp, sizeof(temp));
                swapped = 1;
            }
        }
    } while (swapped);
}

/* Original: FUN_8009557C. */
MAP_FLOOR_CELL *map_floor_cell_at(sint32 world_x, sint32 world_z)
{
    sint32 cell_x;
    sint32 cell_z;
    if (world_x < 0)
        world_x += 0x3fff;
    world_z = g_map_depth_cells * 0xc000 - world_z;
    if (world_z < 0)
        world_z += 0x3fff;
    cell_x = world_x >> 14;
    cell_z = world_z >> 14;
    return g_map_floor_cells + cell_z * g_map_width_cells + cell_x;
}

/* Direct translation of 0x80096CAC..0x80096E9C.  The function deliberately
 * preserves the original sequence of low-word MIPS multiplies, signed
 * divisions and truncating quarter operations. */
/* Original: FUN_80096CAC. */
sint32 map_height_interpolate(sint32 h00, sint32 h01, sint32 h10, sint32 h11, sint32 extent_x, sint32 extent_z, sint32 local_x, sint32 local_z)
{
    sint32 top_left = h00 + 0x400;
    sint32 top_right = h01 + 0x400;
    sint32 bottom_left = h10 + 0x400;
    sint32 bottom_right = h11 + 0x400;
    sint32 top_sum = top_left + top_right;
    sint32 total = top_sum + bottom_left + bottom_right;
    sint32 half_z = extent_z / 2;
    sint32 half_x = extent_x / 2;
    sint32 z_centered = local_z - half_z;
    sint32 x_centered = local_x - half_x;
    sint32 average = total / 4;
    sint32 along_z;
    sint32 along_x;
    sint32 result;

    if (average == 0)
        average = 1;
    if (half_z == 0)
        half_z = 1;

    along_z = mips_mult_lo_div(top_sum, half_z + z_centered, half_z);
    along_z += mips_mult_lo_div(bottom_left + bottom_right, half_z - z_centered, half_z);
    along_z /= 4;

    along_x = mips_mult_lo_div(top_left + bottom_left, half_x + x_centered, half_x);
    along_x += mips_mult_lo_div(top_right + bottom_right, half_x - x_centered, half_x);
    along_x /= 4;

    result = mips_mult_lo_div(along_x, along_z, average) - 0x400;
    return (sint32)((uint32)result << 8);
}

/* Original: FUN_80096B94. */
sint32 map_floor_height_at(sint32 world_x, sint32 current_y, sint32 world_z)
{
    MAP_FLOOR_CELL *cell = map_floor_cell_at(world_x, world_z);
    sint32 map_z, local_x, local_z;
    sint16 h00, h01, h10, h11;
    if (cell->material == 0xff)
        return current_y + 0x800;

    map_z = g_map_depth_cells * 0xc000 - world_z;
    local_x = 0x4000 - (world_x - (world_x / 0x4000) * 0x4000);
    local_z = 0x4000 - (map_z - (map_z / 0x4000) * 0x4000);
    h00 = cell->height;
    h01 = (cell + 1)->height;
    h10 = (cell + g_map_width_cells)->height;
    h11 = (cell + g_map_width_cells + 1)->height;
    {
        sint32 height = map_height_interpolate(h00, h01, h10, h11, 0x4000, 0x4000, local_x, local_z);

        /* 0x80096C68..0x80096C84: publish the material/surface value for
         * the cell from the runtime table built by FUN_800AAEC8. */
        g_collision_surface_resource = g_stage_env->material_lookup[cell->material];
        return height;
    }
}

/* Original: FUN_80095FA0. */
void map_runtime_initialize(sint32 width, sint32 height)
{
    g_map_width_cells = width;
    g_map_depth_subcells = height << 6;
    g_map_depth_cells = height;
    g_map_width_subcells = width << 6;
    g_map_world_depth = height * 0xc000;
}

/* Exact MODLATTS.BIN lookup recovered as FUN_80095604. The file is a list
 * of {model_id, attribute} pairs terminated by an attribute of zero. */
sint32 model_attribute_find(sint16 model_id)
{
    const sint16 *entry = g_map_model_attributes;
    while (entry[1] != 0)
    {
        if (entry[0] == model_id)
            return entry[1];
        entry += 2;
    }
    return 0;
}

static void trace_map_object(const char *phase, MAP_RUNTIME *object)
{
    static sint32 started;
    static sint32 sequence;
    FILE *trace;

    if (getenv("OA_BREAKABLE_TRACE") == 0)
        return;
    trace = fopen("breakable_objects_port.log", started ? "a" : "w");
    if (trace)
    {
        fprintf(trace, "%s %d ptr=%p type=%d xyz=%08x,%08x,%08x half=%08x mask=%08x hp=%d box=%08x,%08x,%08x size=%08x,%08x,%08x\n", phase, sequence, object, (sint32)object->collision.object_type, (uint32)object->collision.x, (uint32)object->collision.y, (uint32)object->collision.z, (uint32)object->y_offset, (uint32)object->collision.receives_mask, (sint32)object->health, (uint32)object->collision.box_x, (uint32)object->collision.box_y, (uint32)object->collision.box_z, (uint32)object->collision.width, (uint32)object->collision.height, (uint32)object->collision.depth);
        fclose(trace);
    }
    started = 1;
    sequence++;
}

/* Original: FUN_800A6D64. */
static void map_runtime_object_update(MAP_RUNTIME *object)
{
    sint32 old_x = object->collision.x;
    sint32 old_y = object->collision.y;
    sint32 old_z = object->collision.z;
    sint32 depth = old_z - g_camera_world_z;
    sint32 sx, sy;
    sint32 floor_y;
    COLLISION_RESULT *result;

    if (old_z == g_camera_world_z)
        return;
    sx = (old_x - g_camera_world_x) * 0x140 / depth;
    if (sx > g_screen_half_width + 0x80 || sx < -(g_screen_half_width + 0x80))
        return;
    sy = (old_y - g_camera_world_y) * 0x163 / depth;
    if ((uint32)(sy + 0xc8) > 0x190u)
        return;

    object->velocity_y += 0x80;
    if (object->collision.object_type == 0x5d || object->collision.object_type == 0x93)
        object->velocity_y = 0;
    if (object->velocity_y > 0x500)
        object->velocity_y = 0x500;
    object->collision.y += object->velocity_y;

    result = static_map_collision_resolve(old_x, old_y + object->y_offset, old_z, object->collision.x, object->collision.y + object->y_offset, object->collision.z, 0x30, 0x30, 0x40);
    floor_y = map_floor_height_at(object->collision.x, object->collision.y + object->y_offset, object->collision.z);
    if (floor_y < object->collision.y + object->y_offset)
    {
        result->y = floor_y;
        result->flags |= 1;
    }
    if (result->flags & 1)
    {
        if (object->bounce_count == 0)
        {
            sint32 velocity = -object->velocity_y;
            object->bounce_count = 1;
            object->velocity_y = (velocity + (sint32)((uint32)velocity >> 31)) / 2;
        }
        else
            object->velocity_y = 0;
        object->collision.x = result->x;
        object->collision.y = result->y - object->y_offset;
        object->collision.z = result->z;
        object->grounded = 1;
    }
    else
        object->grounded = 0;
    {
        sint32 y = object->collision.y;
        if (y < 0)
            y += 0xff;
        object->instance->y = (sint16)(y >> 8);
    }
    trace_map_object("UPDATE", object);
}

/* Original: FUN_800A713C. */
static void map_runtime_object_damage(MAP_RUNTIME *object, FLASHABLE *source)
{
    sint16 type = object->collision.object_type;
    if (type == 0x94)
    {
        if (source->collision.object_type != 2 || source->field_78 != 10)
            return;
    }
    if (object_damage_apply((FLASHABLE *)object, source) == 0)
    {
        if (object->grounded == 0)
            return;
        object->velocity_y = -0x200;
        object->grounded = 0;
        return;
    }

    object->instance->y = 0x4e20;
    object_destroy(object);
    speech_random_request(9);
    if (type == 0x24 || type == 0x90 || type == 0x93)
        g_primary_target_current_count++;
    if (type == 0x48)
        g_secondary_target_current_count++;

    if (type == 0x48 || type == 0x90 || type == 0x93 || type == 0x94)
    {
        SPRITE *effect;
        sint32 kind = type == 0x94 ? 10 : 1;
        object->collision.y += 0x2000;
        effect = damage_expl_create(&object->collision, kind);
        collision_box_set(effect, 0xb4, 0xb4, 0xb4);
        object->collision.y -= 0x2000;
        sound_play_positional(10, 0, 0x96, object->collision.x, object->collision.y, object->collision.z);
        return;
    }
    if (g_scuba_stage_active == 0)
    {
        sound_play_positional(0x11, 0, 0x7f, object->collision.x, object->collision.y, object->collision.z);
        sound_play_positional(9, -2, 0x64, object->collision.x, object->collision.y, object->collision.z);
        timed_callback_create(expl_debris_particle_create, object->collision.x, object->collision.y + 0x2000, object->collision.z, 12, 2);
    }
    else
    {
        /* The alternative module callback at 0x800FDE7C belongs to the
         * non-HQ overlay selected when DAT_800D3DA4 is nonzero. */
        abort();
    }
}

/* Original: FUN_800A6BB8. */
void *map_runtime_object_create(sint32 x, sint32 y, sint32 z, MAP_MODEL_GROUP *group, MAP_MODEL_INSTANCE *instance, sint16 attribute)
{
    MAP_RUNTIME *object = (MAP_RUNTIME *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)map_runtime_object_update);
    sint32 half_y = g_model_descriptors[instance->model_id].half_y;
    object->group = group;
    object->instance = instance;
    object->collision.object_type = attribute;
    object->collision.x = x;
    object->collision.z = z;
    object->y_offset = -half_y * 0x100;
    object->collision.y = y + half_y * 0x100;
    if (attribute != 0x26)
    {
        sint32 collision_height = object->y_offset;
        object->collision.receives_mask = 0x11;
        object->collision.callback_18 = (FUNC_COLLISION_CALLBACK)map_runtime_object_damage;
        object->health = 6;
        if (attribute == 0x48 || attribute == 0x90 || attribute == 0x93)
            object->health = 0x19;
        if (collision_height < 0)
            collision_height += 0x7f;
        collision_box_set(object, 0x46, collision_height >> 7, 0x46);
        object->collision.box_y += object->y_offset;
        if (attribute == 0x24 || attribute == 0x90)
            g_primary_target_total_count++;
        if (attribute == 0x48)
            g_secondary_target_total_count++;
    }
    trace_map_object("OBJECT", object);
    return object;
}

/* Original: FUN_80095664. */
void map_grid_initialize(void)
{
    sint32 logical_cells;
    sint32 cell_index;
    sint32 cell_x = 0;
    sint32 row_z;
    MAP_FLOOR_CELL *floor = g_map_floor_cells;
    uint8 *collision_anchors;
    const STAGE_ENV_RECORD_TAIL *stage_entry = (const STAGE_ENV_RECORD_TAIL *)player_assets_executable_address(0x800cd504u + (uint32)g_stage_index * 0x24u);
    const sint32 *material_lookup = 0;
    sint32 special_material = 0;

    logical_cells = g_map_width_cells * g_map_depth_cells;
    collision_anchors = (uint8 *)runtime_heap_allocate(logical_cells * 8);
    g_dynamic_collision_cell_anchors = collision_anchors;
    g_spatial_cell_bucket_indices = (uint8 *)runtime_heap_allocate(logical_cells);
    g_map_cell_light_values = (uint8 *)runtime_heap_allocate(g_map_width_cells * (g_map_depth_cells + 5));
    g_map_model_record_count = 0;
    row_z = g_map_depth_cells * 0xc000 - 0x4000;
    if (stage_entry != 0)
    {
        /* 0x80095828..0x800958E8: stage_entry already denotes the field at
         * absolute 0x800CD504 (record +0x0C).  The special animated material
         * is at absolute 0x800CD510, therefore it is stage_entry +0x0C.  The
         * immutable +0x0C pointer is relocated to native DAT_800EA198. */
        material_lookup = g_material_resource_table;
        special_material = (sint32)stage_entry->map_resource;
    }

    for (cell_index = 0; cell_index < logical_cells; cell_index++)
    {
        MAP_FLOOR_CELL *cell = floor + cell_index;
        uint16 group_index = cell->group_index;
        MAP_MODEL_GROUP *group = (MAP_MODEL_GROUP *)((uint8 *)g_map_model_groups + (uint32)group_index * sizeof(*group));
        sint32 model_count;
        sint32 model_index;
        sint32 removed_count = 0;
        sint32 dynamic_anchor_initialized = 0;
        uint8 packed_orientation;
        sint32 material = 0;

        g_map_cell_light_values[cell_index] = 0;
        if (cell_x == g_map_width_cells)
        {
            cell_x = 0;
            row_z -= 0x4000;
        }

        packed_orientation = cell->packed_orientation;
        cell->packed_orientation = (uint8)((((packed_orientation & 3) * 2) + 2) & 7);
        model_count = group == (MAP_MODEL_GROUP *)g_map_model_groups ? 0 : (sint16)group->active_count;
        if (model_count > 0x80)
            fatal_error_with_value("MODEL COUNT STOPPROG", model_count);
        g_map_model_record_count += model_count + 1;

        if (material_lookup != 0)
            material = material_lookup[cell->material];
        if (special_material != 0 && special_material == material)
        {
            if ((cell->flags & 0x0f) == 0)
            {
                cell->slope = -1;
                (cell + 1)->slope = -1;
                cell->height = (sint16)(cell->height - random_range(g_terrain_variation_limit));
                (cell + 1)->height = (sint16)((cell + 1)->height - random_range(g_terrain_variation_limit));
            }
        }
        if (special_material == material && (cell->flags & 0x0f) != 0)
        {
            cell->flags &= 0xf0;
            cell->slope = 0;
        }
        if (packed_orientation & 4)
            cell->flags |= 0x40;
        if (packed_orientation & 8)
            cell->flags |= 0x80;

        for (model_index = 0; model_index < model_count; ++model_index)
        {
            MAP_MODEL_INSTANCE *instance = (MAP_MODEL_INSTANCE *)(group + 1) + model_index;
            sint32 attribute;
            instance->local_x = (sint16)((uint16)instance->local_x << 8);
            instance->local_z = (sint16)((uint16)instance->local_z << 8);
            instance->yaw = (sint16)(((uint16)instance->yaw & 0x03ff) << 2);
            attribute = model_attribute_find(instance->model_id);
            if (attribute == 0x2d || attribute == 0x2e)
            {
                sint32 trigger_height = g_model_descriptors[instance->model_id].half_y * -0x200;
                player_detect_ledge(cell_x * 0x4000 + instance->local_x, instance->y * 0x100 + trigger_height / 2, row_z + 0x2000, 0x2800, trigger_height);
                instance->local_z = (sint16)(instance->local_z + 0x2000);
                if (attribute == 0x2d)
                {
                    instance->y = (sint16)(instance->y + 5000);
                    group->removed_count = (sint16)(group->removed_count + 1);
                }
                else
                    instance->y = 6000;
                ++removed_count;
            }
            else if (attribute == 0x4d)
            {
                instance->local_z = (sint16)(instance->local_z + 0x2000);
                instance->y = (sint16)(instance->y + 5000);
                group->removed_count = (sint16)(group->removed_count + 1);
                ++removed_count;
            }
            else if (attribute == 0x25 || attribute == 0x95 || attribute == 0x63)
            {
                if (attribute == 0x25 || attribute == 0x95)
                {
                    OriginalModelDescriptor *descriptor = &g_model_descriptors[instance->model_id];
                    DYNAMIC_COLLISION_NODE *node;
                    void **anchor = (void **)(collision_anchors + cell_index * 8);
                    if (!dynamic_anchor_initialized)
                    {
                        linked_list_initialize(anchor);
                        dynamic_anchor_initialized = 1;
                    }
                    instance->y = (sint16)(instance->y + 5000);
                    group->removed_count = (sint16)(group->removed_count + 1);
                    node = (DYNAMIC_COLLISION_NODE *)runtime_heap_allocate(sizeof(*node));
                    linked_list_append(anchor, node);
                    node->attribute = (sint16)attribute;
                    node->min_x = cell_x * 0x4000 + instance->local_x - descriptor->half_x * 0x100;
                    node->max_x = node->min_x + descriptor->half_x * 0x200;
                    node->max_z = row_z + instance->local_z + 0x600;
                    node->min_z = row_z + instance->local_z - 0x1e00;
                    node->top_y = (descriptor->half_y + instance->y - 0x1380) * 0x100;
                    node->bottom_y = (instance->y - descriptor->half_y - 0x1390) * 0x100;
                }
                if (attribute == 0x63)
                {
                    instance->y = (sint16)(instance->y + 5000);
                    group->removed_count = (sint16)(group->removed_count + 1);
                }
                ++removed_count;
            }
        }
        map_model_group_sort_by_y(group);
        group->active_count = (sint16)(group->active_count - removed_count);

        model_count = group == (MAP_MODEL_GROUP *)g_map_model_groups ? 0 : (sint16)group->active_count;
        for (model_index = 0; model_index < model_count; model_index++)
        {
            MAP_MODEL_INSTANCE *instance = (MAP_MODEL_INSTANCE *)(group + 1) + model_index;
            sint32 attribute = model_attribute_find(instance->model_id);
            if (attribute == 0x39)
                g_object_type_0x39_model_id = instance->model_id;
            if (attribute == 0x24 || attribute == 0x26 || attribute == 0x48 || attribute == 0x5d || attribute == 0x90 || attribute == 0x93 || attribute == 0x94)
                map_runtime_object_create(cell_x * 0x4000 + instance->local_x, (instance->y - g_model_descriptors[instance->model_id].half_y) * 0x100, row_z + instance->local_z, group, instance, (sint16)attribute);
            if (attribute == 0x2f)
                g_model_descriptors[instance->model_id].special = 1;
            if (attribute == 0x71)
            {
                scuba_model_target_create(cell_x * 0x4000 + instance->local_x, instance->y << 8, row_z, instance->model_id);
                instance->y = 6000;
            }
            if (attribute == 0x7d)
            {
                g_bio_goo_model_id = instance->model_id;
                instance->y = 6000;
            }
            if (attribute == 0x80)
            {
                g_robot_press_model_id = instance->model_id;
                instance->y = 6000;
            }
        }
        cell_x++;
    }
}

/* Original: FUN_80095190. */
void map_light_stamp_apply(sint32 world_x, sint32 world_z, sint16 clear, const MAP_STAMP *stamp)
{
    sint32 x, z;
    sint32 base_x, base_z;
    sint32 random_offset;
    sint32 width = (sint16)stamp->width;
    sint32 height = (sint16)stamp->height;
    uint8 *destination;
    const sint16 *source = stamp->values;

    if (world_x < 0)
        world_x += 0x3fff;
    world_z = g_map_depth_cells * 0xc000 - world_z;
    if (world_z < 0)
        world_z += 0x3fff;
    base_x = (world_x >> 14) + stamp->cell_x;
    base_z = (world_z >> 14) + stamp->cell_z;
    destination = g_map_cell_light_values + base_z * g_map_width_cells + base_x;
    random_offset = random_range(0x30);

    for (z = 0; z < height; ++z)
    {
        for (x = 0; x < width; ++x)
        {
            sint16 value = *source++;
            if (clear == 0x80)
                *destination = 0;
            else if (value != -99)
                *destination = (uint8)(value + random_offset);
            ++destination;
        }
        destination += g_map_width_cells - width;
    }
}

/* 800A7DA8: horizontal camera-limit object update. */
/* Original: FUN_800A7DA8. */
void horizontal_camera_limit_update(CAMERA_LIMIT *object)
{
    if (g_player_world_x < object->min_x || object->max_x < g_player_world_x || g_player_world_y < object->min_y || object->max_y < g_player_world_y || g_player_world_z < object->min_z || object->max_z < g_player_world_z)
        return;
    if (object->activates_room != 0)
        g_room_activation_pending = 1;
    if (object->effect_type == 0x4e)
        g_camera_limit_left = object->min_x + object->margin;
    else
        g_camera_limit_right = object->max_x - object->margin;
}

/* 800A7E98: constructor for effect types 0x4E and 0x4F. */
/* Original: FUN_800A7E98. */
void horizontal_camera_limit_create(EFFECT *source)
{
    CAMERA_LIMIT *object = (CAMERA_LIMIT *)runtime_heap_allocate_best_fit(sizeof(*object));
    sint32 margin;
    if (!object)
        return;
    object->update = (FUNC_COLLISION_UPDATE)horizontal_camera_limit_update;
    linked_list_insert_after(g_object_list, object, g_object_list[0]);
    if ((sint16)source->values[0] == 0)
        source->values[0] = 2;
    if ((sint16)source->values[1] == 0)
        source->values[1] = 6;
    source->y += 0x2000;
    source->z -= 0x2000;
    object->effect_type = (sint16)source->type;
    object->max_y = source->y;
    object->min_y = source->y - (sint16)source->values[1] * 0x4000;
    object->min_z = source->z;
    object->max_z = source->z + (sint16)source->values[2] * 0x4000;
    if (source->type == 0x4e)
    {
        object->min_x = source->x - 0x2000;
        object->max_x = object->min_x + (sint16)source->values[0] * 0x4000;
    }
    else
    {
        object->max_x = source->x + 0x2000;
        object->min_x = object->max_x - (sint16)source->values[0] * 0x4000;
    }
    margin = (sint16)source->values[3] != 0 ? 0xb000 : 0x5000;
    if ((sint16)source->values[3] != 0)
        object->activates_room = 1;
    object->margin = margin;
    object->min_x -= margin;
    object->max_x += margin;
    source->type = 0;
}

/* 800A8018: vertical camera-limit object update. */
/* Original: FUN_800A8018. */
void vertical_camera_limit_update(CAMERA_LIMIT *object)
{
    if (g_player_world_x < object->min_x || object->max_x < g_player_world_x || g_player_world_y < object->min_y || object->max_y < g_player_world_y || g_player_world_z < object->min_z || object->max_z < g_player_world_z)
        return;
    if (object->effect_type == 0x6b)
        g_camera_limit_top = object->min_y + 0x7800;
    else
        /* 800A80B4 delay slot computes maxY-0x6000 before the non-0x6B
         * branch applies its additional -0x6C00. */
        g_camera_limit_bottom = object->max_y - 0x6000 - 0x6c00;
}

/* 800A80D8: constructor for effect types 0x6B and 0x6C. */
/* Original: FUN_800A80D8. */
void vertical_camera_limit_create(EFFECT *source)
{
    CAMERA_LIMIT *object = (CAMERA_LIMIT *)runtime_heap_allocate_best_fit(sizeof(*object));
    if (!object)
        return;
    object->update = (FUNC_COLLISION_UPDATE)vertical_camera_limit_update;
    linked_list_insert_after(g_object_list, object, g_object_list[0]);
    if ((sint16)source->values[1] == 0)
        source->values[1] = 2;
    source->values[2] = 1;
    source->z -= 0x2000;
    source->x -= 0x2000;
    object->min_x = source->x;
    object->min_z = source->z;
    object->max_x = source->x + (sint16)source->values[1] * 0x4000;
    object->max_z = source->z + (sint16)source->values[3] * 0x4000;
    object->effect_type = (sint16)source->type;
    if (source->type == 0x6b)
    {
        object->min_y = source->y - 0x2000;
        object->max_y = object->min_y + (sint16)source->values[2] * 0x4000;
    }
    else
    {
        object->max_y = source->y + 0x2000;
        object->min_y = object->max_y - (sint16)source->values[2] * 0x4000;
    }
    object->min_y -= 0x6000;
    object->max_y += 0x6000;
    source->type = 0;
}

/* Original: FUN_800A7ACC. */
void room_depth_limit_create(void)
{
    EFFECT *source = 0;
    ROOM_DEPTH_LIMIT *limit = room_depth_limits;
    sint32 count = 0;
    for (;;)
    {
        if (count == 40)
            fatal_error("MINZTABLE TOO SMALL");
        source = effect_find_next(0x29, source);
        if (source == 0)
        {
            limit->min_x = -1;
            return;
        }
        source->type = 0;
        limit->min_x = source->x - ((sint16)source->values[0] - 1) * 0x4000 - 0x2000;
        limit->min_y = source->y - ((sint16)source->values[2] - 1) * 0x4000 - 0x2000;
        limit->max_x = source->x + ((sint16)source->values[1] - 1) * 0x4000 + 0x2000;
        limit->max_y = source->y + ((sint16)source->values[3] - 1) * 0x4000 + 0x2000;
        limit->signed_depth = source->values[4] != 0 ? -source->z : source->z;
        limit->side = (sint16)source->values[5];
        ++count;
        ++limit;
        ++source;
    }
}

/* Original: FUN_800A7C00. */
void room_camera_limits_update(void)
{
    sint32 index;
    g_room_activation_pending = 0;
    g_camera_limit_near = g_camera_limit_left = g_camera_limit_right = -1;
    g_camera_limit_top = g_camera_limit_bottom = -1;
    g_room_player_near_z = g_room_player_far_z = 0;
    g_camera_limit_far = g_map_depth_cells * 0xc000;
    /* 0x800A7C48..0x800A7C60: while the player is following the recovery
     * path, the original skips all type-0x29 room depth-limit records. */
    if (g_player->update == player_checkpoint_recovery_update)
        return;
    for (index = 0; room_depth_limits[index].min_x != -1; ++index)
    {
        ROOM_DEPTH_LIMIT *limit = &room_depth_limits[index];
        sint32 depth = limit->signed_depth;
        sint32 distance;
        if (depth < 0)
            depth = -depth;
        if (!(limit->min_x < g_player_world_x && limit->min_y < g_player_world_y && g_player_world_x < limit->max_x && g_player_world_y < limit->max_y))
            continue;
        distance = (depth - 0x10e00) - g_camera_world_z;
        if (distance < 0)
            distance = -distance;
        if (distance >= 0x11800)
            continue;
        if (limit->side == 0)
        {
            g_camera_limit_near = limit->signed_depth;
            if (g_camera_limit_near < 0)
            {
                g_room_player_near_z = -g_camera_limit_near;
                g_camera_limit_near = -g_camera_limit_near;
            }
            g_camera_limit_near -= 0x10e00;
        }
        else
        {
            g_camera_limit_far = limit->signed_depth;
            if (g_camera_limit_far < 0)
            {
                g_room_player_far_z = -g_camera_limit_far;
                g_camera_limit_far = -g_camera_limit_far;
            }
            g_camera_limit_far -= 0x10e00;
        }
    }
}
