#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "airship.h"
#include "animation.h"
#include "game_sound.h"
#include "collision.h"
#include "effect_update.h"
#include "global.h"
#include "hq.h"
#include "level_data.h"
#include "map.h"
#include "mission.h"
#include "model.h"
#include "object.h"
#include "game_runtime.h"
#include "player.h"
#include "projectile.h"
#include "psx.h"
#include "random.h"
#include "render.h"
#include "runtime_heap.h"
#include "scuba_player.h"
#include "sprite.h"
#include "sprite_renderer.h"
#include "stubs.h"
#include "text_renderer.h"
#include "v2.h"
#include "vram_alloc.h"

/* Types. */
/* Semantic module generated by tools/merge_semantic_modules.py.
 * Original MIPS address comments remain attached to each function. */
/* Mission-completion control flow from PAL SLES-004.74.
 *
 * The functions in this file are translations of 0x8009E3B4..0x8009EA90
 * and 0x800AB99C..0x800ABD94.  The alternative-code-module branches are
 * deliberately excluded: the stage-0 resource script has no -9 command and
 * slot 4 proves DAT_800D3DA4 == 0.  Every branch reachable in Mission 0 is
 * represented below. */

typedef struct
{
    COLLISION collision;    /* +0x00 */
    sint16 health;          /* +0x78 */
    uint16 field_7a;        /* +0x7A */
    VRAM_SPRITE descriptor; /* +0x7C */
    ANIM animation;         /* +0xAC */
    sint32 field_c8;        /* +0xC8 */
    sint32 target_x;        /* +0xCC */
    sint32 target_z;        /* +0xD0 */
    sint16 fire_countdown;  /* +0xD4 */
    uint16 field_d6;        /* +0xD6 */
    EFFECT *target_effect;  /* +0xD8 */
} MORTAR_ACTOR;

typedef struct
{
    COLLISION collision; /* +0x00 */
    uint32 field_78;     /* +0x78 */
} MISSION_DROP_RANGE;

typedef struct
{
    COLLISION collision;     /* +0x00 */
    uint32 field_78;         /* +0x78 */
    EFFECT *source_effect;   /* +0x7C */
    sint16 activation_ticks; /* +0x80 */
    sint16 hint_delay;       /* +0x82 */
} MISSION_FLARE_AREA;

typedef struct
{
    COLLISION collision;        /* +0x00 */
    uint32 field_78;            /* +0x78 */
    sint16 first_sound_handle;  /* +0x7C */
    sint16 second_sound_handle; /* +0x7E */
    sint16 frame;               /* +0x80 */
    uint16 field_82;            /* +0x82 */
    BUILDING *building;         /* +0x84 */
} AIR_RAID_SEQUENCE;

#if defined(AP_32BIT)
typedef char MortarActor_size_dc[sizeof(MORTAR_ACTOR) == 0xDC ? 1 : -1];
typedef char MortarActor_descriptor_at_7c[offsetof(MORTAR_ACTOR, descriptor) == 0x7C ? 1 : -1];
typedef char MortarActor_animation_at_ac[offsetof(MORTAR_ACTOR, animation) == 0xAC ? 1 : -1];
typedef char MortarActor_target_at_d8[offsetof(MORTAR_ACTOR, target_effect) == 0xD8 ? 1 : -1];
typedef char MissionDropRange_size_7c[sizeof(MISSION_DROP_RANGE) == 0x7C ? 1 : -1];
typedef char MissionFlareArea_size_84[sizeof(MISSION_FLARE_AREA) == 0x84 ? 1 : -1];
typedef char AirRaidSequence_size_88[sizeof(AIR_RAID_SEQUENCE) == 0x88 ? 1 : -1];
typedef char MissionFlareArea_source_at_7c[offsetof(MISSION_FLARE_AREA, source_effect) == 0x7C ? 1 : -1];
typedef char AirRaidSequence_building_at_84[offsetof(AIR_RAID_SEQUENCE, building) == 0x84 ? 1 : -1];
#endif

struct MISSION_HUD_BAR
{
    sint32 x;        /* +0x00 */
    sint32 y;        /* +0x04 */
    sint32 width;    /* +0x08 */
    sint32 field_0c; /* +0x0C */
    sint32 maximum;  /* +0x10 */
    sint32 field_14; /* +0x14 */
    POLY_G4 fill;    /* +0x18 */
    POLY_F4 border;  /* +0x3C */
};

#if defined(AP_32BIT)
typedef char MissionHudBar_size_54[sizeof(MISSION_HUD_BAR) == 0x54 ? 1 : -1];
typedef char MissionHudBar_fill_at_18[offsetof(MISSION_HUD_BAR, fill) == 0x18 ? 1 : -1];
typedef char MissionHudBar_border_at_3c[offsetof(MISSION_HUD_BAR, border) == 0x3c ? 1 : -1];
#endif

/* Variables. */
static const sint32 mission_complete_animation[] = {-8, 8, 4, 0x7f, 0x4b, 0x5800, -8, 8, 4, 0x7f, 4, 0x5800, -1};

/* SLES-004.74 0x800CA700..0x800CA77C.  These are three directional frame
 * offset tables followed by the type-0x23 attack animation bytecode. */
static const sint32 mission0_enemy_walk_frames[4] = {0x16, 0x0c, 2, 0x0c};

static const sint32 mission0_enemy_alert_frames[4] = {0x14, 0x0a, 0, 0x0a};

static const sint32 mission0_enemy_attack_animation[] = {0x16, 0, 3, 1, 3, 0, 3, 1, -5, 0x10, -3, 0x800a37c4, -6, 0x12, 0x96, 3, 0, 3, 1, -3, 0x800a37c4, -7, 0x10, 0x10, 0, -1};

/* SLES-004.74 0x800CA8D4..0x800CA938: stage-17 type-0x49 enemy frames
 * and its exact attack bytecode. */
static const sint32 airfield_enemy_walk_frames[4] = {0x0e, 3, 0x19, 3};

static const sint32 airfield_enemy_alert_frames[4] = {0x0b, 0, 0x16, 0};

static const sint32 airfield_enemy_attack_animation[] = {-6, 0x28, 0xb4, 0x46, 0, 6, 1, 6, 2, -3, 0x800a1f9c, -6, 0x29, 0xb4, 6, 0, -1};

/* SLES-004.74 0x800CA4BC..0x800CA4FC and 0x800CA5A0..0x800CA64C.
 * Directional frame bases and attack bytecode used by object type 0x21. */
static const sint32 shack_enemy_walk_frames[4] = {0x25, 0x16, 7, 0x16};

static const sint32 shack_enemy_attack_frames[4] = {0x22, 0x13, 4, 0x13};

/* Originals: SLES_004.74:DAT_800CA4DC and DAT_800CA4EC (16 bytes each).
 * Byte-identical read-only tables. The secondary slot has no active reader;
 * special-attack readers index values, never compare table pointer identities.
 * Former second native name: shack_enemy_unused_frames. */
static const sint32 shack_enemy_high_attack_frames[4] = {0x1e, 0x0f, 0, 0x0f};

static const sint32 shack_enemy_attack_animation[] = {0x16, 0, 3, 1, 3, 2, 3, 1, -5, 0x10, -3, 0x800a37c4, -6, 0x19, 0x96, 3, 2, 3, 1, -3, 0x800a37c4, 3, 2, 3, 1, -3, 0x800a37c4, -6, 0x19, 0x96, 3, 2, 3, 1, -3, 0x800a37c4, -7, 0x10, 0x10, 0, 4, 3, -1};

/* SLES-004.74 0x800CA4FC..0x800CA5A0. */
static const sint32 enemy_patrol_animation[] = {5, 0, 5, 1, 5, 2, 5, 3, 5, 4, 5, 5, 5, 6, 5, 7, -2, 5, 7, 5, 6, 5, 5, 5, 4, 5, 3, 5, 2, 5, 1, 5, 0, -2, 4, 3, 0x3c, 0, 4, 3, -1};

/* PAL 800CABF8..800CACD0: type-07 directional offsets and two complete
 * animation scripts, referenced by 800A29E8..800A2A24. The patrol ends
 * with -2 (loop), attack with -1; -3 callbacks name MIPS text explicitly. */
static const sint32 officer_walk_frames[4] = {22, 2, 12, 2};

static const sint32 officer_attack_frames[4] = {20, 0, 10, 0};

static const sint32 officer_patrol_animation[] = {5, 0, 5, 1, 5, 2, 5, 3, 5, 4, 5, 5, 5, 6, 5, 7, -2};

static const sint32 officer_attack_animation[] = {28, 0, -6, 27, 150, -5, 16, -3, 0x800a37c4, 4, 1, -7, 16, 10, 0, -5, 16, -6, 27, 150, -3, 0x800a37c4, 4, 1, -7, 16, 18, 0, -1};

/* SLES-004.74 0x800CA64C.  FUN_800A2BD4 tests this exact animation start
 * before applying its alternate muzzle-flash height. */
static const sint32 enemy_special_attack_animation[] = {4, 3, 0x16, 0, 3, 1, 3, 2, 3, 1, -5, 0x10, -3, 0x800a37c4, -6, 0x19, 0x96, 3, 2, 3, 1, -3, 0x800a37c4, 3, 2, 3, 1, -3, 0x800a37c4, -6, 0x19, 0x96, 3, 2, 3, 1, -3, 0x800a37c4, -7, 0x10, 0x10, 0, 4, 3, -1};

/* SLES-004.74 0x800CAF10 and 0x800C8B20. */
static const sint32 enemy_bullet_animation[] = {0xc8, 0x26800, -2, 0xc8, 0x26800, -2};

static const sint32 bullet_impact_animation[] = {3, 0x440c, 3, 0x440d, 3, 0x440e, 3, 0x440f, 3, 0x4410, 3, 0x4411, 3, 0x4412, -1};

static const sint32 mortar_falling_animation[] = {-4, 1, 0x1388, 0x26801, -2};

static const sint32 mortar_fire_animation[] = {3, 0x400, 0x0f, 0x401, 3, 0x402, -6, 0x26, 0x7f, 3, 0x403, 3, 0x404, 0x0a, 0x404, -6, 0x27, 0x7f, -5, 1, 0x0a, 0x404, 5, 0x405, 3, 0x400, -1};

static const sint32 mortar_solid_impact_animation[] = {-4, 1, 6, 0x4400, 5, 0x4401, 4, 0x4402, 3, 0x4403, 3, 0x4404, 3, 0x4405, 3, 0x4406, 3, 0x4407, 3, 0x4408, 4, 0x4409, 4, 0x440a, 4, 0x440b, -1};

static const sint32 mortar_surface_impact_animation[] = {5, 0x1f800, 5, 0x1f801, 5, 0x1f802, 5, 0x1f803, 5, 0x1f804, 5, 0x1f805, 5, 0x1f806, 5, 0x1f807, 5, 0x1f808, 5, 0x1f809, 5, 0x1f80a, 5, 0x1f80b, 5, 0x1f80c, 5, 0x1f80d, 5, 0x1f80e, -1};

/* 0x800CACD0, indexed after quantizing the 10-bit facing angle to 8
 * sectors at 0x800A31D0..0x800A31EC. */
static const sint16 enemy_player_facing[8] = {0, 0, 1, 2, 2, 2, 3, 0};

/* Functions. */
void ambient_camera_sprite_create(void)
{
    const uint32 *animation_table = (const uint32 *)player_assets_executable_address(0x800c8ed0u);
    sint32 z = g_camera_world_z + 0x12c00;
    sint32 depth = z - g_camera_world_z;
    sint32 random = secondary_random_range(0x140);
    sint32 x = (sint32)(((uint32)random * (uint32)depth) / 0x140u) + g_camera_world_x - 0xa000;
    sint32 y;
    sint32 animation_index;
    SPRITE *sprite;

    random = secondary_random_range(0xf0) - 0x78;
    y = (sint32)(((uint32)random * (uint32)depth) / 0x163u) + g_camera_world_y;
    animation_index = secondary_random_range(0x10);
    if (animation_index > 3)
        animation_index = 3;
    sprite = world_sprite_create(x, y, z, (const sint32 *)player_assets_executable_address(animation_table[animation_index]));
    sprite->field_a8 = -100;
    sprite->field_ac = 1;
    sprite->scale_x = (uint16)secondary_random_range(0x3000);
    sprite->rotation_x = (sint16)((secondary_random_range(0x40) - 0x20) & 0x3ff);
}

/* Exact non-audio control flow of SLES-004.74 FUN_800AABB8
 * (0x800AABB8..0x800AABEC).  FUN_800AABF8 is the intentionally skipped
 * sound backend boundary; the signed 16-bit timer and repeated calls after
 * 0x168 are nevertheless retained exactly. */
void ambient_speech_timer_update(void)
{
    g_ambient_speech_timer = (sint16)((uint16)g_ambient_speech_timer + 1u);
    if (g_ambient_speech_timer >= 0x169)
        speech_random_request(0x0d);
}

void *mission_text_pointer(uint32 table, sint32 index)
{
    return (void *)player_assets_resolve_address(read_u32_le(player_assets_executable_address(table + (uint32)index * 4u)));
}

/* 0x8008A04C..0x8008A120.  Mission-unlock text shown after the completion
 * menu.  The saved word at gp+0x518 is DAT_800D41A0, not an input field. */
/* Original: FUN_8008A04C. */
void mission_unlock_text_show(sint32 stage)
{
    const char *text = (const char *)mission_text_pointer(0x80082640u, (sint16)stage);
    const char *caption = (const char *)mission_text_pointer(0x8008275cu, 0);
    sint16 offset = -0x50;
    sint16 extent = (sint16)((uint16)g_font_line_height * (uint16)text_line_break_count(text));
    uint32 saved_tick = g_frame_counter;
    for (;;)
    {
        frame_begin();
        offset = hq_scrolling_text_render(text, offset, extent, caption, 0);
        screen_overlay_draw();
        end_frame_submit(0);
        if ((g_pressed_buttons & 0x10) != 0 || xport_isquit())
            break;
    }
    g_player->menu_resume = 1;
    g_frame_counter = saved_tick;
}

/* 0x80087CEC..0x80087D54. */
/* Original: FUN_80087CEC. */
MissionRecord *mission_record_find_by_stage(sint16 stage)
{
    MissionRecord *record = (MissionRecord *)player_assets_executable_address(0x800c28e4u);
    for (;; record++)
    {
        if (record->connection == 0xffffu)
            fatal_error_with_value("RAF NOT FOUND", stage);
        if (record->stage == (uint8)stage)
            return record;
    }
}

/* 0x8009E4C4..0x8009EA90. */
/* Original: FUN_8009E4C4. */
void extraction_ladder_update(MISSION_EXTRACTION_LADDER *effect)
{
    PLAYER *player = g_player;
    sint32 original_y = effect->collision.y;
    sint32 trail_y = 0, trail_z = 0;
    sint32 delta_x, ot;

    if (effect->phase_counter == 0)
    {
        /* 8009E50C: LW gp+0xA0 = 0x800D3D28, the player's global Y.
         * This is deliberately not the camera Y at 0x800D3EB4. */
        sint32 limit = g_player_world_y - 0x3000;
        if (original_y < limit)
            effect->collision.y = original_y + 0x100;
        else
            effect->phase_counter = 1;
    }
    if (effect->phase_counter >= 0x47)
    {
        effect->collision.y -= 0x100;
        effect->collision.x += 0x200;
        if (effect->phase_counter == 0x47)
        {
            effect->horizontal_acceleration = 0x20;
            effect->horizontal_velocity = 0;
            effect->velocity_limit = 0x280;
        }
        if (effect->phase_counter >= 0x15f)
        {
            object_destroy(effect);
            return;
        }
    }
    if (effect->phase_counter != 0)
        ++effect->phase_counter;

    if (effect->ladder_x < effect->collision.x)
    {
        if (effect->horizontal_direction == 1)
        {
            effect->horizontal_direction = 0;
            effect->horizontal_acceleration -= 8;
            effect->velocity_limit -= 0xa0;
        }
        effect->horizontal_velocity += effect->horizontal_acceleration;
    }
    if (effect->collision.x < effect->ladder_x)
    {
        if (effect->horizontal_direction == 0)
        {
            effect->horizontal_direction = 1;
            effect->horizontal_acceleration -= 8;
            effect->velocity_limit -= 0xa0;
        }
        effect->horizontal_velocity -= effect->horizontal_acceleration;
    }
    if (effect->velocity_limit < 0)
        effect->velocity_limit = 0;
    if (effect->horizontal_acceleration < 0)
        effect->horizontal_acceleration = 0;
    if (effect->horizontal_velocity < -effect->velocity_limit)
        effect->horizontal_velocity = -effect->velocity_limit;
    if (effect->velocity_limit < effect->horizontal_velocity)
        effect->horizontal_velocity = effect->velocity_limit;
    effect->ladder_x += effect->horizontal_velocity;

    delta_x = effect->ladder_x - effect->collision.x;
    ot = 0x480 - div_trunc(g_render_row_world_z - effect->collision.z, 0x100);
    for (;;)
    {
        sint32 projected_y = g_camera_world_y + div_trunc(mul_lo(-g_vertical_cull_extent, effect->collision.z - g_camera_world_z), 0x163);
        sint32 sprite_y = effect->collision.y + trail_y;
        sint32 middle_y, rotation;
        if (sprite_y <= projected_y)
            break;
        middle_y = sprite_y - div_trunc(delta_x < 0 ? -delta_x : delta_x, 5);
        rotation = div_trunc(-(delta_x + div_trunc(delta_x, 8)), 0x100) & 0x3ff;
        render_world_sprite(0x800, effect->collision.x + delta_x, middle_y, effect->collision.z + trail_z, 0, 0x1000, 0x1000, 0, (sint16)ot, 2, 0, rotation);
        /* 8009E804 is the same gp+0xA0 player-Y load. */
        if (middle_y > g_player_world_y - 0x3000 && middle_y - 0x1000 <= g_player_world_y - 0x3000 && effect->player_captured != 0)
            player->x = effect->collision.x + delta_x;
        delta_x = div_trunc(delta_x, 2) + div_trunc(delta_x, 3);
        trail_y -= 0x1000;
        trail_z -= 0x100;
        ++ot;
    }

    if (player->y < effect->collision.y && player->velocity_y > 0)
    {
        if (effect->player_captured == 0)
        {
            effect->player_captured = 1;
            effect->horizontal_acceleration = 0x40;
            effect->horizontal_velocity = 0x280;
            effect->velocity_limit = 0x280;
            player->animation.flags = 1;
            player->animation.frame = 0x1f400 + effect->player_frame;
            effect->capture_delay = 0x28;
        }
    }
    if (effect->player_captured != 0)
    {
        player->animation.frame = 0x1f400 + effect->player_frame;
        player->animation.flags = 1;
        player->velocity_y = 0;
        player->y += effect->collision.y - original_y;
        if (effect->capture_delay == 0)
        {
            if ((g_frame_counter & 3) == 0)
                ++effect->player_frame;
            player->y -= 0x300;
        }
        else
            --effect->capture_delay;
        if (effect->player_frame >= 0x0c)
            effect->player_frame = 0;
        g_hq_world_map_active = 1;
    }
    {
        sint32 distance = div_trunc(g_camera_world_y - effect->collision.y, 0x100);
        sint32 volume;
        sint16 pair[2];
        if (distance < 0)
            distance = 0;
        volume = 0x80 - distance;
        if (volume < 0)
            volume = 0;
        pair[0] = pair[1] = (sint16)(volume << 7);
        sound_voice_spatial_volume_update(pair, effect->sound_handle);
    }
}

/* 0x8009E3B4..0x8009E4C0, Mission-0 (normal module) branch. */
/* Original: FUN_8009E3B4. */
void extraction_ladder_create(sint32 x, sint32 y, sint32 z)
{
    MISSION_EXTRACTION_LADDER *effect;
    sint32 handle;
    if (g_scuba_stage_active == 0 && object_find_next_by_type(0, 0x4c) == 0)
        return;
    effect = (MISSION_EXTRACTION_LADDER *)object_create(sizeof(*effect), (FUNC_COLLISION_UPDATE)extraction_ladder_update);
    effect->collision.object_type = 0x91;
    effect->velocity_limit = 0x500;
    effect->field_84 = 0x500;
    effect->collision.x = x;
    effect->collision.y = y;
    effect->collision.z = z;
    effect->horizontal_acceleration = 0x40;
    effect->horizontal_velocity = 0x500;
    effect->ladder_x = x;
    effect->collision.y = g_camera_world_y + div_trunc(mul_lo(-g_vertical_cull_extent, z - g_camera_world_z), 0x163);
    handle = sound_play_nonpositional(0x1d, 0, 0);
    effect->sound_handle = (sint16)handle;
}

/* Direct translation of 0x8009D784..0x8009D81C. */
/* Original: FUN_8009D784. */
sint32 mission_objective_counts(void)
{
    sint32 index, primary = 0, secondary = 0;
    for (index = 1; index <= g_primary_objective_count; index++)
        if (g_primary_objective_states[index] == 1)
            primary++;
    for (index = 1; index <= g_secondary_objective_count; index++)
        if (g_secondary_objective_states[index] == 1)
            secondary++;
    return primary * 0x10000 + secondary;
}

/* Direct translation of 0x800A1244..0x800A12D8. */
/* Original: FUN_800A1244. */
void mission_text_message_update(MISSION_TEXT_MESSAGE *object)
{
    if (object->steady == 0 || (g_frame_counter & 8) != 0)
        text_render(object->text, object->collision.x, object->collision.y);
    object->lifetime -= 1;
    if (object->lifetime == 0)
    {
        g_mission_message_slots[object->slot] = 0;
        object_destroy(object);
    }
}

/* Direct translation of 0x800A12DC..0x800A142C. */
/* Original: FUN_800A12DC. */
MISSION_TEXT_MESSAGE *mission_text_message_create(const char *text)
{
    MISSION_TEXT_MESSAGE *object = 0;
    sint16 slot;
    while ((object = (MISSION_TEXT_MESSAGE *)object_find_next_by_type(object, 0x5c)) != 0)
        if (object->source_text == text)
            return 0;
    object = (MISSION_TEXT_MESSAGE *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)mission_text_message_update);
    object->text_width = (sint16)text_byte_length(text);
    object->collision.x = -((object->text_width * g_font_glyph_width) / 2);
    for (slot = 0; slot < 0x10 && g_mission_message_slots[slot] != 0; slot++)
    {
    }
    object->collision.y = slot * g_font_line_height - 0x4c;
    g_mission_message_slots[slot] = 1;
    object->slot = (uint8)slot;
    object->collision.object_type = 0x5c;
    strcpy(object->text, text);
    object->source_text = text;
    object->lifetime = 0xb4;
    object->steady = 1;
    return object;
}

/* 0x800ABC50..0x800ABD94.  At 0x800ABCF4 the original installs the
 * WATER/SCUBA.BIN callback at overlay address 0x800FEEB8. */
/* Original: FUN_800ABC50. */
void mission_complete_begin(void)
{
    PLAYER *player = g_player;
    MissionRecord *record;
    sint32 counts;
    if (player->health <= 0)
        return;
    g_mission_ending = 1;
    if (g_scuba_stage_active != 0)
    {
        if (player->update == (FUNC_COLLISION_UPDATE)scuba_mission_complete_player_update)
            return;
        player->update = (FUNC_COLLISION_UPDATE)scuba_mission_complete_player_update;
        goto begin_completion;
    }
    if (player->update == (FUNC_COLLISION_UPDATE)player_mission_complete_update || player->update == (FUNC_COLLISION_UPDATE)door_transition_player_update)
        return;
    player->update = (FUNC_COLLISION_UPDATE)player_mission_complete_update;
    if (g_stage_index != 4 && g_stage_index != 8)
        extraction_ladder_create(g_player_world_x, g_player_world_y, g_player_world_z + 0x100);
begin_completion:
    player->render_flags = 0;
    player->draw_mode = 0;
    player->death_delay = 0xb4;
    sound_voice_stop(&player->spatial_sound_handle);
    mission_text_message_create((const char *)player_assets_executable_pointer(0x8008280cu));
    record = mission_record_find_by_stage((sint16)g_stage_index);
    record->unlocked = 1;
    counts = mission_objective_counts();
    if (g_secondary_objective_count == 0 || g_secondary_objective_count <= (counts & 0xffff))
        record->unlocked = 2;
}

/* Original: FUN_800A4184. */
void building_map_deform(sint32 world_x, sint32 world_z, sint32 width, sint32 rows, sint32 delta, sint32 upper, sint32 lower)
{
    sint32 cell_x = div_pow2_trunc(world_x, 14);
    sint32 cell_z = div_pow2_trunc(g_map_depth_cells * 3 * 0x4000 - world_z, 14);
    MAP_FLOOR_CELL *row = g_map_floor_cells + cell_z * g_map_width_cells + cell_x;
    sint32 row_index;

    for (row_index = 0; row_index < rows; row_index++, row += g_map_width_cells)
    {
        sint32 column;
        MAP_FLOOR_CELL *cell = row;
        for (column = width; column > 0; column--, cell++)
        {
            sint16 value = cell->height;
            if (value < upper - 0x10)
            {
                cell->height = (sint16)(value + delta);
                if (cell->height >= upper - 0x10 && column != width && column != 1)
                    cell->height = (sint16)((uint16)cell->height + random_range(0x20));
            }
            if (column == 1 && (cell + 1)->height < upper + 0x10)
                (cell + 1)->height = (sint16)((cell + 1)->height + delta);
            {
                MAP_MODEL_GROUP *group = (MAP_MODEL_GROUP *)((uint8 *)g_map_model_groups + (uint32)cell->group_index * sizeof(*group));
                sint32 original_count = group->active_count;
                sint32 total = original_count + (group->removed_count + original_count);
                sint32 index;
                MAP_MODEL_INSTANCE *instance = (MAP_MODEL_INSTANCE *)(group + 1);
                for (index = 0; index < total; index++, instance++)
                {
                    sint32 instance_y = instance->y;
                    sint32 top;
                    if (index >= original_count)
                        instance_y -= 0x1388;
                    top = instance_y + g_model_descriptors[instance->model_id].half_y;
                    if (top < upper && top > lower)
                    {
                        instance->local_x = (sint16)((random_range(2) + 0x1f) << 8);
                        instance->y = (sint16)(instance->y + delta);
                        instance_y += delta;
                        if (instance_y + g_model_descriptors[instance->model_id].half_y >= upper)
                            instance->y = 0x1770;
                    }
                }
            }
        }
    }
    if (g_scuba_stage_active == 0)
    {
        sint32 column;
        MAP_FLOOR_CELL *cell = row;
        for (column = width; column > 0; column--, cell++)
        {
            sint16 value = cell->height;
            if (value < upper - 0x10)
                cell->height = (sint16)(value + delta);
            if (column == 1 && (cell + 1)->height < upper + 0x10)
                (cell + 1)->height = (sint16)((cell + 1)->height + delta);
        }
    }
}

/* Original: FUN_800A3F90. */
static void destructible_building_update(BUILDING *object)
{
    sint32 age = object->age;
    building_map_deform(object->map_x, object->map_z, object->cell_width, object->cell_rows, age < 100 ? 0 : 4, object->upper_height, object->lower_height);
    if (age >= 100)
    {
        if (object->sound_delay == 0)
        {
            sint32 channel;
            sint32 sound;
            sint32 previous = g_previous_destruction_sound_variant;
            object->sound_delay = (sint16)(random_range(30) + 30);
            channel = -random_range(8);
            sound = random_range(3);
            if (previous == sound)
                sound++;
            sound &= 3;
            g_previous_destruction_sound_variant = (sint16)sound;
            sound_play_nonpositional(sound + 0x6b, channel, 0x7f);
        }
        else
            --object->sound_delay;
    }
    ++object->age;
    if ((g_frame_counter & 3) == 0)
    {
        SPRITE *effect = world_sprite_create(object->collision.x + (random_range(object->cell_width << 6) << 8), object->collision.y, object->collision.z + object->collision.box_z, (const sint32 *)player_assets_executable_address(0x800d8bc8));
        g_shared_result_pointer = effect;
        effect->scale_x = (uint16)(random_range(0x800) + 0x2000);
        effect->velocity_y = -0x300;
    }
    if (object->age > object->lifetime)
    {
        object_destroy(object);
        sound_voice_stop(&object->sound_handle);
        --g_objective_counts[6];
        speech_random_request(4);
    }
}

/* Original: FUN_800A4644. */
static void building_player_damage(FLASHABLE *object, void *source)
{
    uint16 saved = (uint16)object->field_78;
    object->field_78 = 0x400;
    player_apply_damage(object, source);
    object->field_78 = (sint16)saved;
}

/* Original: FUN_800A3DC0. */
void destructible_building_damage(BUILDING *object, FLASHABLE *source)
{
    sint32 source_type;
    COLLISION *node;

    if (source == 0)
        source_type = 0x270f;
    else
    {
        source_type = source->collision.object_type;
        if (g_stage_index == 13)
            source_type = 0;
    }
    if (source_type == 2 && source->field_78 != 10)
        return;
    if (source_type != 2 && source_type != 0x270f)
        return;

    object->collision.update = (FUNC_COLLISION_UPDATE)destructible_building_update;
    object->collision.receives_mask = 6;
    object->field_78 = 100;
    object->collision.sends_mask = 1;
    object->collision.callback_14 = (FUNC_COLLISION_CALLBACK)building_player_damage;
    --g_objective_counts[6];
    object->lifetime = div_pow2_trunc(object->vertical_span, 10) + 0x78;
    object->sound_handle = (sint16)sound_play_nonpositional(0x36, -2, 0x7f);
    sound_play_nonpositional(0x6b, -2, 0x7f);

    node = (COLLISION *)((OBJECT *)g_ledge_trigger_list[0])->next;
    while (node != 0)
    {
        COLLISION *next = node->next;
        if (node->x <= object->collision.x || node->x >= object->collision.x + object->collision.width || node->y > (object->upper_height << 8) || node->y <= (object->lower_height << 8) || node->z >= object->collision.z || node->z <= object->collision.z + object->collision.box_z)
        {
            node = next;
            continue;
        }
        linked_list_unlink(g_ledge_trigger_list, node);
        runtime_heap_defer_free(node);
        node = next;
    }
}

/* Original: FUN_800A3BC4. */
void building_create(EFFECT *effect)
{
    EFFECT *first = effect;
    EFFECT *second;
    BUILDING *object;
    sint32 dx, dy, dz, collision_x, collision_y, collision_z;

    first->type = 0;
    first->z += 0x4000;
    second = effect_find_next(0x28, first + 1);
    while (second != 0 && second->values[0] != first->values[0])
        second = effect_find_next(0x28, second + 1);
    if (second == 0)
        fatal_error("NO PAIR DEST");
    second->type = 0;
    if (first->y < second->y)
    {
        EFFECT *swap = first;
        first = second;
        second = swap;
    }

    object = (BUILDING *)runtime_heap_allocate(sizeof(*object));
    linked_list_append(g_object_list, object);
    object->collision.x = (first->x & -0x4000) + 0x4000;
    object->collision.z = first->z & -0x4000;
    dx = second->x - first->x;
    dz = first->z - second->z;
    dy = first->y - second->y;
    object->cell_width = div_pow2_trunc(dx - 0x4000, 14);
    object->cell_rows = div_pow2_trunc(dz - 0x4000, 14);
    object->vertical_span = dy;
    object->map_x = object->collision.x;
    object->map_z = object->collision.z;
    object->collision.object_type = 0x28;
    object->collision.receives_mask = 1;
    object->collision.callback_18 = (FUNC_COLLISION_CALLBACK)destructible_building_damage;
    object->collision.y = first->y + 0x1f00;
    collision_x = div_pow2_trunc(dx - 0x4000, 8);
    collision_y = div_pow2_trunc(dy, 8);
    collision_z = div_pow2_trunc(dz - 0x4000, 8);
    collision_box_set(object, collision_x, collision_y, collision_z);
    object->collision.box_z = -(dz - 0x4000);
    object->collision.box_x = 0;
    object->upper_height = div_pow2_trunc(first->y, 8) + 0x20;
    object->lower_height = div_pow2_trunc(second->y, 8) - 0x21;
    object->source_effect = first;
}

/* Original: FUN_800A4588. */
static void building_collapse_activate(BUILDING_COLLAPSE *object, FLASHABLE *source)
{
    BUILDING_COLLAPSE *scan = 0;
    if (source->field_78 != 10)
        return;
    object_destroy(source);
    for (;;)
    {
        scan = (BUILDING_COLLAPSE *)object_find_next_by_type(scan, 0x5e);
        if (scan == 0)
        {
            BUILDING *building = 0;
            do
            {
                building = (BUILDING *)object_find_next_by_type(building, 0x28);
            } while (building->source_effect->values[0] != object->source_effect->values[0]);
            destructible_building_damage(building, 0);
            return;
        }
        --g_objective_counts[6];
        if (scan->source_effect->values[0] == object->source_effect->values[0])
            return;
    }
}

/* Original: FUN_800A44F8. */
void building_collapse_create(EFFECT *effect)
{
    BUILDING_COLLAPSE *object;
    effect->type = 0;
    object = (BUILDING_COLLAPSE *)object_create(sizeof(*object), 0);
    object->collision.x = effect->x;
    object->collision.y = effect->y;
    object->collision.z = effect->z + 0x2000;
    object->collision.object_type = 0x5e;
    object->source_effect = effect;
    collision_box_set(object, 0x50, 0x50, 0x50);
    object->collision.callback_18 = (FUNC_COLLISION_CALLBACK)building_collapse_activate;
    object->collision.receives_mask = 1;
}

/* Exact PAL 0x800A829C..0x800A8348: tower volume enables player state 0x242. */
/* Original: FUN_800A829C. */
void tower_surface_trigger_update(EFFECT *effect)
{
    if (!(effect->x - 0x1800 < g_player_world_x + 0x1300 && g_player_world_x - 0x1300 < effect->x + 0x1800))
        return;
    if (!(effect->z - 0x1e00 < g_player_world_z + 0x300 && g_player_world_z - 0x300 < effect->z + 0x1e00))
        return;
    if (g_player_world_y < effect->y + 0x1f00 - ((sint16)effect->values[0] << 8) || effect->y + 0x2300 < g_player_world_y)
        return;
    g_player->surface_state = 1;
#ifdef XPORT_NATIVE
    if (g_stage_index == 28 && getenv("OA_STAGE28_TRACE"))
    {
        FILE *f = fopen("../status/the-tower-native.log", "w");
        if (f)
        {
            fprintf(f, "THE_TOWER_NATIVE effect=%d,%d,%d player=%d,%d,%d value=%d flag=%d\n", effect->x, effect->y, effect->z, g_player_world_x, g_player_world_y, g_player_world_z, (sint16)effect->values[0], g_player->surface_state);
            fclose(f);
        }
    }
#endif
}

/* Exact PAL 0x800A39D8..0x800A3B04: proximity-triggered falling hazard. */
/* Original: FUN_800A3B04. */
static void falling_hazard_bounce(void *raw)
{
    SPRITE *object = (SPRITE *)raw;
    if (g_player_world_x < object->collision.x)
        object->velocity_x = -0x200;
    if (object->collision.x < g_player_world_x)
        object->velocity_x = 0x200;
    object->velocity_y = -(object->velocity_y / 2 + object->velocity_y / 4);
    sound_play_positional(9, 0, 0x96, object->collision.x, object->collision.y, object->collision.z);
    object->velocity_z = -0x100;
}

/* Original: FUN_800A39D8. */
void falling_hazard_create(EFFECT *effect)
{
    SPRITE *object;
    MODEL_NODE *node;
    if (g_player_world_x < effect->x - 0x8000 || effect->x + 0x8000 < g_player_world_x)
        return;
    effect->type = 0;
    sound_play_positional(9, 0, 0x96, effect->x, effect->y, effect->z);
    object = world_sprite_create(effect->x, effect->y - 0x10000, effect->z, (const sint32 *)1);
    node = (MODEL_NODE *)runtime_heap_allocate(sizeof(*node));
    object->model = node;
    node->scale = 0x1400;
    node->model_id = g_object_type_0x39_model_id;
    object->rotation_step_y = 0x20;
    object->render_kind = 3;
    object->animation.delay = 0x1770;
    object->lifetime = 0x12c;
    object->collision_callback = falling_hazard_bounce;
    object->acceleration_y = 0x20;
    object->collision.receives_mask = 2;
    object->collision.callback_14 = player_apply_damage;
    object->damage = 0xaa;
    collision_box_set(object, 0x60, 0x60, 0x60);
    object->collision.box_y += 0x3000;
#ifdef XPORT_NATIVE
    if (g_stage_index == 26 && getenv("OA_STAGE26_TRACE"))
    {
        sint32 player_x = g_player_world_x;
        FILE *file = fopen("../status/subterranea-native.log", "w");
        if (file)
        {
            fprintf(file, "SUBTERRANEA_NATIVE_CTOR xyz=%d,%d,%d health=%d flags=%d node_model=%d update=800a3b04\n", object->collision.x, object->collision.y, object->collision.z, object->damage, object->collision.receives_mask, node->model_id);
            fclose(file);
        }
        g_player_world_x = object->collision.x - 1;
        object->velocity_y = 1000;
        falling_hazard_bounce(object);
        file = fopen("../status/subterranea-native.log", "a");
        if (file)
        {
            fprintf(file, "SUBTERRANEA_NATIVE_UPDATE vx=%d vy=%d vz=%d\n", object->velocity_x, object->velocity_y, object->velocity_z);
            fclose(file);
        }
        g_player_world_x = player_x;
        object_destroy(object);
    }
#endif
}

/* Original: FUN_800A14E4. Direct translation of 0x800A14E4..0x800A16F4. */
sint32 mission_enemy_update_visibility(COLLISION *object, EFFECT *source, sint16 type, uint16 clut)
{
    VRAM_SPRITE *descriptor = (VRAM_SPRITE *)object->frame_descriptor;
    sint32 visible = world_object_is_visible(object->x, object->y, object->z, 0x30000);
    if (!visible)
    {
        if (descriptor->region_token != 0)
            sprite_vram_defer_release(descriptor);
        if (source == 0)
            goto remove_object;
        if (effect_is_visible(source) != 0)
            return 0;
    }
    else
    {
        if (!world_object_is_visible(object->x, object->y, object->z, 0x6000))
        {
            if (descriptor->region_token == 0)
                return 2;
            sprite_vram_defer_release(descriptor);
            return 2;
        }
        if (descriptor->region_token != 0)
            return 1;
        g_vram_error_reporting_enabled = 0;
        if (type == 0x37)
            visible = sprite_vram_allocate(descriptor, 0x46, 0x50, 1) != 0;
        else if (type == 0x6e)
            visible = sprite_vram_allocate(descriptor, 0x5a, 0x30, 1) != 0;
        else if (type == 0x66 || type == 0x7e || type == 0x92 || type == 0x8e)
            visible = sprite_vram_allocate(descriptor, 0x46, 0x5a, 1) != 0;
        else
            visible = sprite_vram_allocate(descriptor, 0x40, 0x50, 1) != 0;
        g_vram_error_reporting_enabled = 1;
        if (visible)
        {
            descriptor->clut = clut;
            return 1;
        }
        if (source == 0)
            goto remove_object;
    }
    source->type = type;
remove_object:
    object_destroy(object);
    return 0;
}

/* Direct translation of 0x800A4E1C..0x800A4EA4. */
/* Original: FUN_800A4E1C. */
sint32 angle_to_player(sint32 x, sint32 z, sint32 divisor)
{
    sint32 dx = g_player_world_x - x;
    sint32 dz = g_player_world_z - z;
    if (dx < 0)
        dx += 0xfff;
    if (dz < 0)
        dz += 0xfff;
    return (fixed_angle_from_vector(dx >> 12, dz >> 12) & 0x3ff) / divisor;
}

/* Original: FUN_800A640C. Direct translation of 0x800A640C..0x800A66D0. */
static sint32 projectile_update(PROJECTILE *object)
{
    sint32 old_x = object->collision.x;
    sint32 old_y = object->collision.y;
    sint32 old_z = object->collision.z;
    sint32 floor_y;
    sint16 collision;
    fixed_dda_advance(object->motion);
    if (object->wind_enabled != 0)
        object->motion[0] += g_effect_wind_x * 0x100;
    {
        sint32 value = object->motion[0];
        if (value < 0)
            value += 0xff;
        object->collision.x = value >> 8;
        value = object->motion[1];
        if (value < 0)
            value += 0xff;
        object->collision.y = value >> 8;
        value = object->motion[2];
        if (value < 0)
            value += 0xff;
        object->collision.z = value >> 8;
    }
    if (object->probe_mode == 0)
    {
        if (!world_object_is_visible(object->collision.x, object->collision.y, object->collision.z, 0xc800))
            object_destroy(object);
        animation_update(&object->animation);
        g_next_frame_object->force_light = 1;
        render_world_sprite((uint32)object->animation.frame, object->collision.x, object->collision.y, object->collision.z, 0, object->scale, object->scale, (POLY_FT4 *)object->collision.prim, 0, 0, 0, 0);
    }
    floor_y = map_floor_height_at(object->collision.x, object->collision.y, object->collision.z);
    collision = swept_collision_test(old_x, old_y, old_z, &object->collision.x, &object->collision.y, &object->collision.z);
    if (collision == 0 && object->collision.y <= floor_y)
    {
        FUNC_COLLISION_UPDATE callback = object->floor_callback;
        if (callback != 0)
            callback(object);
        return 0;
    }
    {
        FUNC_COLLISION_UPDATE callback = object->impact_callback;
        if (callback == 0)
        {
            if (object->probe_mode == 0)
            {
                SPRITE *impact;
                object_destroy(object);
                impact = world_sprite_create(object->collision.x, object->collision.y, object->collision.z, bullet_impact_animation);
                g_shared_result_pointer = impact;
                impact->scale_x = 0x1800;
                projectile_surface_impact_emit(object->collision.x, object->collision.y, object->collision.z);
            }
        }
        else
        {
            callback(object);
            object_destroy(object);
        }
    }
    return 1;
}

/* Original: FUN_800A62AC. Direct translation of 0x800A62AC..0x800A6408.  The original leaves the
 * allocated object in v0, and both callers consume it as the return value. */
PROJECTILE *projectile_create(sint32 x0, sint32 y0, sint32 z0, sint32 x1, sint32 y1, sint32 z1)
{
    PROJECTILE *object = (PROJECTILE *)runtime_heap_allocate(sizeof(*object));
    POLY_FT4 *prim = (POLY_FT4 *)object->collision.prim;
    object->collision.update = (FUNC_COLLISION_UPDATE)projectile_update;
    linked_list_append(g_object_list, object);
    fixed_dda_initialize(x0, y0, z0, x1, y1, z1, object->motion);
    object->motion[3] *= 5;
    object->motion[4] *= 5;
    object->motion[5] *= 5;
    SetPolyFT4(prim);
    SetShadeTex(prim, 0);
    SetSemiTrans(prim, 1);
    object->collision.x = x0;
    object->collision.y = y0;
    object->collision.z = z0;
    collision_box_set(object, 2, 2, 2);
    object->collision.receives_mask = 2;
    object->collision.callback_14 = player_apply_damage;
    animation_start(&object->animation, enemy_bullet_animation);
    object->collision.object_type = 0x18;
    object->scale = 0x1000;
    return object;
}

/* Original: FUN_800A617C. Direct translation of 0x800A617C..0x800A62A8. */
static sint32 projectile_test_path(sint32 x0, sint32 y0, sint32 z0, sint32 x1, sint32 y1, sint32 z1, sint32 steps)
{
    PROJECTILE *probe = projectile_create(x0, y0, z0, x1, y1, z1);
    probe->probe_mode = 1;
    while (steps > 0)
    {
        if (x1 - 0x500 < probe->collision.x && probe->collision.x < x1 + 0x500 && y1 - 0x500 < probe->collision.y && probe->collision.y < y1 + 0x500 && z1 - 0x500 < probe->collision.z && probe->collision.z < z1 + 0x500)
            break;
        if (projectile_update(probe) != 0)
        {
            object_destroy(probe);
            return 1;
        }
        --steps;
    }
    object_destroy(probe);
    return 0;
}

/* Original: FUN_800A37C4. Animation callback 0x800A37C4..0x800A39C4, Mission-0 branch
 * DAT_800D3DA4 == 0. */
void mission_enemy_fire(MISSION_ENEMY_ACTOR *object)
{
    if (getenv("OA_MISSION_ENEMY_TRACE"))
    {
        static sint32 shots;
        if (shots < 8)
        {
            FILE *trace = fopen("mission_enemy_port.log", shots ? "a" : "w");
            if (trace)
            {
                fprintf(trace, "SHOT %d tick=%u object=%p type=%d dir=%d alt=%d xyz=%08x,%08x,%08x target=%08x,%08x,%08x\n", shots, g_frame_counter, object, (sint32)object->collision.object_type, (sint32)object->display_direction, (sint32)object->alternate_attack, (uint32)object->collision.x, (uint32)object->collision.y, (uint32)object->collision.z, (uint32)object->target_x, (uint32)object->target_y, (uint32)object->target_z);
                fclose(trace);
            }
            ++shots;
        }
    }
    sint32 direction = object->display_direction;
    sint32 z_offset = direction == 0 ? 0x100 : (direction == 2 ? -0x100 : 0);
    sint32 x_offset = direction == 1 ? 0x100 : (direction == 3 ? -0x100 : 0);
    sint32 target_y = object->target_y - random_range(0x1000);
    sint32 projectile_y = target_y - 0x2000;
    PROJECTILE *projectile;
    if (object->alternate_attack != 0)
        projectile_y = target_y;
    projectile = projectile_create(object->collision.x + x_offset * 0x10, object->collision.y + object->muzzle_y_offset, object->collision.z + z_offset * 2, object->target_x + random_range(0x2000) - 0x1000, projectile_y, object->target_z);
    projectile->scale = 0xc00;
    /* 800A38F4..800A3928: officer bullets travel at twice the common
     * projectile velocity (MIPS SLL, including wraparound semantics). */
    if (object->collision.object_type == 7)
    {
        projectile->motion[3] = (sint32)((uint32)projectile->motion[3] << 1);
        projectile->motion[4] = (sint32)((uint32)projectile->motion[4] << 1);
        projectile->motion[5] = (sint32)((uint32)projectile->motion[5] << 1);
    }
}

/* Original: FUN_800A2BD4. Direct translation of the type-0x21/type-0x23 execution paths through
 * 0x800A2BD4..0x800A3720. */
void mission_enemy_update(MISSION_ENEMY_ACTOR *object)
{
    sint32 old_x = object->collision.x, old_y = object->collision.y, old_z = object->collision.z;
    EFFECT *source = object->source_effect;
    EFFECT **waypoints = object->route_points;
    sint32 active;
    sint32 scale = object->collision.object_type == 0x1d ? 0x1400 : g_default_model_scale;
    sint32 destination_x, destination_z;
    sint32 direction, display_direction, frame_offset;
    if (getenv("OA_MISSION_ENEMY_STATE_TRACE"))
    {
        static sint32 count;
        if (count < 40)
        {
            sint16 route = object->route_index;
            EFFECT *waypoint = object->route_points[route];
            FILE *trace = fopen("mission_enemy_state_port.log", count ? "a" : "w");
            if (trace)
            {
                fprintf(trace, "STATE %d tick=%u object=%p xyz=%08x,%08x,%08x attack=%d secondary=%d timer=%d turn=%d route=%d/%d waypoint=%p dest=%08x,%08x velocity=%08x,%08x,%08x\n", count, g_frame_counter, object, (uint32)object->collision.x, (uint32)object->collision.y, (uint32)object->collision.z, (sint32)object->attack_active, (sint32)object->secondary_active, (sint32)object->attack_countdown, (sint32)object->turn_countdown, (sint32)route, (sint32)object->route_count, (void *)waypoint, (uint32)waypoint->x, (uint32)waypoint->z, (uint32)object->movement_line[0], (uint32)object->movement_line[1], (uint32)object->movement_line[2]);
                fclose(trace);
            }
            ++count;
        }
    }
    g_mission_enemy_update_count++;
    active = mission_enemy_update_visibility(&object->collision, source, object->collision.object_type, g_resource_clut_table[(uint32)object->render_resource >> 10]);
    if (active == 0)
        return;

    if (object->scale_transition != 0)
    {
        object->scale_transition = (sint16)(object->scale_transition - 2);
        scale = g_default_model_scale - object->scale_transition * 8;
        object->palette_offset = (sint16)(object->palette_offset + 2);
    }
    if (object->attack_countdown == 0 && object->secondary_active == 0)
    {
        sint32 blocked = projectile_test_path(object->collision.x, object->collision.y - 0x3000, object->collision.z, g_player_world_x, g_player_world_y - 0x3000, g_player_world_z, 0x1a);
        if (blocked == 0)
        {
            const sint32 *attack;
            sint32 selected = 0;
            if (object->special_attack_enabled == 0 || g_player_world_y - object->collision.y < 0x4001)
                attack = object->attack_animation;
            else
                attack = enemy_special_attack_animation;
            animation_start(&object->animation, attack);
            object->attack_active = 1;
            if (object->alternate_attack_chance != 0)
            {
                sint32 chance = object->alternate_attack_chance;
                if (chance == -1 || random_range(chance) == 0)
                    selected = 1;
                if (((PLAYER *)g_player)->update == player_prone_control_update && selected)
                    object->alternate_attack = 1;
                else
                    object->alternate_attack = 0;
            }
            object->attack_countdown = (sint16)(object->attack_delay + random_range(100));
        }
        else
            object->attack_countdown = object->attack_delay;
    }
    if (g_mission_ending != 0)
        object->attack_countdown = 999;
    if (object->attack_countdown != 0)
        object->attack_countdown = (sint16)(object->attack_countdown - 1);
    if (object->attack_countdown == 0x1e)
        object->turn_countdown = object->turn_attack_enabled ? 0x1f : 0;

    destination_x = waypoints[object->route_index]->x;
    destination_z = waypoints[object->route_index]->z;
    object->collision.y += object->vertical_velocity;
    object->vertical_velocity += 0x55;
    if (object->vertical_velocity > 0x600)
        object->vertical_velocity = 0x600;
    if (animation_get_next(&object->animation) == 0)
    {
        sint32 dx = destination_x - object->collision.x;
        sint32 dz = destination_z - object->collision.z;
        const sint32 *patrol = object->patrol_animation;
        animation_start(&object->animation, patrol);
        object->attack_active = 0;
        object->secondary_active = 0;
        if (dx < 0)
            dx += 0xfff;
        if (dz < 0)
            dz += 0xfff;
        if (object->scale_transition == 0)
            object->movement_direction = (sint16)(((fixed_angle_from_vector(dx >> 12, dz >> 12) + 0x40) & 0x3ff) >> 8);
    }
    if (object->attack_active == 0)
    {
        if (destination_x - 0x1000 < object->collision.x && object->collision.x < destination_x + 0x1000 && destination_z - 0x1000 < object->collision.z && object->collision.z < destination_z + 0x1000)
        {
            object->route_index = (sint16)(object->route_index + object->route_step);
            if (object->route_index == object->route_count - 1)
                object->route_step = -1;
            if (object->route_index == 0)
                object->route_step = 1;
            destination_x = waypoints[object->route_index]->x;
            destination_z = waypoints[object->route_index]->z;
            fixed_dda_initialize(object->collision.x, object->collision.y, object->collision.z, destination_x, object->collision.y, destination_z, object->movement_line);
            object->movement_line[3] *= object->movement_speed;
            object->movement_line[5] *= object->movement_speed;
            if (object->movement_slowed != 0)
            {
                object->movement_line[3] /= 2;
                object->movement_line[5] /= 2;
            }
            {
                sint32 dx = destination_x - object->collision.x;
                sint32 dz = destination_z - object->collision.z;
                if (dx < 0)
                    dx += 0xfff;
                if (dz < 0)
                    dz += 0xfff;
                object->movement_direction = (sint16)(((fixed_angle_from_vector(dx >> 12, dz >> 12) + 0x40) & 0x3ff) >> 8);
            }
        }
        if (object->scale_transition == 0)
            fixed_dda_advance(object->movement_line);
        {
            sint32 v = object->movement_line[0];
            if (v < 0)
                v += 0xff;
            object->collision.x = v >> 8;
        }
        {
            sint32 v = object->movement_line[2];
            if (v < 0)
                v += 0xff;
            object->collision.z = v >> 8;
        }
    }
    else
    {
        sint32 sector = ((angle_to_player(object->collision.x, object->collision.z, 1) + 0x40) & 0x3ff) >> 7;
        object->movement_direction = enemy_player_facing[sector];
        object->target_x = g_player_world_x;
        object->target_y = g_player_world_y;
        object->target_z = g_player_world_z;
    }

    direction = object->movement_direction;
    animation_update(&object->animation);
    frame_offset = object->animation.frame;
    display_direction = direction;
    if (object->attack_active == 0 && object->turn_countdown != 0)
    {
        if (display_direction == 0 && g_player_world_z < object->collision.z)
            display_direction = 2;
        if (display_direction == 1 && g_player_world_x < object->collision.x)
            display_direction = 3;
        if (display_direction == 2 && object->collision.z < g_player_world_x)
            display_direction = 0;
        if (display_direction == 3 && object->collision.x < g_player_world_x)
            display_direction = 1;
        if (animation_get_start(&object->animation) == object->patrol_animation && direction != display_direction)
            frame_offset = 7 - object->animation.frame;
        object->turn_countdown = (sint16)(object->turn_countdown - 1);
    }
    object->horizontal_flip = 1;
    object->display_direction = (sint16)display_direction;
    {
        const sint32 *frames = object->walk_frames;
        sint32 frame = frames[display_direction];
        if (object->attack_active != 0)
        {
            frames = object->attack_frames;
            frame = frames[display_direction];
            if (animation_get_start(&object->animation) == enemy_special_attack_animation)
            {
                frames = object->special_attack_frames;
                frame = frames[display_direction];
            }
        }
        if (object->secondary_active != 0)
        {
            frames = object->special_attack_frames;
            frame = frames[display_direction];
        }
        if (display_direction == 3)
            object->horizontal_flip = -1;
        player_collision_resolve(old_x, old_y, old_z, &object->collision.x, &object->collision.y, &object->collision.z, 0, &object->vertical_velocity, 0x10, 0x50, 5);
        if ((g_collision_flags & 2) != 0 && g_current_collision_result->step == 0)
            object->movement_line[0] = old_x << 8;
        if ((g_collision_flags & 4) != 0 && g_current_collision_result->step == 0)
            object->movement_line[2] = old_z << 8;
        if ((g_collision_flags & 6) != 0 && (g_collision_flags & 1) != 0 && g_dynamic_collision_hit == 0 && g_current_collision_result->step == 0)
        {
            object->vertical_velocity = -0x700;
            object->turn_countdown = 0;
            object->attack_countdown = 100;
        }
        if (((VRAM_SPRITE *)object->collision.frame_descriptor)->region_token != 0 && active != 2)
        {
            g_next_frame_object->light_delta = object->palette_offset;
            render_world_sprite(frame_offset + frame + object->render_resource, object->collision.x, object->collision.y - ((object->scale_transition + (object->scale_transition < 0 ? 7 : 0)) >> 3) * 0x100, object->collision.z, object->horizontal_flip, scale, scale, (POLY_FT4 *)object->collision.prim, 0, 0, (VRAM_SPRITE *)object->collision.frame_descriptor, 0);
            player_hit_flash_update(object);
            if (object->attack_active != 0)
            {
                object->attack_active = (sint16)(object->attack_active + 1);
                if (object->muzzle_flash_enabled != 0 && (object->animation.flags & 0x10) != 0)
                {
                    sint32 y_offset = object->muzzle_y_offset;
                    sint32 z_offset = display_direction == 0 ? 0x200 : (display_direction == 2 ? -0x200 : 0);
                    sint32 x_offset = display_direction == 1 ? 0x2000 : (display_direction == 3 ? -0x2000 : 0);
                    POLY_FT4 *flash = (POLY_FT4 *)(intptr)g_transient_prim_cursor;
                    sint32 extra = (display_direction == 0 || display_direction == 2) ? ((g_frame_counter & 0xff) << 2) : display_direction;
                    if (animation_get_start(&object->animation) == enemy_special_attack_animation)
                        y_offset = -0x1000;
                    g_next_frame_object->force_light = 1;
                    g_next_frame_object->light_delta = -0x30;
                    SetPolyFT4(flash);
                    SetSemiTrans(flash, 1);
                    render_world_sprite(((g_frame_counter >> 1) & 1) | 0x14800, object->collision.x + x_offset, object->collision.y + y_offset, object->collision.z + z_offset - 0x100, object->horizontal_flip, 0xa00, 0xa00, flash, 0, 0, 0, extra);
                    g_transient_prim_cursor += (sint32)sizeof(POLY_FT4);
                }
            }
        }
    }
    if (object->animation.flags == 1)
        object->attack_callback(object);
}

/* Direct translation of 0x800A798C..0x800A7A98. */
/* Original: FUN_800A798C. */
void *mortar_shell_impact(SPRITE *projectile)
{
    SPRITE *effect;
    sint32 sound;
    if (g_collision_surface_resource == g_stage_env->map_resource || g_collision_surface_resource == -1)
    {
        effect = surface_impact_create(projectile->collision.x, projectile->collision.y, projectile->collision.z, mortar_surface_impact_animation);
        sound = 0x24;
    }
    else
    {
        effect = world_sprite_create(projectile->collision.x, projectile->collision.y, projectile->collision.z, mortar_solid_impact_animation);
        sound = 9;
    }
    sound_play_positional(sound, 0, 0xa0, projectile->collision.x, projectile->collision.y, projectile->collision.z);
    object_destroy(projectile);
    effect->damage = 0x100;
    effect->scale_x = (uint16)(random_range(0x800) + 0x1800);
    effect->collision.receives_mask = 2;
    effect->collision.callback_14 = player_apply_damage;
    collision_box_set(effect, 0x80, 0x80, 0x80);
    player_particle_ring_create(effect->collision.x, effect->collision.y, effect->collision.z, 0x0c, 3);
    expl_flash_create(effect->collision.x, effect->collision.y - 0x4000, effect->collision.z - 0x100);
    return effect;
}

/* Direct translation of 0x800A77F8..0x800A7988. */
/* Original: FUN_800A77F8. */
static void *mortar_shell_spawn_timer(TIMED_CALLBACK *emitter)
{
    sint16 lifetime = emitter->lifetime;
    if (lifetime == 0x19)
    {
        sound_play_positional(0x25, 0, 0x96, emitter->collision.x, emitter->collision.y, emitter->collision.z);
        speech_random_request(10);
    }
    if (lifetime == 1)
    {
        SPRITE *projectile = world_sprite_create(emitter->collision.x + random_range(0x4000) - (emitter->callback_value_88 * 0x20 + 0x2000), ((emitter->collision.z - g_camera_world_z) * -0x8c) / 0x163 + g_camera_world_y, emitter->collision.z + random_range(0x4000) - (emitter->callback_value_8c * 0x20 + 0x2000), mortar_falling_animation);
        projectile->lifetime = 0x3c;
        projectile->scale_x = 0x2000;
        projectile->velocity_y = 0x800;
        projectile->velocity_x = emitter->callback_value_88;
        projectile->velocity_z = emitter->callback_value_8c;
        projectile->frame_callback = projectile_trail_emit;
        projectile->field_9e = 1;
        projectile->collision_callback = (FUNC_COLLISION_UPDATE)mortar_shell_impact;
        projectile->rotation_step_x = 0x18;
        projectile->damage = 0x100;
        projectile->collision.receives_mask = 2;
        projectile->collision.callback_14 = player_apply_damage;
        collision_box_set(projectile, 0x10, 0x10, 0x10);
        return projectile;
    }
    return 0;
}

/* Direct translation of 0x800A74A0..0x800A77F4. */
/* Original: FUN_800A74A0. */
void mortar_update(MORTAR_ACTOR *object)
{
    sint32 old_x = object->collision.x, old_y = object->collision.y, old_z = object->collision.z;
    sint32 visible = world_object_is_visible(old_x, old_y, old_z, 0x8000);
    sint32 velocity_x, velocity_z;
    VRAM_SPRITE *descriptor = &object->descriptor;
    if (!visible)
    {
        if (object->descriptor.region_token != 0)
            sprite_vram_defer_release(descriptor);
        object->collision.frame_descriptor = 0;
    }
    else if (object->descriptor.region_token == 0)
    {
        sprite_vram_allocate(descriptor, 0x40, 0x46, 1);
        object->collision.frame_descriptor = descriptor;
        object->descriptor.cached_resource = 0;
        object->descriptor.clut = g_resource_clut_table[1];
    }
    object->collision.y += 0x400;
    velocity_x = object->target_x - old_x;
    if (velocity_x < 0)
        velocity_x += 0x1fff;
    velocity_z = object->target_z - old_z;
    if (velocity_z < 0)
        velocity_z += 0x1fff;
    fixed_angle_from_vector(velocity_x >> 13, velocity_z >> 13);
    velocity_x = ((velocity_x >> 13) << 4) / 3;
    velocity_z = ((velocity_z >> 13) << 6) / 3;
    if (object->fire_countdown == 0)
    {
        animation_start(&object->animation, mortar_fire_animation);
        animation_set_owner(&object->animation, object);
        object->fire_countdown = (sint16)(random_range(0x1e) + 0x3c);
    }
    else
        object->fire_countdown--;
    object->animation.flags = 0;
    animation_update(&object->animation);
    if (object->animation.flags != 0)
    {
        if (visible)
        {
            SPRITE *projectile = world_sprite_create(old_x, old_y - 0x3000, old_z - 0x400, mortar_falling_animation);
            projectile->lifetime = 0x3c;
            projectile->scale_x = 0x2000;
            projectile->velocity_y = -0x600;
            projectile->frame_callback = projectile_trail_emit;
            projectile->field_9e = 1;
            projectile->collision.receives_mask = 2;
            projectile->velocity_x = velocity_x;
            projectile->velocity_z = velocity_z;
            projectile->collision.callback_14 = player_apply_damage;
            collision_box_set(projectile, 0x10, 0x10, 0x10);
        }
        {
            EFFECT *destination = object->target_effect;
            sint32 dx = destination->x - g_player_world_x;
            if (dx < 0)
                dx = -dx;
            sint32 dz = destination->z - g_player_world_z;
            if (dz < 0)
                dz = -dz;
            if ((dx + dz) / 2 < 0xc800)
            {
                TIMED_CALLBACK *emitter = (TIMED_CALLBACK *)timed_callback_create((void *(*)(void *))mortar_shell_spawn_timer, object->target_x, old_y, object->target_z, 0x55, 0);
                emitter->callback_value_88 = velocity_x;
                emitter->callback_value_8c = velocity_z;
            }
        }
    }
    player_collision_resolve(old_x, old_y, old_z, &object->collision.x, &object->collision.y, &object->collision.z, 0, 0, 0x34, 0x50, 5);
    if (visible)
    {
        render_world_sprite(object->animation.frame, object->collision.x, object->collision.y, object->collision.z, 0, g_default_model_scale, g_default_model_scale, (POLY_FT4 *)object->collision.prim, 0, 0, (VRAM_SPRITE *)object->collision.frame_descriptor, 0);
        player_hit_flash_update(object);
    }
}

/* Direct translation of 0x800A7378..0x800A749C. */
/* Original: FUN_800A7378. */
void mortar_create(EFFECT *source)
{
    MORTAR_ACTOR *object = (MORTAR_ACTOR *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)mortar_update);
    EFFECT *destination = 0;
    sint16 route = (sint16)source->values[0];
    SetPolyFT4((POLY_FT4 *)object->collision.prim);
    SetShadeTex((POLY_FT4 *)object->collision.prim, 0);
    object->collision.x = source->x;
    object->collision.y = source->y;
    object->collision.z = source->z;
    object->collision.receives_mask = 0xc1;
    object->collision.callback_18 = (FUNC_COLLISION_CALLBACK)destroyable_object_damage_and_reward;
    object->health = 0x14;
    animation_set_owner(&object->animation, object);
    object->collision.object_type = 0x16;
    collision_box_set(object, 0x40, 0x40, 0x10);
    source->type = 0;
    for (;;)
    {
        destination = effect_find_next(0x1b, destination);
        if (destination == 0)
            return;
        if ((sint16)destination->values[0] == route)
            break;
        destination++;
    }
    object->target_x = destination->x;
    object->target_z = destination->z;
    object->animation.frame = 0x400;
    object->target_effect = destination;
    object->fire_countdown = 1;
}

/* Direct collision callback 0x800A3754..0x800A37C0. */
/* Original: FUN_800A3754. */
void mission_enemy_damage(MISSION_ENEMY_ACTOR *object, void *source)
{
    if (object->scale_transition != 0)
        return;
    destroyable_object_damage_and_reward(object, source);
    if (object->hit_reaction_enabled == 0)
        return;
    object->turn_countdown = 0x14;
    if (object->attack_active == 0 && random_range(2) == 0)
        object->attack_countdown = 0;
}

/* Exact stage-17 attack callback 0x800A1F9C..0x800A2004. */
/* Original: FUN_800A1F9C. */
void airfield_enemy_fire(MISSION_ENEMY_ACTOR *object)
{
    PROJECTILE *projectile = projectile_create(object->collision.x, object->collision.y - 0x3000, object->collision.z, object->target_x, object->target_y, object->target_z);
    projectile->damage = 0x80;
    projectile->floor_callback = (FUNC_COLLISION_UPDATE)explosive_projectile_trail_update;
    projectile->impact_callback = (FUNC_COLLISION_UPDATE)explosive_projectile_impact;
    projectile->collision.object_type = 0;
#ifdef XPORT_NATIVE
    {
        const char *trace = getenv("OA_AIRFIELD_TRACE");
        if (trace && *trace)
        {
            FILE *file = fopen("../status/airfield-native.log", "a");
            if (file)
            {
                fprintf(file, "AIRFIELD_NATIVE_ATTACK xyz=%d,%d,%d velocity=%d,%d,%d type=%d\n", projectile->collision.x, projectile->collision.y, projectile->collision.z, projectile->motion[3], projectile->motion[4], projectile->motion[5], projectile->collision.object_type);
                fclose(file);
            }
        }
    }
#endif
}

/* Exact type-0x49 descriptor initializer 0x800A2004..0x800A2088. */
/* Original: FUN_800A2004. */
void airfield_enemy_configure(MISSION_ENEMY_ACTOR *object)
{
    object->health = 5;
    object->walk_frames = airfield_enemy_walk_frames;
    object->attack_frames = airfield_enemy_alert_frames;
    object->movement_speed = 2;
    object->attack_animation = airfield_enemy_attack_animation;
    object->patrol_animation = enemy_patrol_animation;
    object->muzzle_y_offset = -0x2600;
    object->alternate_attack_chance = 2;
    object->attack_callback = (FUNC_COLLISION_UPDATE)airfield_enemy_fire;
    object->attack_delay = 0xc8;
    object->render_resource = 0x27c00;
    object->muzzle_flash_enabled = 0;
    object->attack_countdown = 0;
    object->collision.object_type = 0x49;
}

/* Direct translation of 0x800A20F8..0x800A2194. */
/* Original: FUN_800A20F8. */
sint32 route_waypoints_collect(sint16 route, sint16 index_bias, EFFECT **waypoints)
{
    EFFECT *effect = 0;
    sint16 count = 0;
    while ((effect = effect_find_next(0x1e, effect)) != 0)
    {
        if ((sint16)effect->values[0] == route)
        {
            count = (sint16)(count + 1);
            waypoints[(sint16)effect->values[1] + index_bias] = effect;
        }
        effect++;
    }
    return count;
}

/* Original: FUN_800A2198. Recovered paths of 0x800A2198..0x800A2BD0: officer 7, enemy types
 * 0x21/0x23/0x49 and generators 0x27/0x44. Other type branches remain WIP.
 * Officer proof: status/gyro-officers-regression.md. */
MISSION_ENEMY_ACTOR *mission_enemy_create(EFFECT *source)
{
    sint16 source_type = (sint16)source->type;
    sint16 object_type = source_type;
    sint16 route;
    sint16 route_count_bias;
    sint32 route_index_bias;
    MISSION_ENEMY_ACTOR *object;

#ifdef XPORT_NATIVE
    if (source_type == 0x49 && g_stage_index == 17 && source == g_effects + 9)
    {
        const char *trace = getenv("OA_AIRFIELD_TRACE");
        if (trace && *trace)
        {
            FILE *file = fopen("../status/airfield-native.log", "w");
            if (file)
            {
                fprintf(file, "AIRFIELD_NATIVE_HANDLER type=%d route=%d xyz=%d,%d,%d\n", source_type, (sint16)source->values[0], source->x, source->y, source->z);
                fclose(file);
            }
        }
    }
#endif

    if (g_mission_enemy_update_count > 5)
        speech_random_request(5);
    if (source_type == 0x27)
    {
        if (source->x - 0x2000 < g_player_world_x && g_player_world_x < source->x + 0x2000 && g_player_world_y < source->y + 0x3800 && source->y - 0x5000 < g_player_world_y && source->z - 0x100 < g_player_world_z)
            ((PLAYER *)g_player)->z = source->z - 0x100;
    }
    if (source_type == 0x27 || source_type == 0x44)
    {
        sint32 mask = 0x40;
        sint32 shifts = (sint16)source->values[5];
        /* 0x800A2284..0x800A2298: these periodic generators are disabled
         * when the difficulty/state value is 6 or greater. */
        if (g_mission_enemy_update_count >= 6)
            return 0;
        while (shifts > 0)
        {
            mask <<= 1;
            --shifts;
        }
        if ((g_frame_counter & (uint32)(mask - 1)) != 0)
            return 0;
        if ((sint16)source->values[3] != 0)
        {
            source->values[3] = (uint16)((sint16)source->values[3] - 1);
            if (source->values[3] == 0)
                source->type = 0;
        }
    }

    object = (MISSION_ENEMY_ACTOR *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)mission_enemy_update);
    SetPolyFT4((POLY_FT4 *)object->collision.prim);
    SetShadeTex((POLY_FT4 *)object->collision.prim, 0);
    object->collision.y = source->y;
    if (source_type == 0x27 || source_type == 0x44)
    {
        object->collision.x = source->x;
        object->collision.z = source->z + 0x1000;
        object_type = (sint16)source->values[0];
        if (object_type == 0)
            object_type = (sint16)source->values[4];
        object->collision.y = source->y + 0x2000;
    }
    object->collision.object_type = object_type;
    object->collision.frame_descriptor = object->descriptor;
    object->collision.receives_mask = 0xc1;
    if (object_type == 0x66 || object_type == 0x7e || object_type == 0x92)
        object->collision.receives_mask = 0x41;
    object->collision.callback_18 = (FUNC_COLLISION_CALLBACK)mission_enemy_damage;
    animation_set_owner(&object->animation, object);
    collision_box_set(object, 0x40, 0x40, 0x10);

    if (source_type == 0x27 || source_type == 0x44)
    {
        route = (sint16)source->values[1];
        if (route != (sint16)source->values[2])
            route = (sint16)(route + random_range((sint16)source->values[2] - route));
        route_count_bias = 0;
        route_index_bias = -1;
    }
    else
    {
        route = (sint16)source->values[0];
        route_count_bias = 1;
        route_index_bias = 0;
        object->route_points[0] = source;
        object->source_effect = source;
        source->type = 0;
    }
    object->route_count = (sint16)(route_count_bias + route_waypoints_collect(route, (sint16)route_index_bias, object->route_points));
    object->route_step = 1;
    object->attack_countdown = (sint16)random_range(100);

    if (source_type == 0x44)
    {
        EFFECT **waypoints = object->route_points;
        sint32 minimum_x = waypoints[0]->x;
        sint32 maximum_x = minimum_x;
        sint32 index;
        sint32 depth = (source->z + 0x1000) - g_camera_world_z;
        sint32 right = (depth * 0xc0) / 0x140 + g_camera_world_x;
        sint32 left = (depth * -0xc0) / 0x140 + g_camera_world_x;
        g_shared_scratch_value = 0;
        for (index = 0; index < object->route_count; index++)
        {
            sint32 x = waypoints[index]->x;
            if (x < minimum_x)
                minimum_x = x;
            if (x > maximum_x)
                maximum_x = x;
            g_shared_scratch_value = index + 1;
        }
        object->collision.z = source->z + 0x1000;
        if (random_range(1) == 0)
            object->collision.x = maximum_x < right ? left : right;
        else
            object->collision.x = left < minimum_x ? right : left;
        if (object->collision.x < minimum_x || maximum_x < object->collision.x)
        {
            object_destroy(object);
            return 0;
        }
    }

    if (object_type == 0x21)
    {
        object->health = 0x12;
        object->walk_frames = shack_enemy_walk_frames;
        object->attack_frames = shack_enemy_attack_frames;
        object->special_attack_frames = shack_enemy_high_attack_frames;
        object->secondary_frames = shack_enemy_high_attack_frames;
        object->render_resource = 0x1f000;
        object->alternate_attack_chance = -1;
        object->movement_speed = 1;
        object->attack_animation = shack_enemy_attack_animation;
        object->patrol_animation = enemy_patrol_animation;
        object->muzzle_y_offset = -0x3400;
        object->special_attack_enabled = 1;
        object->turn_attack_enabled = 1;
        object->hit_reaction_enabled = 1;
        object->muzzle_flash_enabled = 1;
        object->attack_delay = 100;
    }
    if (object_type == 0x23)
    {
        object->health = 5;
        object->walk_frames = mission0_enemy_walk_frames;
        object->attack_frames = mission0_enemy_alert_frames;
        object->movement_speed = 2;
        object->attack_animation = mission0_enemy_attack_animation;
        object->patrol_animation = enemy_patrol_animation;
        object->muzzle_y_offset = -0x2600;
        object->alternate_attack_chance = 2;
        object->muzzle_flash_enabled = 1;
        object->render_resource = 0x13000;
        object->attack_delay = 100;
    }
    if (object_type == 0x49)
        airfield_enemy_configure(object);

    /* PAL 800A29B8..800A2A44: officer, including byte/halfword widths.
     * Its bullets are emitted by the attack script's 800A37C4 callback,
     * not the type-49 explosive callback at object+1B8. */
    if (object_type == 7)
    {
        object->health = 0x19;
        object->walk_frames = officer_walk_frames;
        object->attack_frames = officer_attack_frames;
        object->movement_speed = 3;
        object->alternate_attack_chance = -1;
        object->patrol_animation = officer_patrol_animation;
        object->attack_animation = officer_attack_animation;
        object->muzzle_y_offset = -0x3200;
        object->render_resource = 0x15c00;
        object->attack_delay = 100;
        collision_box_set(object, 0x40, 0x50, 0x14);
        object->muzzle_flash_enabled = 1;
    }

    if (source_type == 0x27)
    {
        EFFECT *waypoint = object->route_points[0];
        object->scale_transition = 0x80;
        object->palette_offset = -0x80;
        object->attack_countdown = 0x3c;
        fixed_dda_initialize(object->collision.x, object->collision.y, object->collision.z, waypoint->x, object->collision.y, waypoint->z, object->movement_line);
        object->movement_direction = 2;
        object->movement_line[3] *= object->movement_speed;
        object->movement_line[5] *= object->movement_speed;
        object->collision.x += (random_range(8) - 4) * 0x100;
    }
    if (source_type == 0x44)
    {
        EFFECT *waypoint = object->route_points[0];
        fixed_dda_initialize(object->collision.x, object->collision.y, object->collision.z, waypoint->x, object->collision.y, waypoint->z, object->movement_line);
        object->movement_line[3] *= object->movement_speed;
        object->movement_line[5] *= object->movement_speed;
    }
    if (source_type != 0x27 && source_type != 0x44)
    {
        EFFECT *waypoint = object->route_points[0];
        object->collision.x = waypoint->x;
        object->collision.z = waypoint->z;
    }
#ifdef XPORT_NATIVE
    if (object_type == 0x49 && g_stage_index == 17 && source == g_effects + 9)
    {
        const char *trace = getenv("OA_AIRFIELD_TRACE");
        if (trace && *trace)
        {
            FILE *file = fopen("../status/airfield-native.log", "a");
            if (file)
            {
                fprintf(file, "AIRFIELD_NATIVE_CTOR type=%d health=%d speed=%d range=%d route_count=%d xyz=%d,%d,%d\n", object->collision.object_type, object->attack_delay, object->movement_speed, object->render_resource, object->route_count, object->collision.x, object->collision.y, object->collision.z);
                fclose(file);
            }
            airfield_enemy_fire(object);
        }
    }
#endif
    return object;
}

/* Direct translation of 0x800A912C..0x800A92FC. */
/* Original: FUN_800A912C. */
void drop_range_update(MISSION_DROP_RANGE *object)
{
    PLAYER *player = (PLAYER *)g_player;
    SPRITE *sprite;
    VRAM_SPRITE *descriptor;
    if (player->grounded != 0)
        g_hq_world_map_active = 0;
    if (player->update == player_ledge_control_update || player->update == player_checkpoint_recovery_update || player->health <= 0)
        return;
    if (g_player_world_x < object->collision.x || g_player_world_x > object->collision.box_x || g_player_world_z < object->collision.box_z || g_player_world_z > object->collision.z || g_player_world_y < object->collision.y || g_player_world_y > object->collision.box_y)
        return;
    player_apply_damage(0, player);
    g_hq_world_map_active = 1;
    if (player->health == 0)
        return;
    player_checkpoint_recovery_begin(player);
    sprite = world_sprite_create(g_player_world_x, g_player_world_y, g_player_world_z, (const sint32 *)1);
    sprite->velocity_y = 0x600;
    sprite->acceleration_y = 0x20;
    sprite->animation.delay = 0xc8;
    sprite->owns_resource = 1;
    sprite->animation.frame = player->animation.frame;
    descriptor = (VRAM_SPRITE *)runtime_heap_allocate(sizeof(*descriptor));
    sprite_vram_allocate(descriptor, 0x48, 0x50, 1);
    descriptor->clut = g_player_sprite_clut;
    sprite->collision.frame_descriptor = descriptor;
    player->recovery_delay = 0x14;
}

/* Direct translation of 0x800A8FD4..0x800A9128. */
/* Original: FUN_800A8FD4. */
void drop_range_create(EFFECT *first)
{
    EFFECT *second;
    MISSION_DROP_RANGE *object;
    char message[48];
    first->type = 0;
    first->z += 0x4000;
    second = effect_find_next(0x45, first + 1);
    while (second != 0 && (sint16)second->values[0] != (sint16)first->values[0])
        second = effect_find_next(0x45, second + 1);
    if (second == 0)
    {
        sprintf(message, "DROPRANGE FX %d %d,%d", (sint16)first->values[0], first->x / 0x4000, first->y / 0x100);
        fatal_error(message);
        return;
    }
    second->type = 0;
    if (first->z < second->z)
    {
        EFFECT *swap = first;
        first = second;
        second = swap;
    }
    object = (MISSION_DROP_RANGE *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)drop_range_update);
    object->collision.x = first->x - 0x2000;
    object->collision.box_x = second->x + 0x2000;
    object->collision.y = first->y;
    object->collision.box_y = second->y + 0x4000;
    object->collision.z = first->z + 0x2000;
    object->collision.box_z = second->z - 0x1e00;
}

/* Exact PAL 0x8009DD14..0x8009DDC4: Air Raid red-flare timeline. */
/* Original: FUN_8009DD14. */
static void air_raid_sequence_update(AIR_RAID_SEQUENCE *object)
{
    sint16 frame = (sint16)(object->frame + 1);
    object->frame = frame;
    if (frame == 0xb4)
        object->second_sound_handle = (sint16)sound_play_nonpositional(0x33, -1, 0x7f);
    if (frame == 0x1e0)
        v2_expl_sequence_begin();
    if (frame == 0x200)
        sound_voice_stop(&object->first_sound_handle);
    if (frame == 0x258)
    {
        sound_voice_stop(&object->second_sound_handle);
        object_destroy(object);
        destructible_building_damage(object->building, 0);
    }
}

/* Exact PAL 0x8009DC9C..0x8009DD14: starts the Air Raid red-flare
 * countdown.  The original receives the area coordinates in a0-a2 but only
 * retains the matched building passed in a3. */
/* Original: FUN_8009DC9C. */
void air_raid_sequence_create(sint32 x, sint32 y, sint32 z, BUILDING *building)
{
    AIR_RAID_SEQUENCE *object;
    object = (AIR_RAID_SEQUENCE *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)air_raid_sequence_update);
    object->first_sound_handle = (sint16)sound_play_nonpositional(0x32, -1, 0x7f);
    object->building = building;
    mission_text_message_create((const char *)player_assets_executable_pointer(0x80082784u));
    mission_text_message_create((const char *)player_assets_executable_pointer(0x80082788u));
}

/* Direct translation of 0x8009D380..0x8009D698, including the stage-15
 * type-0x60 branch. */
/* Original: FUN_8009D380. */
void flare_area_update(MISSION_FLARE_AREA *object)
{
    EFFECT *source = object->source_effect;
    sint16 type = object->collision.object_type;
    sint16 gate = 0;
    if (g_scuba_stage_active != 0)
    {
        object->collision.y = g_player_world_y;
        object->collision.box_y = g_player_world_y;
    }
    if (g_player_world_x < object->collision.x || g_player_world_x > object->collision.box_x || g_player_world_z < object->collision.box_z || g_player_world_z > object->collision.z || g_player_world_y < object->collision.y || g_player_world_y > object->collision.box_y)
    {
        object->activation_ticks = 0;
        g_action_trigger_states[(sint16)source->values[0]] = 0;
        object->hint_delay = 500;
        return;
    }
    object->hint_delay += 1;
    if (g_action_trigger_states[(sint16)source->values[0]] == 0 && object->hint_delay > 0x30)
    {
        MISSION_TEXT_MESSAGE *message;
        object->hint_delay = 0;
        if (type == 0x60)
        {
            message = mission_text_message_create((const char *)player_assets_executable_pointer(0x80082768u));
            if (message != 0)
                message->lifetime = 0x2e;
        }
        if (type == 0x4c)
        {
            message = mission_text_message_create((const char *)player_assets_executable_pointer(0x8008276cu));
            if (message != 0)
                message->lifetime = 0x2e;
        }
    }
    if (g_scuba_stage_active != 0)
        gate = object_count_by_type(0x76);
    if (type == 0x7c)
        gate = 1;
    if ((animation_get_start(&((PLAYER *)g_player)->animation) == player_assets_executable_address(0x800c96b4u) && animation_get_next(&((PLAYER *)g_player)->animation) != 0) || gate != 0)
    {
        sint16 duration = g_scuba_stage_active == 0 ? 0x5a : 0x3c;
        object->activation_ticks += 1;
        if (object->activation_ticks > duration || type == 0x7c)
        {
            if (type == 0x4c || type == 0x7c)
            {
                sint32 counts = mission_objective_counts();
                if (g_primary_objective_count - 1 <= (counts >> 16))
                    g_action_trigger_states[(sint16)source->values[0]] = 1;
            }
            if (type == 0x60)
            {
                BUILDING *building = 0;
                for (;;)
                {
                    building = (BUILDING *)object_find_next_by_type(building, 0x28);
                    if (building == 0)
                        fatal_error("RED FLARE BUILDING!");
                    if (building->source_effect->values[0] == (sint16)source->values[1])
                        break;
                }
                air_raid_sequence_create(object->collision.x, object->collision.y, object->collision.z, building);
                object_destroy(object);
            }
        }
    }
}

/* Direct translation of 0x8009D20C..0x8009D37C. */
/* Original: FUN_8009D20C. */
void flare_area_create(EFFECT *first)
{
    sint16 type = (sint16)first->type;
    EFFECT *second;
    MISSION_FLARE_AREA *object;
    char message[48];
    first->type = 0;
    first->z += 0x4000;
    second = effect_find_next(type, first + 1);
    while (second != 0 && (sint16)second->values[0] != (sint16)first->values[0])
        second = effect_find_next(type, second + 1);
    if (second == 0)
    {
        sprintf(message, "FLAREAREA FX %d %d,%d", (sint16)first->values[0], first->x / 0x4000, first->y / 0x100);
        fatal_error(message);
        return;
    }
    second->type = 0;
    if (first->z < second->z)
    {
        EFFECT *swap = first;
        first = second;
        second = swap;
    }
    object = (MISSION_FLARE_AREA *)object_create(sizeof(*object), (FUNC_COLLISION_UPDATE)flare_area_update);
    object->source_effect = first;
    object->collision.object_type = type;
    object->collision.x = first->x - 0x2000;
    object->collision.box_x = second->x + 0x2000;
    object->collision.y = first->y - 0x8000;
    object->collision.box_y = second->y + 0x4000;
    object->collision.z = first->z + 0x2000;
    object->collision.box_z = second->z - 0x2000;
}

/* Direct translation of 0x8009D698..0x8009D780. */
/* Original: FUN_8009D698. */
static void mission_objective_complete(sint16 primary, sint16 secondary)
{
    char text[32];
    SPRITE *effect;
    if (g_primary_objective_states[primary] == 0 && primary != 0)
    {
        g_primary_objective_states[primary] = 1;
        sprintf(text, (const char *)player_assets_executable_pointer(0x80082774u), integer_to_text(primary));
    }
    if (g_secondary_objective_states[secondary] == 0 && secondary != 0)
    {
        g_secondary_objective_states[secondary] = 1;
        sprintf(text, (const char *)player_assets_executable_pointer(0x80082778u), integer_to_text(secondary));
    }
    mission_text_message_create(text);
    effect = world_sprite_create(g_player_world_x, g_player_world_y, g_player_world_z, mission_complete_animation);
    effect->render_kind = 999;
}

static uint16 mission_timer_value(sint32 threshold)
{
    if (threshold == 32000)
        return 0;
    return (uint16)g_mission_timer_display->elapsed_seconds;
}

/* Direct translation of 0x8009D820..0x8009DC98. */
/* Original: FUN_8009D820. */
sint32 mission_objective_script_update(sint32 script_address)
{
    const sint16 *script = (const sint16 *)(intptr)script_address;
    sint32 threshold = 32000;
    sint16 primary = 0, secondary = 0;
    sint32 primary_count = 0, secondary_count = 0;
    char text[32];
    for (;;)
    {
        sint16 opcode = *script++;
        uint16 timer;
        if (opcode == -2)
        {
            primary = *script++;
            secondary = 0;
            primary_count++;
            continue;
        }
        if (opcode == -3)
        {
            secondary = *script++;
            primary = 0;
            secondary_count++;
            continue;
        }
        timer = mission_timer_value(threshold);
        if (threshold < (sint32)timer)
        {
            if (g_primary_objective_states[primary] == 0 && primary != 0)
            {
                sprintf(text, (const char *)player_assets_executable_pointer(0x8008277cu), primary);
                g_primary_objective_states[primary] = 2;
                mission_text_message_create(text);
                player_death_begin();
            }
            if (g_secondary_objective_states[secondary] == 0 && secondary != 0)
            {
                sprintf(text, (const char *)player_assets_executable_pointer(0x80082780u), secondary);
                g_secondary_objective_states[secondary] = 2;
                mission_text_message_create(text);
            }
        }
        if (opcode == -4)
        {
            sint16 mode = *script++;
            sint32 current = 0, total = 0;
            if ((primary != 0 && g_primary_objective_states[primary] != 0) || (secondary != 0 && g_secondary_objective_states[secondary] != 0))
                continue;
            if (mode == 0)
            {
                current = g_primary_target_current_count;
                total = g_primary_target_total_count;
            }
            if (mode == 1)
            {
                current = g_secondary_target_current_count;
                total = g_secondary_target_total_count;
            }
            timer = mission_timer_value(threshold);
            if (current == total && threshold >= (sint32)timer)
                mission_objective_complete(primary, secondary);
            continue;
        }
        if (opcode == -5)
        {
            sint16 index = *script++;
            if (primary != 0)
                g_primary_action_objective_present = 1;
            timer = mission_timer_value(threshold);
            if (g_action_trigger_states[index] != 0 && threshold >= (sint32)timer)
            {
                g_primary_objective_states[primary] = 1;
                g_secondary_objective_states[secondary] = 1;
            }
            else
            {
                g_primary_objective_states[primary] = 0;
                g_secondary_objective_states[secondary] = 0;
            }
            continue;
        }
        if (opcode == -6)
            return primary_count * 0x10000 + secondary_count;
        if (opcode == -7)
        {
            threshold = *script++;
            g_mission_timer_visible = 1;
            continue;
        }
        if (opcode == -8)
        {
            threshold = 32000;
            continue;
        }
        if (opcode == -10)
        {
            sint16 index = *script++;
            if ((primary == 0 || g_primary_objective_states[primary] == 0) && (secondary == 0 || g_secondary_objective_states[secondary] == 0) && g_objective_counts[index] != 0)
                mission_objective_complete(primary, secondary);
            continue;
        }
        if (opcode == -12)
        {
            sint16 index = *script++;
            if ((primary == 0 || g_primary_objective_states[primary] == 0) && (secondary == 0 || g_secondary_objective_states[secondary] == 0) && g_objective_counts[index] == 0)
                mission_objective_complete(primary, secondary);
            continue;
        }
        if (opcode == -13)
        {
            sint16 index = *script++;
            sint16 value = *script++;
            if ((primary == 0 || g_primary_objective_states[primary] == 0) && (secondary == 0 || g_secondary_objective_states[secondary] == 0) && value < (sint32)g_objective_counts[index])
                mission_objective_complete(primary, secondary);
        }
    }
}

/* Direct translation of 0x800A0610..0x800A0794. */
/* Original: FUN_800A0690. */
static void mission_timer_display_update(MISSION_TIMER_DISPLAY *object)
{
    char *text = object->text;
    uint32 elapsed = g_frame_counter / 59;
    *text = 0;
    object->elapsed_seconds = (sint16)elapsed;
    if (g_mission_timer_visible != 0)
    {
        if (elapsed / 60 < 10)
            strcat(text, "0");
        strcat(text, integer_to_text((sint32)(elapsed / 60)));
        strcat(text, ":");
        if (elapsed % 60 < 10)
            strcat(text, "0");
        strcat(text, integer_to_text((sint32)(elapsed % 60)));
        g_text_color_index = 4;
        text_render(text, object->x, object->y);
    }
}

/* Original: FUN_800A0610. */
MISSION_TIMER_DISPLAY *mission_timer_display_create(sint32 x, sint32 y, sint32 z)
{
    MISSION_TIMER_DISPLAY *object = (MISSION_TIMER_DISPLAY *)runtime_heap_allocate(sizeof(*object));
    object->update = (FUNC_COLLISION_UPDATE)mission_timer_display_update;
    linked_list_append(g_object_list, object);
    object->x = x;
    object->y = y;
    object->z = z;
    object->field_7c = 0;
    return object;
}

/* Direct translation of 0x800A087C..0x800A092C. */
/* Original: FUN_800A087C. */
void hud_bar_initialize(MISSION_HUD_BAR *hud, sint32 x, sint32 y, sint32 width, sint32 maximum)
{
    POLY_G4 *fill = &hud->fill;
    POLY_F4 *border = &hud->border;
    hud->x = x;
    hud->y = y + 0x40;
    hud->width = width;
    hud->maximum = maximum + 1;
    SetPolyG4(fill);
    SetPolyF4(border);
    border->x0 = (sint16)(x - 1);
    border->y0 = (sint16)(y + 0x3f);
    border->x1 = (sint16)(x + width);
    border->y1 = (sint16)(y + 0x3f);
    border->x2 = (sint16)(x - 1);
    border->y2 = (sint16)(y + 0x47);
    border->x3 = (sint16)(x + width);
    border->y3 = (sint16)(y + 0x47);
    border->r0 = border->g0 = border->b0 = 0;
}

/* Direct translation of 0x800A0930..0x800A0BEC. */
/* Original: FUN_800A0930. */
void hud_bar_render(MISSION_HUD_BAR *hud, sint32 amount, sint32 unused, sint32 zero_width)
{
    POLY_G4 *fill = &hud->fill;
    POLY_F4 *border = &hud->border;
    sint32 maximum = hud->maximum;
    sint32 width = hud->width;
    sint32 visible_width = zero_width;
    if (maximum < amount)
        amount = maximum;
    if (amount != 0)
    {
        sint32 ratio = (maximum << 16) / amount;
        sint32 empty_width = (width << 16) / ratio;
        sint32 full_ratio, empty_ratio;
        if (empty_width == 0)
            empty_width = 1;
        full_ratio = (width << 16) / empty_width;
        empty_ratio = (width << 16) / (width - empty_width);
        fill->r0 = fill->r1 = fill->r2 = fill->r3 = (uint8)(0xff0000 / empty_ratio);
        fill->g0 = fill->g1 = fill->g2 = fill->g3 = (uint8)(0xff0000 / full_ratio);
        visible_width = empty_width;
    }
    fill->x0 = fill->x2 = (sint16)hud->x;
    fill->x1 = fill->x3 = (sint16)(hud->x + visible_width);
    fill->y0 = fill->y1 = (sint16)hud->y;
    fill->y2 = fill->y3 = (sint16)(hud->y + 6);
    if (amount != 0)
    {
        memcpy(g_gpu_packet_cursor, fill, sizeof(*fill));
        /* The PAL OT applies DR_OFFSET(160,64) before these screen-space
         * packets.  Native AddPrim records that GPU state per packet. */
        psx_set_prim_screen_offset(160, 64);
        AddPrim(g_current_render_frame->ot, g_gpu_packet_cursor);
        g_gpu_packet_cursor += sizeof(*fill);
    }
    memcpy(g_gpu_packet_cursor, border, sizeof(*border));
    psx_set_prim_screen_offset(160, 64);
    AddPrim(g_current_render_frame->ot, g_gpu_packet_cursor);
    g_gpu_packet_cursor += sizeof(*border);
}

/* Exact 0x800A0C18..0x800A0FF0 target-indicator branch. */
static void draw_target_indicator(void)
{
    MODEL_NODE node;
    COLLISION *target = (COLLISION *)object_find_next_by_type(0, 4);
    sint32 line[6], rotation_x, rotation_y;
    sint32 target_depth = g_camera_world_z + 0x12c00;
    sint32 denominator = target_depth - g_camera_world_z;
    sint32 offset_x, offset_y;
    MATRIX identity;
    rotation_x = rotation_y = (sint32)((g_frame_counter & 0x7f) << 5);
    if (target)
    {
        sint32 x, z, horizontal, y;
        fixed_dda_initialize(g_player_world_x, g_player_world_y, g_player_world_z, target->x, target->y, target->z, line);
        x = div_2048_trunc(line[3]);
        z = div_2048_trunc(line[5]);
        rotation_y = fixed_angle_from_vector(x, z) << 2;
        x = line[3] < 0 ? -line[3] : line[3];
        z = line[5] < 0 ? -line[5] : line[5];
        horizontal = x < z ? z + x / 2 : x + z / 2;
        y = div_2048_trunc(line[4]);
        horizontal = div_2048_trunc(horizontal);
        if (horizontal < 0)
            horizontal = -horizontal;
        rotation_x = (-fixed_angle_from_vector(y, horizontal) << 2) & 0xfff;
    }
    memset(&node, 0, sizeof(node));
    node.rotation_x = (sint16)rotation_x;
    node.rotation_y = (sint16)rotation_y;
    node.rotation_z = 0;
    node.translation_x = g_player_world_x - g_camera_world_x;
    node.translation_y = g_player_world_y - g_camera_world_y;
    node.translation_z = denominator;
    node.model_id = g_target_indicator_model_id;
    g_model_render_frame = 0;
    model_render_begin();
    g_render_depth_bucket = 0;
    g_current_model_world_z = target_depth;
    memset(&identity, 0, sizeof(identity));
    identity.m[0][0] = identity.m[1][1] = identity.m[2][2] = 0x1000;
    offset_x = 160 - 0x28 - (g_player_world_x - g_camera_world_x) * 0x140 / denominator;
    offset_y = 64 - (g_player_world_y - g_camera_world_y) * 0x163 / denominator + 0x94;
    model_set_screen_offset(offset_x, offset_y);
    model_render_node(&node, &identity);
    model_render_end();
    /* 0x800A0F40..0x800A0FF0 submits the second DR_OFFSET packet after the
     * indicator model.  AddPrim's LIFO order scopes the temporary offset to
     * that model and restores the PAL draw origin for later submissions. */
    model_set_screen_offset(160, 64);
}

/* Mission-HUD path of 0x800A0BF0..0x800A1178. */
/* Original: FUN_800A0BF0. */
void mission_hud_render(void)
{
    PLAYER *player = g_player;
    INVENTORY_SLOT *weapon = &player->inventory[g_selected_weapon_slot];
    sint32 counts;
    if (getenv("OA_HIERARCHY_PACKET_TRACE"))
    {
        static sint32 enabled;
        if (!enabled)
        {
            g_target_indicator_enabled = 1;
            g_target_indicator_model_id = g_radar_target_model_id;
            enabled = 1;
        }
    }
    {
        const char *trace_name = getenv("OA_MISSION_HUD_TRACE");
        if (trace_name)
        {
            static sint32 frames;
            if (frames < 4)
            {
                FILE *trace = fopen(strcmp(trace_name, "1") == 0 ? "mission_hud_port.log" : trace_name, frames ? "a" : "w");
                if (trace)
                {
                    fprintf(trace, "HUD %d tick=%u score=%u health=%u weapon=%u ammo=%u icon=%08x target=%d primary=%d secondary=%d\n", frames, g_frame_counter, (uint32)(uint16)player->ammunition, (uint32)player->health, (uint32)g_selected_weapon_slot, (uint32)weapon->count, (uint32)weapon->frame_id, (sint32)g_target_indicator_enabled, g_primary_objective_count, g_secondary_objective_count);
                    fclose(trace);
                }
                ++frames;
            }
        }
    }
    if (g_target_indicator_enabled != 0)
        draw_target_indicator();
    if (g_scuba_stage_active == 0)
    {
        g_text_color_index = 4;
        text_render(integer_to_text(player->ammunition), -0x80, -0x64);
    }
    if (weapon->frame_id != 0)
        render_screen_sprite(-0x70, 0x6c, weapon->frame_id, 0);
    if (weapon->count != 0xffff)
        text_render(integer_to_text(weapon->count), -0x60, 0x5c);
    hud_bar_render((MISSION_HUD_BAR *)g_player_health_bar, player->health, 0, 0);
    if ((g_frame_counter & 8) != 0)
        return;
    counts = mission_objective_counts();
    g_text_color_index = 1;
    if (g_primary_objective_count != g_primary_action_objective_present && g_primary_objective_count - g_primary_action_objective_present <= (counts >> 16))
        text_render("P", -0x80, 0x38);
    g_text_color_index = 4;
    if (g_secondary_objective_count != 0 && g_secondary_objective_count <= (counts & 0xffff))
        text_render("S", g_font_glyph_width - 0x80, 0x38);
    g_text_color_index = 0;
}
