#include <stdlib.h>
#include <string.h>
#include "app.h"
#include "audio/game_sound.h"
#include "collision.h"
#include "global.h"
#include "object.h"
#include "player.h"
#include "projectile.h"
#include "random.h"
#include "runtime_heap.h"
#include "sprite.h"
#include "vram_alloc.h"

/* Functions. */
/* Original: SLES_004.74:FUN_80096B58 (0x80096B58..0x80096B94).
 * Resident helper shared by AIRSHIP/SCUBA callers, not an overlay copy.
 * MIPS writes CLUT at DAT_800D401C - 0x1A, unlike FUN_80096B28,
 * which writes the embedded primitive at object + 0x52. */
void object_hit_flash_apply(FLASHABLE *object)
{
    if (object->flash_clut_ticks != 0)
    {
        --object->flash_clut_ticks;
        POLY_FT4 *prim = (POLY_FT4 *)((uint8 *)(intptr)g_transient_prim_cursor - sizeof(POLY_FT4));
        prim->clut = (uint16)g_hit_flash_clut;
    }
}

/* Semantic module generated by tools/merge_semantic_modules.py.
 * Original MIPS address comments remain attached to each function. */
/* Original: FUN_8008BEF0. */
GDB_CALL void linked_list_initialize(void *anchor_value)
{
    OBJECT **anchor;
    OBJECT *sentinel = (OBJECT *)runtime_heap_allocate(0x7c);
    if (vram_alloc_is_anchor(anchor_value))
    {
        /* PAL allocates a sentinel node here. The host VRAM list keeps the
         * equivalent empty anchor without exposing host pointers in its
         * original 32-bit descriptor fields. */
        vram_alloc_init_anchor(anchor_value);
        return;
    }
    anchor = (OBJECT **)anchor_value;
    sentinel->previous = 0;
    sentinel->next = 0;
    anchor[0] = sentinel;
    anchor[1] = sentinel;
}

/* Original: FUN_8008BF2C. */
void linked_list_append(void *anchor_value, void *object_value)
{
    OBJECT **anchor;
    OBJECT *object = (OBJECT *)object_value;
    if (vram_alloc_is_anchor(anchor_value))
    {
        vram_alloc_link_descriptor(anchor_value, object);
        return;
    }
    anchor = (OBJECT **)anchor_value;
    OBJECT *tail = anchor[1];
    tail->next = object;
    object->next = 0;
    object->previous = tail;
    anchor[1] = object;
}

/* 8008BF48: insert object immediately after an existing list node.  Camera
 * limit constructors use this with the sentinel so their callbacks run
 * before the player callback in FUN_8008BFBC. */
/* Original: FUN_8008BF48. */
void linked_list_insert_after(void *anchor_value, OBJECT *object, OBJECT *after)
{
    OBJECT **anchor = (OBJECT **)anchor_value;
    OBJECT *next = (OBJECT *)after->next;
    if (next != 0)
        next->previous = object;
    object->next = next;
    after->next = object;
    object->previous = after;
    if (anchor[1] == after)
        anchor[1] = object;
}

/* Original: FUN_8008C270. */
GDB_CALL void *object_find_next_by_type(void *after, sint16 object_type)
{
    OBJECT *object = after != 0 ? (OBJECT *)((OBJECT *)after)->next : g_object_list[0]->next;
    while (object != 0)
    {
        if (((COLLISION *)object)->object_type == object_type)
            return object;
        object = (OBJECT *)object->next;
    }
    return 0;
}

/* Direct FUN_8008C2A8 translation. */
sint16 object_count_by_type(sint16 object_type)
{
    void *object = object_find_next_by_type(0, object_type);
    sint16 count = 0;
    if (object == 0)
        return 0;
    do
    {
        object = object_find_next_by_type(object, object_type);
        ++count;
    } while (object != 0);
    return count;
}

/* Original: FUN_8008BF8C. */
void linked_list_unlink(void *anchor_value, OBJECT *object)
{
    OBJECT **anchor;
    OBJECT *previous;
    OBJECT *next;

    /* The Windows VRAM allocator stores a stable region token in the
     * descriptor's original 32-bit +0x10 anchor field.  Preserve the PAL
     * FUN_8008BF8C call boundary while delegating only that host backing. */
    if (anchor_value != (void *)g_object_list)
    {
        vram_alloc_unlink_descriptor(anchor_value, object);
        return;
    }
    anchor = (OBJECT **)anchor_value;
    previous = (OBJECT *)object->previous;
    next = (OBJECT *)object->next;

    previous->next = next;
    if (next != 0)
        next->previous = previous;
    else
        anchor[1] = previous;
}

/* Original: FUN_8008C008. */
GDB_CALL void object_destroy(void *object)
{
    linked_list_unlink((void *)g_object_list, (OBJECT *)object);
    runtime_heap_defer_free(object);
}

/* 8008C35C..8008C3BC: remove every object having the requested type and
 * return the last removed object (or NULL when no object existed). */
/* Original: FUN_8008C35C. */
__declspec(noinline) void *object_destroy_all_by_type(sint16 type)
{
    void *after = 0;
    void *object;
    do
    {
        object = object_find_next_by_type(after, type);
        if (object != 0)
        {
            object_destroy(object);
            after = object;
        }
    } while (object != 0);
    return after;
}

/* Original: FUN_800A16F8. */
GDB_CALL void *destroyable_object_damage_and_reward(COLLISION *target, COLLISION *source)
{
    SPRITE *actor;
    VRAM_SPRITE *resource;
    const sint32 *animation;
    sint32 random;
    sint16 type;

    if (object_damage_apply((FLASHABLE *)target, (FLASHABLE *)source) == 0)
        return 0;
    resource = (VRAM_SPRITE *)target->frame_descriptor;
    if (resource != 0 && resource->region_token != 0)
        sprite_vram_defer_release(resource);
    object_destroy(target);
    speech_random_request(1);
    ++g_destroyed_reward_object_count;
    type = target->object_type;
    if (type == 0x37)
        --g_remaining_flame_target_count;
    if (type == 0x66 || type == 0x7e)
        ++g_destroyed_special_target_count;

    random = random_range(2);
    if (random == 0)
        animation = (const sint32 *)player_assets_executable_address(0x800ca338u);
    else if (random == 1)
        animation = (const sint32 *)player_assets_executable_address(0x800ca34cu);
    else
        animation = (const sint32 *)player_assets_executable_address(0x800ca360u);

    if (type == 0x66 || type == 0x7e || type == 0x92)
    {
        target->y -= 0x4000;
        damage_expl_create(target, 1);
        return 0;
    }

    actor = world_sprite_create(target->x, target->y, target->z, animation);
    actor->field_a8 = 0x80;
    actor->field_aa = -9;
    actor->velocity_y = -(random_range(0x200) + 0x500);
    if (g_scuba_stage_active == 0)
    {
        actor->acceleration_y = 0x55;
        actor->velocity_y = -(random_range(0x200) + 0x500);
        if (g_stage_index == 0x0b)
            sound_play_positional(0x69, 0, 0x7f, target->x, target->y, target->z);
        else
            sound_play_positional(random_range(2) + 0x13, 0, 0x7f, target->x, target->y, target->z);
    }
    else
    {
        actor->acceleration_y = 8;
        actor->velocity_y = -(random_range(0x200) + 0x200);
        sound_play_positional(0xa5, 0, 0xc8, target->x, target->y, target->z);
    }
    actor->scale_x = (uint16)g_default_model_scale;
    random = random_range(0x200);
    actor->velocity_x = random - 0x100;
    if (random - 0x100 < 0)
        random -= 0xe1;
    else
        random -= 0x100;
    actor->rotation_step_x = (sint16)(random >> 5);
    if (source->object_type == 2)
    {
        actor->velocity_y -= 0x200;
        actor->velocity_x *= 2;
        actor->rotation_step_x = (sint16)(actor->rotation_step_x * 3);
    }
    return actor;
}

/* FUN_8008BFBC: invoke the per-frame callback for every object-list node. */

GDB_CALL void object_list_update(void)
{
    OBJECT *object = g_object_list[0]->next;

    while (object != 0)
    {
        if (object->update != 0)
            object->update(object);
        object = (OBJECT *)object->next;
    }
}

/* Original: FUN_8008C310. */
GDB_CALL void *object_create(sint32 size, FUNC_COLLISION_UPDATE callback)
{
    /* FUN_8008C310 calls FUN_8008C414 directly.  Keep every object on the
     * same deferred-free heap; callbacks in the original may continue to
     * inspect an object after FUN_8008C008 unlinks it. */
    OBJECT *object = (OBJECT *)runtime_heap_allocate(size);
    object->update = callback;
    linked_list_append((void *)g_object_list, object);
    return object;
}
