#include <stddef.h>
#include <stdlib.h>
#include "animation.h"
#include "game_sound.h"
#include "camera.h"
#include "collision.h"
#include "global.h"
#include "level_data.h"
#include "map.h"
#include "model.h"
#include "object.h"
#include "player.h"
#include "projectile.h"
#include "psx.h"
#include "random.h"
#include "runtime_heap.h"
#include "sprite.h"
#include "sprite_renderer.h"
#include "stubs.h"
#include "vram_alloc.h"

/* Functions. */
/* Semantic module generated by tools/merge_semantic_modules.py.
 * Original MIPS address comments remain attached to each function. */
/* Original: FUN_80098244. */
sint16 swept_collision_test(sint32 old_x, sint32 old_y, sint32 old_z, sint32 *new_x, sint32 *new_y, sint32 *new_z)
{
    sint32 x_cell = div_16384_trunc(*new_x);
    sint32 z_cell = div_16384_trunc((g_map_depth_cells * 3 << 14) - *new_z);
    uint16 group_index;
    MAP_MODEL_GROUP *group;
    MAP_MODEL_INSTANCE *instance;
    sint32 center_x = (*new_x & (sint32)0xffffc0ff) + 0x2000;
    sint32 center_z = (*new_z & (sint32)0xffffc0ff) + 0x2000;
    sint32 count, i;

    g_collision_flags = 0;
    group_index = g_map_floor_cells[x_cell + z_cell * g_map_width_cells].group_index;
    group = (MAP_MODEL_GROUP *)((uint8 *)g_map_model_groups + (uint32)group_index * sizeof(*group));
    if (group == g_map_model_groups)
        return 0;
    count = group->active_count;
    instance = (MAP_MODEL_INSTANCE *)(group + 1);
    for (i = 0; i < count; ++i, instance++)
    {
        sint16 model_index = instance->model_id;
        sint32 model_y = (sint32)instance->y << 8;
        sint32 half_y = g_model_descriptors[model_index].half_y << 8;
        sint32 top = model_y + half_y;
        sint32 bottom = model_y - half_y;

        if (*new_y - 0x800 < top && bottom < *new_y)
        {
            *new_y = top;
            g_collision_flags |= 1;
            return (sint16)g_collision_flags;
        }
        /* SLES_004.74 0x80098384..0x800983a0:
             *   slt v0,t7,(model_y-half_y)  => new_y < bottom
             *   slt v0,(model_y+half_y),t7  => top < new_y
             * half_y is negative in the original descriptor, so this is
             * the strict interval top < new_y < bottom. */
        if (*new_y < bottom && top < *new_y)
        {
            if (old_x < *new_x && *new_x < center_x)
            {
                *new_x = center_x - 0x2800;
                g_collision_flags |= 2;
            }
            if (*new_x < old_x && center_x < *new_x)
            {
                *new_x = center_x + 0x2800;
                g_collision_flags |= 2;
            }
            if (old_z < *new_z && *new_z < center_z)
            {
                *new_z = center_z - 0x2800;
                g_collision_flags |= 4;
            }
            if (*new_z < old_z && center_z < *new_z)
            {
                *new_z = center_z + 0x2800;
                g_collision_flags |= 4;
            }
            return (sint16)g_collision_flags;
        }
    }

    if (*new_z != old_z || *new_x != old_x)
    {
        COLLISION_RESULT *result = runtime_object_collision_resolve(old_x, old_y, old_z, *new_x, *new_y, *new_z, 0x100, 0x100);
        g_current_collision_result = result;
        *new_x = result->x;
        *new_y = result->y;
        *new_z = result->z;
        g_collision_flags |= result->flags;
    }
    if ((g_collision_flags & 4) == 0)
        return 0;
    return (sint16)g_collision_flags;
}

/* Direct translation of PSX FUN_800933E8 (SLES_004.74 0x800933E8). */

sint32 world_object_is_visible(sint32 x, sint32 y, sint32 z, sint32 diameter)
{
    sint32 depth, half, projected, vertical_limit, map_limit;
    if (z == g_camera_world_z)
        return 0;
    half = diameter / 2;
    depth = z - g_camera_world_z;
    projected = ((x - half) - g_camera_world_x) * 320 / depth;
    if (projected > g_screen_half_width)
        return 0;
    projected = ((x + half) - g_camera_world_x) * 320 / depth;
    if (projected < -g_screen_half_width)
        return 0;
    if (z > g_camera_world_z + 0x3e800)
        return 0;
    map_limit = g_map_depth_cells * 3 << 14;
    if (z >= map_limit)
        return 0;
    if (z < g_camera_world_z + 0x4000)
        return 0;
    if (z <= map_limit - (g_map_depth_cells << 14) + 0x4000)
        return 0;
    vertical_limit = g_screen_height / 2 + 0x80;
    projected = (y - g_camera_world_y) * 355 / depth;
    if (projected < -vertical_limit)
        return 0;
    projected = (y - (g_camera_world_y + 0x8000)) * 355 / depth;
    return projected <= vertical_limit;
}

/* Direct translation of FUN_80092CF0. */
GDB_CALL FrameObjectPartial *frame_model_object_create(COLLISION *object, sint32 model_plus_one)
{
    FrameObjectPartial *record = g_next_frame_object;
    if (record >= g_frame_objects + FRAME_OBJECT_LIMIT)
        return record;
    record->world_x = object->x;
    record->world_y = object->y;
    record->world_z = object->z;
    record->drawn = 0;
    record->model_plus_one = model_plus_one;
    record->x_subcell_offset = 0;
    record->model_rot_y = 0;
    record->model_rot_x = 0;
    record->model_rot_z = 0;
    record->light_delta = 0;
    record->ot_bucket = 0;
    g_next_frame_object = record + 1;
    return record;
}

/* Direct translation of FUN_8009080C. */
void world_sprite_destroy(SPRITE *object)
{
    if (object->owns_resource != 0)
    {
        void *resource = object->collision.frame_descriptor;
        sprite_vram_defer_release(resource);
        runtime_heap_defer_free(resource);
    }
    object_destroy(object);
}

/* Original: FUN_80090F5C. */
void projectile_surface_impact_emit(sint32 x, sint32 y, sint32 z)
{
    const sint16 *impact_sounds = (const sint16 *)player_assets_executable_address(0x800c8cb4u);
    sint32 sound = impact_sounds[random_range(4)];
    if (g_projectile_effect_cooldown == 0)
    {
        sound_play_positional(sound, random_range(8) - 4, 0x6e, x, y, z);
        g_projectile_effect_cooldown = 12;
    }
    if (random_range(4) == 0)
    {
        SPRITE *spark = world_sprite_create(x, y - 0x1000, z - 0x100, (const sint32 *)player_assets_executable_address(0x800c932cu));
        spark->field_a8 = 0x80;
        spark->field_aa = -0x10;
        spark->rotation_step_x = 0x10;
        spark->scale_step = (sint16)(random_range(0x80) + 0x80);
        spark->field_ae = 1;
        spark->scale_x = 1;
    }
}

/* Original: FUN_80091058. */
SPRITE *surface_impact_create(sint32 x, sint32 y, sint32 z, const sint32 *animation)
{
    VRAM_SPRITE *descriptor = (VRAM_SPRITE *)runtime_heap_allocate(sizeof(*descriptor));
    SPRITE *effect = world_sprite_create(x, y, z, animation);
    effect->owns_resource = 1;
    if (animation == (const sint32 *)player_assets_executable_address(0x800c8db8u))
        sprite_vram_allocate(descriptor, 0x20, 0x30, 0);
    else
        sprite_vram_allocate(descriptor, 0x40, 0x68, 0);
    effect->collision.frame_descriptor = descriptor;
    /* 0x800D76D4 is not an independent scalar.  In the original RAM layout
     * it is DAT_800D75D8[(0x1F800 >> 10)], the shared CLUT slot for the
     * 0x1F800 surface-impact/splash frames. */
    descriptor->clut = g_resource_clut_table[0x1f800u >> 10];
    effect->field_a8 = -0x40;
    effect->field_9e = 2;
    return effect;
}

/* Direct decompilation of FUN_80090860. */
void world_sprite_update(SPRITE *object)
{
    sint32 old_x = object->collision.x;
    sint32 old_y = object->collision.y;
    sint32 old_z = object->collision.z;
    sint32 lifetime;
    sint32 frame;
    VRAM_SPRITE *descriptor = 0;
    void (*callback)(void *);

    if (object->scale_y == 0)
        object->scale_y = object->scale_x;

    object->collision.x += object->velocity_x;
    object->collision.y += object->velocity_y;
    object->collision.z += object->velocity_z;
    if (object->render_kind == 3 && object->collision.z < g_camera_world_z + 0x8000)
    {
        world_sprite_destroy(object);
        return;
    }
    if (object->owns_resource != 0)
        descriptor = (VRAM_SPRITE *)object->collision.frame_descriptor;

    lifetime = object->lifetime;
    if (lifetime != 0)
    {
        if (lifetime == 0x1e && object->collision.object_type == 0x40)
        {
            object->collision.receives_mask = 0;
            object->collision.sends_mask = 0;
        }
        object->lifetime = (sint16)(lifetime - 1);
        if (lifetime == 1)
        {
            world_sprite_destroy(object);
            return;
        }
    }
    if (object->collision.object_type == 10)
    {
        player_projectile_impact_update(object, old_x, old_y, old_z);
        if (object->damage == 0)
            return;
    }
    if (object->render_kind != 2 && object->render_kind != 3)
        object->rotation_x = (sint16)((object->rotation_x + object->rotation_step_x) & 0x3ff);
    object->velocity_x += object->acceleration_x;
    object->velocity_y += object->acceleration_y;
    object->velocity_z += object->acceleration_z;
    object->scale_x = (uint16)(object->scale_x + object->scale_step);
    if (object->scale_y != 0)
        object->scale_y = (uint16)(object->scale_y + object->scale_step);
    if (object->cull_distance == 0)
        object->cull_distance = 0x8000;
    frame = animation_update(&object->animation);
    if ((uint32)frame > 0x30800u)
        fatal_error_with_value("BAD FRAME", (sint32)object->animation.start_address);

    callback = object->frame_callback;
    if (callback != 0)
        callback(object);

    g_collision_flags = 0;
    callback = object->collision_callback;
    if (callback != 0)
    {
        sint32 y_offset = 0;
        MODEL_NODE *model = object->model;
        if (model != 0)
        {
            sint32 descriptor_index = model->model_id;
            y_offset = -g_model_descriptors[descriptor_index].half_y << 8;
        }
        object->collision.y += y_offset;
        if (player_collision_resolve(old_x, old_y + y_offset, old_z, &object->collision.x, &object->collision.y, &object->collision.z, &object->velocity_x, &object->velocity_y, 0x10, 0x50, 5) != 0)
            callback(object);
        object->collision.y -= y_offset;
    }
    callback = object->impact_callback;
    if (callback != 0 && (g_collision_flags & 6) != 0)
        callback(object);

    /* 80090B80..80090BA8: the original writes the current frame record
       unconditionally; frame setup guarantees DAT_800D3F80 here. */
    g_next_frame_object->light_delta = object->field_a8;
    g_next_frame_object->force_light = object->field_ae;
    object->field_a8 = (sint16)(object->field_a8 + object->field_aa);

    if (object->render_kind == 0)
    {
        sint32 visible = world_object_is_visible(object->collision.x, object->collision.y, object->collision.z, object->cull_distance);
        sint32 draw = 1;
        if (!visible || (uint32)object->collision.z < (uint32)((g_map_depth_cells * 3 << 14) - (g_map_depth_subcells << 8)))
        {
            if (object->field_9c == 0)
            {
                world_sprite_destroy(object);
                return;
            }
            draw = 0;
        }
        if (draw)
        {
            render_world_sprite(frame, object->collision.x, object->collision.y, object->collision.z, object->velocity_x, object->scale_x, object->scale_y, (POLY_FT4 *)object->collision.prim, object->field_ac, object->field_9e, descriptor, object->rotation_x);
            if (object->clut_override != 0)
                ((POLY_FT4 *)object->collision.prim)->clut = object->clut_override;
        }
    }
    else if (object->render_kind == 1)
    {
        render_world_sprite_immediate(frame, object->collision.x, object->collision.y, object->collision.z, object->velocity_x, object->scale_x, object->scale_y, (sint32)object->collision.prim, 0, 0, 0, object->rotation_x);
    }
    else if (object->render_kind == 2)
    {
        FrameObjectPartial *model;
        if (!world_object_is_visible(object->collision.x, object->collision.y, object->collision.z, object->cull_distance) && (uint32)object->collision.z >= (uint32)((g_map_depth_cells * 3 << 14) - (g_map_depth_subcells << 8)))
        {
            world_sprite_destroy(object);
            return;
        }
        object->rotation_x = (sint16)((object->rotation_x + object->rotation_step_x) & 0xfff);
        object->rotation_y = (sint16)((object->rotation_y + object->rotation_step_y) & 0xfff);
        object->rotation_z = (sint16)((object->rotation_z + object->rotation_step_z) & 0xfff);
        model = frame_model_object_create(&object->collision, (sint32)object->animation.frame);
        model->model_rot_y = object->rotation_x;
        model->model_rot_x = object->rotation_y;
        model->model_rot_z = object->rotation_z;
    }
    else if (object->render_kind == 3)
    {
        /* SLES_004.74 0x80090de8..0x80090f0c.  DAT_800C8DEC is the
         * byte-exact identity MATRIX embedded in the executable. */
        static MATRIX identity = {{{ONE, 0, 0}, {0, ONE, 0}, {0, 0, ONE}}, {0, 0, 0}};
        MODEL_NODE *model = object->model;
        sint32 depth_delta;

        model->rotation_y = (sint16)((model->rotation_y + (uint16)object->rotation_step_x) & 0xfff);
        model->rotation_x = (sint16)((model->rotation_x + (uint16)object->rotation_step_y) & 0xfff);
        model->rotation_z = (sint16)((model->rotation_z + (uint16)object->rotation_step_z) & 0xfff);
        model->translation_x = object->collision.x - g_camera_world_x;
        model->translation_y = object->collision.y - g_camera_world_y;
        model->translation_z = object->collision.z - g_camera_world_z;
        g_model_render_frame = g_current_render_frame;
        depth_delta = g_render_row_world_z - object->collision.z;
        if (depth_delta < 0)
            depth_delta += 0xff;
        g_render_depth_bucket = 0x480 - (depth_delta >> 8);
        g_current_model_world_z = object->collision.z;
        model_render_node(model, &identity);
    }

    if (object->animation.next_address == 0)
    {
        world_sprite_destroy(object);
        return;
    }
}

/* Direct decompilation of FUN_80090758. */
SPRITE *world_sprite_create(sint32 x, sint32 y, sint32 z, const sint32 *animation)
{
    SPRITE *object = (SPRITE *)object_create(sizeof(*object), world_sprite_update);
    POLY_FT4 *prim = (POLY_FT4 *)object->collision.prim;

    SetPolyFT4(prim);
    setShadeTex(prim, 0);
    object->scale_x = 0x1000;
    animation_start(&object->animation, animation);
    object->animation.owner_address = (uint32)object;
    object->collision.x = x;
    object->collision.y = y;
    object->collision.z = z;
    object->field_9e = 1;
    return object;
}

/* Original: FUN_80099320. */
SPRITE *expl_flash_create(sint32 x, sint32 y, sint32 z)
{
    SPRITE *effect = world_sprite_create(x, y, z, (const sint32 *)player_assets_executable_address(0x800c932c));
    effect->cull_distance = 0x3e8000;
    effect->field_a8 = 0x80;
    effect->field_aa = -0x10;
    effect->rotation_step_x = 0x10;
    effect->scale_step = 0x400;
    effect->field_ac = 1;
    effect->field_ae = 1;
    return effect;
}

/* Direct FUN_80099380 grenade callback. */
void thrown_explosive_update(void *raw_object)
{
    SPRITE *object = (SPRITE *)raw_object;
    sint32 old_x = object->collision.x, old_y = object->collision.y, old_z = object->collision.z;
    sint16 type = object->collision.object_type;
    sint32 velocity;
    world_sprite_update(object);
    if ((g_held_buttons & 0x20) == 0)
        object->acceleration_y = 0xa0;
    player_collision_resolve(old_x, old_y, old_z, &object->collision.x, &object->collision.y, &object->collision.z, 0, 0, 0x10, 0x10, 6);
    if (g_collision_flags & 8)
        object->velocity_y = -object->velocity_y;
    if (g_collision_flags & 4)
    {
        velocity = -object->velocity_z;
        object->velocity_z = (velocity < 0 ? velocity + 3 : velocity) >> 2;
    }
    if (g_collision_flags & 2)
    {
        velocity = -object->velocity_x;
        object->velocity_x = (velocity < 0 ? velocity + 3 : velocity) >> 2;
    }
    if ((g_collision_flags & 9) != 0 && type != 0x0b)
    {
        velocity = -object->velocity_y;
        object->velocity_y = (velocity < 0 ? velocity + 3 : velocity) >> 2;
        object->velocity_x = (object->velocity_x + (sint32)((uint32)object->velocity_x >> 31)) >> 1;
        object->velocity_z = (object->velocity_z + (sint32)((uint32)object->velocity_z >> 31)) >> 1;
        if ((object->velocity_y < 0 ? -object->velocity_y : object->velocity_y) > 0x100)
            sound_play_positional(0x18, 0, 0x7f, object->collision.x, object->collision.y, object->collision.z);
    }
    if ((g_collision_flags & 6) != 0 && type != 0x0b && ((object->velocity_x < 0 ? -object->velocity_x : object->velocity_x) > 0x100 || (object->velocity_z < 0 ? -object->velocity_z : object->velocity_z) > 0x100))
        sound_play_positional(0x18, 0, 0x7f, object->collision.x, object->collision.y, object->collision.z);
    if (g_collision_flags != 0 && type == 0x0b)
        sound_play_positional(0x18, 0, 0x7f, object->collision.x, object->collision.y, object->collision.z);
    if (type == 0x86)
    {
        SPRITE *smoke = (SPRITE *)continuous_weapon_particle_create(object->collision.x, object->collision.y - 0x1000, object->collision.z - 0x100, g_signal_flare_sprite_clut);
        if (smoke != 0)
        {
            smoke->field_aa = -3;
            smoke->collision.receives_mask = 4;
            smoke->collision.sends_mask = 0x80;
            smoke->damage = 1;
            smoke->velocity_x *= 2;
            collision_box_set(smoke, 0xe6, 0xe6, 0xe6);
            object->collision.box_y += 0x2000;
        }
    }
    if ((g_collision_flags & 1) != 0 && type == 0x0b)
    {
        SPRITE *effect;
        sint32 surface = g_stage_env->map_resource;
        object_destroy(object);
        if (g_collision_surface_resource == surface || g_collision_surface_resource == -1)
        {
            effect = surface_impact_create(old_x, old_y, old_z, (const sint32 *)player_assets_executable_address(0x800c8d3c));
            g_shared_result_pointer = effect;
            sound_play_positional(0x24, 0, 0x96, old_x, old_y, old_z);
        }
        else
        {
            effect = world_sprite_create(old_x, old_y, old_z, (const sint32 *)player_assets_executable_address(0x800c8b5c));
            g_shared_result_pointer = effect;
            sound_play_positional(9, 0, 0x96, old_x, old_y, old_z);
            expl_flash_create(old_x, old_y - 0x4000, old_z - 0x100);
        }
        effect->cull_distance = 0x3e800;
        effect->field_ae = 1;
        effect->scale_x = (uint16)(random_range(0x800) + 0x2000);
        collision_box_set(effect, 0xa0, 0x60, 0x80);
        effect->collision.receives_mask = 4;
        effect->collision.sends_mask = 1;
        effect->collision.object_type = 2;
        effect->damage = 1;
        effect->collision.box_y += 0x1000;
        player_particle_ring_create(effect->collision.x, effect->collision.y, effect->collision.z, 0x0c, 3);
        camera_shake_start();
    }
}

/* Direct FUN_80099230 constructor. */
SPRITE *thrown_explosive_create(sint32 x, sint32 y, sint32 z, const sint32 *animation)
{
    SPRITE *object = (SPRITE *)runtime_heap_allocate(sizeof(*object));
    POLY_FT4 *prim = (POLY_FT4 *)object->collision.prim;
    sint16 type;
    SetPolyFT4(prim);
    setShadeTex(prim, 0);
    object->collision.update = thrown_explosive_update;
    linked_list_append(g_object_list, object);
    object->cull_distance = 0x3e800;
    object->scale_x = 0x1708;
    animation_start(&object->animation, animation);
    object->collision.x = x;
    object->collision.y = y;
    object->collision.z = z;
    type = g_player->field_240;
    object->collision.object_type = type == 0x89 ? 0x86 : type;
    return object;
}

/* Direct special-projectile callbacks FUN_8009DF84/FUN_8009E118/FUN_800A1C70. */

static sint32 clamp(sint32 value, sint32 minimum, sint32 maximum)
{
    if (value < minimum)
        return minimum;
    if (value > maximum)
        return maximum;
    return value;
}

void homing_projectile_steer(SPRITE *object)
{
    sint32 vx = object->velocity_x;
    sint32 vz = object->velocity_z;
    /* 0x8009DFAC: slt v0, abs(vz), abs(vx).  Steer the weaker
     * horizontal component so homing does not rotate the dominant axis. */
    if ((vz < 0 ? -vz : vz) < (vx < 0 ? -vx : vx))
    {
        if (object->collision.z < object->field_d4)
            vz += 0x40;
        if (object->collision.z > object->field_d4)
            vz -= 0x40;
        object->velocity_z = clamp(vz, -0x400, 0x400);
    }
    else
    {
        if (object->collision.x < object->field_cc)
            vx += 0x40;
        if (object->collision.x > object->field_cc)
            vx -= 0x40;
        object->velocity_x = clamp(vx, -0x400, 0x400);
    }
    if (object->collision.y < object->field_d0)
        object->velocity_y += 0x40;
    if (object->collision.y > object->field_d0)
        object->velocity_y -= 0x40;
    object->velocity_y = clamp(object->velocity_y, -0x200, 0x200);
}

/* Original: FUN_800A1C70. */
void projectile_trail_emit(SPRITE *object)
{
    if ((g_frame_counter & 3) == 0)
    {
        SPRITE *trail = world_sprite_create(object->collision.x, object->collision.y + 0x800, object->collision.z + 0x100, (const sint32 *)player_assets_executable_address(0x800c8bc8u));
        trail->scale_x = 0x800;
        trail->field_ae = 1;
    }
}

/* Direct FUN_800A4DC0, using its original 64x64 fixed-angle table at
 * 0x800C3E74. */
sint32 fixed_angle_from_vector(sint32 x, sint32 z)
{
    const sint32 *table = (const sint32 *)player_assets_executable_address(0x800c3e74u);
    sint32 ax = x < 0 ? -x : x;
    sint32 az = z < 0 ? -z : z;
    sint32 angle;
    angle = table[(ax & 0x3f) + ((az & 0x3f) << 6)];
    if (z < 0)
        angle = 0x200 - angle;
    if (x < 0)
        angle = 0x400 - angle;
    return angle;
}
