#include <stddef.h>
#include "app.h"
#include "global.h"
#include "stubs.h"

/* Functions. */
/* Semantic module generated by tools/merge_semantic_modules.py.
 * Original MIPS address comments remain attached to each function. */
/* Decompilation of FUN_8008E3A0.
 *
 * The pool is exactly 0x700 bytes: 64 buckets * 0x1c bytes. FUN_8008E410
 * fills each bucket with up to 24 indices of visible/spatial objects and stores
 * the bucket number in a byte map indexed by cell_index.
 */

/* 0x700-byte bucket pool */
/* cell -> bucket index map */

static void spatial_bucket_storage_clear(void)
{
    sint32 i;

    for (i = 0; i < SPATIAL_BUCKET_COUNT; ++i)
    {
        SpatialBucket *bucket = &g_spatial_buckets[i];

        bucket->count = 0;
        g_spatial_cell_bucket_indices[bucket->cell_index] = 0;
        bucket->cell_index = 0;
    }
}

/* Original: FUN_8008E3A0. */
void spatial_buckets_reset(void)
{
    spatial_bucket_storage_clear();
}

void spatial_buckets_build(void)
{
    FrameObjectPartial *object = g_frame_objects;
    uint16 object_index = 0;
    uint32 allocated_buckets = 0;

    while (object < g_next_frame_object)
    {
        sint32 x = object->world_x + object->x_subcell_offset * 0x100;
        sint32 y = g_map_depth_cells * 0xc000 - object->world_z;
        sint32 cell_index;
        uint32 bucket_index;
        SpatialBucket *bucket;

        g_frame_object_lookup[object_index] = object;

        /* The compiler implements signed division by 0x4000 with this
         * pre-add before the arithmetic shift. */
        if (x < 0)
            x += 0x3fff;
        if (y < 0)
            y += 0x3fff;
        cell_index = (x >> 14) + (y >> 14) * g_map_width_cells;

        bucket_index = g_spatial_cell_bucket_indices[(sint16)cell_index];
        if (bucket_index == 0)
        {
            bucket_index = ++allocated_buckets;
            g_spatial_cell_bucket_indices[(sint16)cell_index] = (uint8)bucket_index;
            g_spatial_buckets[bucket_index].cell_index = (sint16)cell_index;
        }
        bucket = &g_spatial_buckets[bucket_index];
        if (bucket->count < SPATIAL_BUCKET_CAPACITY)
            bucket->object_indices[bucket->count++] = (uint8)object_index;

        ++object_index;
        ++object;
        if (object_index > 0xffu)
            fatal_error("SORT TABLE TOO SMALL");
    }
    g_frame_object_lookup[object_index] = NULL;
}
